import { AtlasCluster, AtlasEdge, AtlasNode, AtlasZoomView, EdgeWord } from './atlas.models';

export const FIRE_VERTEX_SHADER = `
varying vec3 vWorldPos;

void main() {
  gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
  vWorldPos = (modelMatrix * vec4(position, 1.0)).xyz;
}
`;

export const FIRE_FRAGMENT_SHADER = `
precision highp float;

#define ITERATIONS 10
#define OCTIVES 3

uniform vec3 color;
uniform float time;
uniform float seed;
uniform mat4 invModelMatrix;
uniform vec3 scale;
uniform vec4 noiseScale;
uniform float magnitude;
uniform float lacunarity;
uniform float gain;
uniform sampler2D fireTex;
varying vec3 vWorldPos;

vec4 permute(vec4 x) {
  return mod(((x * 34.0) + 1.0) * x, 289.0);
}

vec4 taylorInvSqrt(vec4 r) {
  return 1.79284291400159 - 0.85373472095314 * r;
}

float snoise(vec3 v) {
  const vec2 c = vec2(1.0 / 6.0, 1.0 / 3.0);
  const vec4 d = vec4(0.0, 0.5, 1.0, 2.0);

  vec3 i = floor(v + dot(v, c.yyy));
  vec3 x0 = v - i + dot(i, c.xxx);
  vec3 g = step(x0.yzx, x0.xyz);
  vec3 l = 1.0 - g;
  vec3 i1 = min(g.xyz, l.zxy);
  vec3 i2 = max(g.xyz, l.zxy);
  vec3 x1 = x0 - i1 + c.xxx;
  vec3 x2 = x0 - i2 + c.yyy;
  vec3 x3 = x0 - d.yyy;

  i = mod(i, 289.0);
  vec4 p = permute(
    permute(
      permute(i.z + vec4(0.0, i1.z, i2.z, 1.0))
      + i.y + vec4(0.0, i1.y, i2.y, 1.0)
    )
    + i.x + vec4(0.0, i1.x, i2.x, 1.0)
  );

  float n_ = 1.0 / 7.0;
  vec3 ns = n_ * d.wyz - d.xzx;
  vec4 j = p - 49.0 * floor(p * ns.z * ns.z);
  vec4 x_ = floor(j * ns.z);
  vec4 y_ = floor(j - 7.0 * x_);

  vec4 x = x_ * ns.x + ns.yyyy;
  vec4 y = y_ * ns.x + ns.yyyy;
  vec4 h = 1.0 - abs(x) - abs(y);
  vec4 b0 = vec4(x.xy, y.xy);
  vec4 b1 = vec4(x.zw, y.zw);
  vec4 s0 = floor(b0) * 2.0 + 1.0;
  vec4 s1 = floor(b1) * 2.0 + 1.0;
  vec4 sh = -step(h, vec4(0.0));
  vec4 a0 = b0.xzyw + s0.xzyw * sh.xxyy;
  vec4 a1 = b1.xzyw + s1.xzyw * sh.zzww;
  vec3 p0 = vec3(a0.xy, h.x);
  vec3 p1 = vec3(a0.zw, h.y);
  vec3 p2 = vec3(a1.xy, h.z);
  vec3 p3 = vec3(a1.zw, h.w);

  vec4 norm = taylorInvSqrt(vec4(dot(p0, p0), dot(p1, p1), dot(p2, p2), dot(p3, p3)));
  p0 *= norm.x;
  p1 *= norm.y;
  p2 *= norm.z;
  p3 *= norm.w;

  vec4 m = max(0.6 - vec4(dot(x0, x0), dot(x1, x1), dot(x2, x2), dot(x3, x3)), 0.0);
  m = m * m;
  return 42.0 * dot(m * m, vec4(dot(p0, x0), dot(p1, x1), dot(p2, x2), dot(p3, x3)));
}

float turbulence(vec3 p) {
  float sum = 0.0;
  float freq = 1.0;
  float amp = 1.0;

  for (int i = 0; i < OCTIVES; i++) {
    sum += abs(snoise(p * freq)) * amp;
    freq *= lacunarity;
    amp *= gain;
  }

  return sum;
}

vec4 samplerFire(vec3 p, vec4 scaleValue) {
  vec2 st = vec2(sqrt(dot(p.xz, p.xz)), p.y);

  if (st.x <= 0.0 || st.x >= 1.0 || st.y <= 0.0 || st.y >= 1.0) {
    return vec4(0.0);
  }

  p.y -= (seed + time) * scaleValue.w;
  p *= scaleValue.xyz;
  st.y += sqrt(st.y) * magnitude * turbulence(p);

  if (st.y <= 0.0 || st.y >= 1.0) {
    return vec4(0.0);
  }

  return texture2D(fireTex, st);
}

vec3 localize(vec3 p) {
  return (invModelMatrix * vec4(p, 1.0)).xyz;
}

void main() {
  vec3 rayPos = vWorldPos;
  vec3 rayDir = normalize(rayPos - cameraPosition);
  float rayLen = 0.0288 * length(scale.xyz);
  vec4 col = vec4(0.0);

  for (int i = 0; i < ITERATIONS; i++) {
    rayPos += rayDir * rayLen;
    vec3 lp = localize(rayPos);
    lp.y += 0.5;
    lp.xz *= 2.0;
    col += samplerFire(lp, noiseScale);
  }

  col.a = col.r;
  gl_FragColor = col;
}
`;

export const EDGE_WORD_CLOUD: Record<'top' | 'right' | 'bottom' | 'left', EdgeWord[]> = {
  top: [
    { text: 'Revelation', offset: 10, size: 11, alpha: 0.16, delay: 0.4, tilt: -8 },
    { text: 'Truth', offset: 21, size: 14, alpha: 0.28, delay: 1.2, tilt: -4 },
    { text: 'Justice', offset: 35, size: 13, alpha: 0.24, delay: 2.1, tilt: 3 },
    { text: 'Prophets', offset: 49, size: 12, alpha: 0.2, delay: 0.9, tilt: -2 },
    { text: 'Covenant', offset: 64, size: 11, alpha: 0.18, delay: 2.8, tilt: 6 },
    { text: 'Hereafter', offset: 79, size: 13, alpha: 0.24, delay: 1.8, tilt: -5 },
    { text: 'Mercy', offset: 90, size: 11, alpha: 0.16, delay: 3.2, tilt: 8 },
  ],
  right: [
    { text: 'Scripture', offset: 12, size: 11, alpha: 0.16, delay: 1.1, tilt: -5 },
    { text: 'Law', offset: 24, size: 14, alpha: 0.26, delay: 2.3, tilt: 2 },
    { text: 'Worship', offset: 38, size: 11, alpha: 0.18, delay: 0.6, tilt: -4 },
    { text: 'Family', offset: 54, size: 13, alpha: 0.24, delay: 2.9, tilt: 5 },
    { text: 'Authors', offset: 70, size: 11, alpha: 0.16, delay: 1.7, tilt: -3 },
    { text: 'Providence', offset: 84, size: 11, alpha: 0.16, delay: 3.4, tilt: 4 },
  ],
  bottom: [
    { text: 'Capitalism', offset: 12, size: 11, alpha: 0.17, delay: 0.8, tilt: 6 },
    { text: 'Modernity', offset: 26, size: 13, alpha: 0.24, delay: 1.5, tilt: -5 },
    { text: 'Media', offset: 40, size: 12, alpha: 0.18, delay: 3.1, tilt: 2 },
    { text: 'Power', offset: 53, size: 14, alpha: 0.24, delay: 2.2, tilt: -4 },
    { text: 'Society', offset: 67, size: 12, alpha: 0.2, delay: 0.5, tilt: 4 },
    { text: 'Education', offset: 80, size: 11, alpha: 0.16, delay: 2.7, tilt: -6 },
  ],
  left: [
    { text: 'Thinkers', offset: 16, size: 11, alpha: 0.16, delay: 2.6, tilt: 4 },
    { text: 'Fitrah', offset: 30, size: 12, alpha: 0.2, delay: 0.9, tilt: -4 },
    { text: 'Devil', offset: 45, size: 12, alpha: 0.22, delay: 1.9, tilt: 5 },
    { text: 'Desire', offset: 60, size: 11, alpha: 0.18, delay: 2.8, tilt: -5 },
    { text: 'Reason', offset: 74, size: 13, alpha: 0.24, delay: 1.3, tilt: 3 },
    { text: 'Memory', offset: 87, size: 11, alpha: 0.16, delay: 3.6, tilt: -3 },
  ],
};

export const SUPPLEMENTAL_CLUSTERS: AtlasCluster[] = [
  {
    id: 'cl_knowledge',
    label: 'Knowledge',
    label_ar: 'المعرفة',
    order: 10,
    color: '#7db9ff',
    world_x: -170,
    world_y: -470,
    radius: 250,
  },
  {
    id: 'cl_civilization',
    label: 'Civilization',
    label_ar: 'الحضارة',
    order: 11,
    color: '#a7d98f',
    world_x: 525,
    world_y: -395,
    radius: 255,
  },
  {
    id: 'cl_morality',
    label: 'Morality',
    label_ar: 'الأخلاق',
    order: 12,
    color: '#ff9f7a',
    world_x: 645,
    world_y: 288,
    radius: 235,
  },
  {
    id: 'cl_human_nature',
    label: 'Human Nature',
    label_ar: 'الطبيعة الإنسانية',
    order: 13,
    color: '#8b9cff',
    world_x: -675,
    world_y: 238,
    radius: 240,
  },
  {
    id: 'cl_education',
    label: 'Education',
    label_ar: 'التعليم',
    order: 14,
    color: '#70d8c8',
    world_x: -20,
    world_y: 575,
    radius: 265,
  },
  {
    id: 'cl_economics',
    label: 'Economics',
    label_ar: 'الاقتصاد',
    order: 15,
    color: '#d8c36b',
    world_x: -900,
    world_y: -150,
    radius: 235,
  },
  {
    id: 'cl_prophecy',
    label: 'Prophecy',
    label_ar: 'النبوة',
    order: 16,
    color: '#8fd9a1',
    world_x: 885,
    world_y: -40,
    radius: 228,
  },
];

export const SUPPLEMENTAL_NODES: AtlasNode[] = [
  {
    id: 'n_concept_epistemology',
    kind: 'concept',
    cluster_id: 'cl_knowledge',
    label: 'Epistemology',
    label_ar: 'نظرية المعرفة',
    size: 31,
    zoom_level: 2,
    importance: 8,
    fx_hint: -218,
    fy_hint: -520,
    time_start: 800,
    time_end: 2100,
  },
  {
    id: 'n_claim_method_authority',
    kind: 'claim',
    cluster_id: 'cl_knowledge',
    label: 'Modern knowledge privileges method as authority',
    label_ar: 'المعرفة الحديثة تمنح المنهج موقع السلطة',
    size: 20,
    zoom_level: 3,
    importance: 7,
    fx_hint: -110,
    fy_hint: -474,
    time_start: 1650,
    time_end: 2100,
  },
  {
    id: 'n_evidence_laboratory',
    kind: 'evidence',
    cluster_id: 'cl_knowledge',
    label: 'Laboratory model',
    label_ar: 'نموذج المختبر',
    size: 14,
    zoom_level: 4,
    importance: 5,
    fx_hint: -58,
    fy_hint: -420,
    time_start: 1750,
    time_end: 2100,
    evidence_type: 'institution',
  },
  {
    id: 'n_evidence_peer_review',
    kind: 'evidence',
    cluster_id: 'cl_knowledge',
    label: 'Peer review gate',
    label_ar: 'بوابة التحكيم العلمي',
    size: 14,
    zoom_level: 4,
    importance: 4,
    fx_hint: -148,
    fy_hint: -390,
    time_start: 1900,
    time_end: 2100,
    evidence_type: 'institution',
  },
  {
    id: 'n_concept_transmission',
    kind: 'concept',
    cluster_id: 'cl_knowledge',
    label: 'Transmission',
    label_ar: 'النقل',
    size: 29,
    zoom_level: 2,
    importance: 7,
    fx_hint: -302,
    fy_hint: -424,
    time_start: 700,
    time_end: 2100,
  },
  {
    id: 'n_claim_chains_preserve_knowledge',
    kind: 'claim',
    cluster_id: 'cl_knowledge',
    label: 'Transmission chains preserve verified memory',
    label_ar: 'سلاسل النقل تحفظ الذاكرة الموثقة',
    size: 20,
    zoom_level: 3,
    importance: 6,
    fx_hint: -382,
    fy_hint: -360,
    time_start: 700,
    time_end: 2100,
  },
  {
    id: 'n_evidence_isnad',
    kind: 'evidence',
    cluster_id: 'cl_knowledge',
    label: 'Isnad discipline',
    label_ar: 'علم الإسناد',
    size: 14,
    zoom_level: 4,
    importance: 5,
    fx_hint: -458,
    fy_hint: -308,
    time_start: 700,
    time_end: 2100,
    evidence_type: 'tradition',
  },
  {
    id: 'n_evidence_commentary',
    kind: 'evidence',
    cluster_id: 'cl_knowledge',
    label: 'Commentary tradition',
    label_ar: 'تقليد الشروح',
    size: 14,
    zoom_level: 4,
    importance: 4,
    fx_hint: -350,
    fy_hint: -278,
    time_start: 900,
    time_end: 2100,
    evidence_type: 'text',
  },
  {
    id: 'n_concept_urban_form',
    kind: 'concept',
    cluster_id: 'cl_civilization',
    label: 'Urban Form',
    label_ar: 'العمران',
    size: 31,
    zoom_level: 2,
    importance: 8,
    fx_hint: 462,
    fy_hint: -442,
    time_start: -500,
    time_end: 2100,
  },
  {
    id: 'n_claim_city_embeds_worldview',
    kind: 'claim',
    cluster_id: 'cl_civilization',
    label: 'Cities embed metaphysical order into daily life',
    label_ar: 'المدن تجسّد النظام الميتافيزيقي في الحياة اليومية',
    size: 20,
    zoom_level: 3,
    importance: 7,
    fx_hint: 382,
    fy_hint: -372,
    time_start: -200,
    time_end: 2100,
  },
  {
    id: 'n_evidence_market_mosque',
    kind: 'evidence',
    cluster_id: 'cl_civilization',
    label: 'Market and mosque adjacency',
    label_ar: 'تجاور السوق والمسجد',
    size: 14,
    zoom_level: 4,
    importance: 5,
    fx_hint: 336,
    fy_hint: -304,
    time_start: 700,
    time_end: 1800,
    evidence_type: 'historical_case',
  },
  {
    id: 'n_evidence_city_charter',
    kind: 'evidence',
    cluster_id: 'cl_civilization',
    label: 'Civic charter',
    label_ar: 'ميثاق مدني',
    size: 14,
    zoom_level: 4,
    importance: 4,
    fx_hint: 432,
    fy_hint: -282,
    time_start: 1100,
    time_end: 1900,
    evidence_type: 'archive',
  },
  {
    id: 'n_concept_civilizational_memory',
    kind: 'concept',
    cluster_id: 'cl_civilization',
    label: 'Civilizational Memory',
    label_ar: 'الذاكرة الحضارية',
    size: 29,
    zoom_level: 2,
    importance: 7,
    fx_hint: 592,
    fy_hint: -464,
    time_start: -500,
    time_end: 2100,
  },
  {
    id: 'n_claim_memory_stabilizes_forms',
    kind: 'claim',
    cluster_id: 'cl_civilization',
    label: 'Memory stabilizes forms across dynastic change',
    label_ar: 'الذاكرة تثبّت الأشكال عبر تغيّر الدول',
    size: 20,
    zoom_level: 3,
    importance: 6,
    fx_hint: 664,
    fy_hint: -392,
    time_start: 0,
    time_end: 2100,
  },
  {
    id: 'n_evidence_archive_city',
    kind: 'evidence',
    cluster_id: 'cl_civilization',
    label: 'Archive of urban continuities',
    label_ar: 'أرشيف الاستمراريات العمرانية',
    size: 14,
    zoom_level: 4,
    importance: 4,
    fx_hint: 720,
    fy_hint: -328,
    time_start: 700,
    time_end: 2100,
    evidence_type: 'archive',
  },
  {
    id: 'n_evidence_craft_guild',
    kind: 'evidence',
    cluster_id: 'cl_civilization',
    label: 'Craft guild inheritance',
    label_ar: 'توريث الحِرَف والنقابات',
    size: 14,
    zoom_level: 4,
    importance: 4,
    fx_hint: 610,
    fy_hint: -302,
    time_start: 900,
    time_end: 1900,
    evidence_type: 'historical_case',
  },
  {
    id: 'n_concept_virtue',
    kind: 'concept',
    cluster_id: 'cl_morality',
    label: 'Virtue',
    label_ar: 'الفضيلة',
    size: 31,
    zoom_level: 2,
    importance: 8,
    fx_hint: 566,
    fy_hint: 238,
    time_start: -400,
    time_end: 2100,
  },
  {
    id: 'n_claim_virtue_shapes_perception',
    kind: 'claim',
    cluster_id: 'cl_morality',
    label: 'Virtue shapes what the self can perceive as good',
    label_ar: 'الفضيلة تشكّل ما تستطيع النفس إدراكه كخير',
    size: 20,
    zoom_level: 3,
    importance: 7,
    fx_hint: 504,
    fy_hint: 322,
    time_start: -300,
    time_end: 2100,
  },
  {
    id: 'n_evidence_akhlaq',
    kind: 'evidence',
    cluster_id: 'cl_morality',
    label: 'Akhlaq manual',
    label_ar: 'متن في الأخلاق',
    size: 14,
    zoom_level: 4,
    importance: 5,
    fx_hint: 440,
    fy_hint: 380,
    time_start: 1000,
    time_end: 1800,
    evidence_type: 'text',
  },
  {
    id: 'n_evidence_ascetic_practice',
    kind: 'evidence',
    cluster_id: 'cl_morality',
    label: 'Ascetic discipline',
    label_ar: 'رياضة الزهد',
    size: 14,
    zoom_level: 4,
    importance: 4,
    fx_hint: 532,
    fy_hint: 408,
    time_start: 700,
    time_end: 2100,
    evidence_type: 'practice',
  },
  {
    id: 'n_concept_relativism',
    kind: 'concept',
    cluster_id: 'cl_morality',
    label: 'Relativism',
    label_ar: 'النسبية',
    size: 29,
    zoom_level: 2,
    importance: 7,
    fx_hint: 694,
    fy_hint: 220,
    time_start: 1850,
    time_end: 2100,
  },
  {
    id: 'n_claim_morality_detached',
    kind: 'claim',
    cluster_id: 'cl_morality',
    label: 'Morality detaches from transcendence and common telos',
    label_ar: 'الأخلاق تنفصل عن التعالي والغاية المشتركة',
    size: 20,
    zoom_level: 3,
    importance: 6,
    fx_hint: 760,
    fy_hint: 300,
    time_start: 1900,
    time_end: 2100,
  },
  {
    id: 'n_evidence_values_language',
    kind: 'evidence',
    cluster_id: 'cl_morality',
    label: 'Values discourse',
    label_ar: 'خطاب القيم',
    size: 14,
    zoom_level: 4,
    importance: 4,
    fx_hint: 818,
    fy_hint: 362,
    time_start: 1950,
    time_end: 2100,
    evidence_type: 'text',
  },
  {
    "id": "n_evidence_ethics_committee",
    "kind": "evidence",
    "cluster_id": "cl_morality",
    "label": "Ethics committee procedure",
    "label_ar": "إجراء لجنة أخلاقيات",
    "size": 14,
    "zoom_level": 4,
    "importance": 4,
    "fx_hint": 730,
    "fy_hint": 392,
    "time_start": 1970,
    "time_end": 2100,
    "evidence_type": "institution"
  },
  {
    "id": "n_concept_fitrah",
    "kind": "concept",
    "cluster_id": "cl_human_nature",
    "label": "Fitrah",
    "label_ar": "الفطرة",
    "size": 31,
    "zoom_level": 2,
    "importance": 8,
    "fx_hint": -618,
    "fy_hint": 178,
    "time_start": 600,
    "time_end": 2100
  },
  {
    "id": "n_claim_human_directed",
    "kind": "claim",
    "cluster_id": "cl_human_nature",
    "label": "Human nature is oriented before it is self-invented",
    "label_ar": "الطبيعة الإنسانية موجهة قبل أن تخترع نفسها",
    "size": 20,
    "zoom_level": 3,
    "importance": 7,
    "fx_hint": -542,
    "fy_hint": 266,
    "time_start": 600,
    "time_end": 2100
  },
  {
    "id": "n_evidence_creation_verse",
    "kind": "evidence",
    "cluster_id": "cl_human_nature",
    "label": "Creation verse",
    "label_ar": "آية الخلق",
    "size": 14,
    "zoom_level": 4,
    "importance": 5,
    "fx_hint": -480,
    "fy_hint": 336,
    "time_start": 600,
    "time_end": 2100,
    "evidence_type": "verse"
  },
  {
    "id": "n_evidence_classical_anthropology",
    "kind": "evidence",
    "cluster_id": "cl_human_nature",
    "label": "Classical anthropology text",
    "label_ar": "نص في الأنثروبولوجيا الكلاسيكية",
    "size": 14,
    "zoom_level": 4,
    "importance": 4,
    "fx_hint": -568,
    "fy_hint": 358,
    "time_start": 1000,
    "time_end": 1800,
    "evidence_type": "text"
  },
  {
    "id": "n_concept_desire",
    "kind": "concept",
    "cluster_id": "cl_human_nature",
    "label": "Desire",
    "label_ar": "الرغبة",
    "size": 29,
    "zoom_level": 2,
    "importance": 7,
    "fx_hint": -742,
    "fy_hint": 182,
    "time_start": -300,
    "time_end": 2100
  },
  {
    "id": "n_claim_desire_educated",
    "kind": "claim",
    "cluster_id": "cl_human_nature",
    "label": "Desire must be educated rather than absolutized",
    "label_ar": "الرغبة تحتاج إلى تهذيب لا إلى تأليه",
    "size": 20,
    "zoom_level": 3,
    "importance": 6,
    "fx_hint": -818,
    "fy_hint": 258,
    "time_start": 600,
    "time_end": 2100
  },
  {
    "id": "n_evidence_fasting",
    "kind": "evidence",
    "cluster_id": "cl_human_nature",
    "label": "Fasting discipline",
    "label_ar": "رياضة الصوم",
    "size": 14,
    "zoom_level": 4,
    "importance": 4,
    "fx_hint": -870,
    "fy_hint": 320,
    "time_start": 600,
    "time_end": 2100,
    "evidence_type": "practice"
  },
  {
    "id": "n_evidence_adab",
    "kind": "evidence",
    "cluster_id": "cl_human_nature",
    "label": "Adab pedagogy",
    "label_ar": "تربية الأدب",
    "size": 14,
    "zoom_level": 4,
    "importance": 4,
    "fx_hint": -776,
    "fy_hint": 346,
    "time_start": 900,
    "time_end": 2100,
    "evidence_type": "practice"
  },
  {
    "id": "n_concept_pedagogy",
    "kind": "concept",
    "cluster_id": "cl_education",
    "label": "Pedagogy",
    "label_ar": "التربية",
    "size": 31,
    "zoom_level": 2,
    "importance": 8,
    "fx_hint": -88,
    "fy_hint": 514,
    "time_start": 700,
    "time_end": 2100
  },
  {
    "id": "n_claim_pedagogy_forms_perception",
    "kind": "claim",
    "cluster_id": "cl_education",
    "label": "Pedagogy forms perception before argument",
    "label_ar": "التربية تشكّل الإدراك قبل الجدل",
    "size": 20,
    "zoom_level": 3,
    "importance": 7,
    "fx_hint": -186,
    "fy_hint": 592,
    "time_start": 700,
    "time_end": 2100
  },
  {
    "id": "n_evidence_madrasa",
    "kind": "evidence",
    "cluster_id": "cl_education",
    "label": "Madrasa routine",
    "label_ar": "إيقاع المدرسة",
    "size": 14,
    "zoom_level": 4,
    "importance": 5,
    "fx_hint": -254,
    "fy_hint": 658,
    "time_start": 1000,
    "time_end": 1900,
    "evidence_type": "institution"
  },
  {
    "id": "n_evidence_recitation",
    "kind": "evidence",
    "cluster_id": "cl_education",
    "label": "Recitation circle",
    "label_ar": "حلقة التلاوة",
    "size": 14,
    "zoom_level": 4,
    "importance": 4,
    "fx_hint": -154,
    "fy_hint": 688,
    "time_start": 700,
    "time_end": 2100,
    "evidence_type": "practice"
  },
  {
    "id": "n_concept_memory",
    "kind": "concept",
    "cluster_id": "cl_education",
    "label": "Memory",
    "label_ar": "الذاكرة",
    "size": 29,
    "zoom_level": 2,
    "importance": 7,
    "fx_hint": 78,
    "fy_hint": 520,
    "time_start": 600,
    "time_end": 2100
  },
  {
    "id": "n_claim_memory_is_civilizational",
    "kind": "claim",
    "cluster_id": "cl_education",
    "label": "Memory is infrastructure for civilizational continuity",
    "label_ar": "الذاكرة بنية تحتية لاستمرار الحضارة",
    "size": 20,
    "zoom_level": 3,
    "importance": 6,
    "fx_hint": 162,
    "fy_hint": 600,
    "time_start": 600,
    "time_end": 2100
  },
  {
    "id": "n_evidence_hifz",
    "kind": "evidence",
    "cluster_id": "cl_education",
    "label": "Hifz discipline",
    "label_ar": "رياضة الحفظ",
    "size": 14,
    "zoom_level": 4,
    "importance": 4,
    "fx_hint": 224,
    "fy_hint": 662,
    "time_start": 700,
    "time_end": 2100,
    "evidence_type": "practice"
  },
  {
    "id": "n_evidence_family_story",
    "kind": "evidence",
    "cluster_id": "cl_education",
    "label": "Family story transmission",
    "label_ar": "نقل الحكاية العائلية",
    "size": 14,
    "zoom_level": 4,
    "importance": 4,
    "fx_hint": 118,
    "fy_hint": 692,
    "time_start": 600,
    "time_end": 2100,
    "evidence_type": "practice"
  },
  {
    id: 'n_concept_justice',
    kind: 'concept',
    cluster_id: 'cl_morality',
    label: 'Justice',
    label_ar: 'العدل',
    size: 31,
    zoom_level: 2,
    importance: 9,
    fx_hint: 610,
    fy_hint: 118,
    time_start: 600,
    time_end: 2100,
  },
  {
    id: 'n_claim_justice_measures_power',
    kind: 'claim',
    cluster_id: 'cl_morality',
    label: 'Justice measures power and desire',
    label_ar: 'العدل يزن السلطة والرغبة',
    size: 20,
    zoom_level: 3,
    importance: 7,
    fx_hint: 534,
    fy_hint: 178,
    time_start: 600,
    time_end: 2100,
  },
  {
    id: 'n_evidence_qist',
    kind: 'evidence',
    cluster_id: 'cl_morality',
    label: 'Qist verse',
    label_ar: 'آية القسط',
    size: 14,
    zoom_level: 4,
    importance: 5,
    fx_hint: 478,
    fy_hint: 236,
    time_start: 600,
    time_end: 2100,
    evidence_type: 'verse',
  },
  {
    id: 'n_evidence_sermon_farewell',
    kind: 'evidence',
    cluster_id: 'cl_morality',
    label: 'Farewell sermon',
    label_ar: 'خطبة الوداع',
    size: 14,
    zoom_level: 4,
    importance: 4,
    fx_hint: 562,
    fy_hint: 256,
    time_start: 632,
    time_end: 2100,
    evidence_type: 'prophet',
  },
  {
    id: 'n_concept_truth',
    kind: 'concept',
    cluster_id: 'cl_knowledge',
    label: 'Truth',
    label_ar: 'الحق',
    size: 31,
    zoom_level: 2,
    importance: 9,
    fx_hint: -92,
    fy_hint: -548,
    time_start: 600,
    time_end: 2100,
  },
  {
    id: 'n_claim_truth_is_received',
    kind: 'claim',
    cluster_id: 'cl_knowledge',
    label: 'Truth is received before it is systematized',
    label_ar: 'الحق يُتلقّى قبل أن يُنظَّم',
    size: 20,
    zoom_level: 3,
    importance: 7,
    fx_hint: -18,
    fy_hint: -490,
    time_start: 600,
    time_end: 2100,
  },
  {
    id: 'n_evidence_haqq',
    kind: 'evidence',
    cluster_id: 'cl_knowledge',
    label: 'Haqq motif',
    label_ar: 'مفهوم الحق',
    size: 14,
    zoom_level: 4,
    importance: 5,
    fx_hint: 44,
    fy_hint: -430,
    time_start: 600,
    time_end: 2100,
    evidence_type: 'verse',
  },
  {
    id: 'n_evidence_witness_testimony',
    kind: 'evidence',
    cluster_id: 'cl_knowledge',
    label: 'Witness testimony',
    label_ar: 'شهادة الشاهد',
    size: 14,
    zoom_level: 4,
    importance: 4,
    fx_hint: -54,
    fy_hint: -410,
    time_start: 700,
    time_end: 2100,
    evidence_type: 'practice',
  },
  {
    id: 'n_concept_hereafter',
    kind: 'concept',
    cluster_id: 'cl_revelation',
    label: 'Hereafter',
    label_ar: 'الآخرة',
    size: 32,
    zoom_level: 2,
    importance: 9,
    fx_hint: -184,
    fy_hint: -356,
    time_start: 600,
    time_end: 2100,
  },
  {
    id: 'n_claim_hereafter_scales_life',
    kind: 'claim',
    cluster_id: 'cl_revelation',
    label: 'The Hereafter resizes moral scale',
    label_ar: 'الآخرة تعيد قياس المجال الأخلاقي',
    size: 20,
    zoom_level: 3,
    importance: 7,
    fx_hint: -270,
    fy_hint: -300,
    time_start: 600,
    time_end: 2100,
  },
  {
    id: 'n_evidence_resurrection_verse',
    kind: 'evidence',
    cluster_id: 'cl_revelation',
    label: 'Resurrection verse',
    label_ar: 'آية البعث',
    size: 14,
    zoom_level: 4,
    importance: 5,
    fx_hint: -338,
    fy_hint: -242,
    time_start: 600,
    time_end: 2100,
    evidence_type: 'verse',
  },
  {
    id: 'n_evidence_mizan',
    kind: 'evidence',
    cluster_id: 'cl_revelation',
    label: 'Mizan image',
    label_ar: 'صورة الميزان',
    size: 14,
    zoom_level: 4,
    importance: 4,
    fx_hint: -244,
    fy_hint: -214,
    time_start: 600,
    time_end: 2100,
    evidence_type: 'text',
  },
  {
    id: 'n_concept_devil',
    kind: 'concept',
    cluster_id: 'cl_human_nature',
    label: 'Devil',
    label_ar: 'الشيطان',
    size: 30,
    zoom_level: 2,
    importance: 8,
    fx_hint: -862,
    fy_hint: 104,
    time_start: 600,
    time_end: 2100,
  },
  {
    id: 'n_claim_devil_whispers',
    kind: 'claim',
    cluster_id: 'cl_human_nature',
    label: 'Evil works through whisper and inversion',
    label_ar: 'الشر يعمل بالوسوسة وقلب المعاني',
    size: 20,
    zoom_level: 3,
    importance: 6,
    fx_hint: -934,
    fy_hint: 170,
    time_start: 600,
    time_end: 2100,
  },
  {
    id: 'n_evidence_iblis',
    kind: 'evidence',
    cluster_id: 'cl_human_nature',
    label: 'Iblis account',
    label_ar: 'قصة إبليس',
    size: 14,
    zoom_level: 4,
    importance: 5,
    fx_hint: -988,
    fy_hint: 238,
    time_start: 600,
    time_end: 2100,
    evidence_type: 'verse',
  },
  {
    id: 'n_evidence_temptation',
    kind: 'evidence',
    cluster_id: 'cl_human_nature',
    label: 'Temptation ethics',
    label_ar: 'أخلاق مقاومة الإغراء',
    size: 14,
    zoom_level: 4,
    importance: 4,
    fx_hint: -900,
    fy_hint: 254,
    time_start: 700,
    time_end: 2100,
    evidence_type: 'practice',
  },
  {
    id: 'n_concept_capitalism',
    kind: 'concept',
    cluster_id: 'cl_economics',
    label: 'Capitalism',
    label_ar: 'الرأسمالية',
    size: 32,
    zoom_level: 2,
    importance: 9,
    fx_hint: -840,
    fy_hint: -200,
    time_start: 1700,
    time_end: 2100,
  },
  {
    id: 'n_claim_capitalism_reorders_value',
    kind: 'claim',
    cluster_id: 'cl_economics',
    label: 'Capitalism recodes value, labor, and time',
    label_ar: 'الرأسمالية تعيد ترميز القيمة والعمل والزمن',
    size: 20,
    zoom_level: 3,
    importance: 7,
    fx_hint: -748,
    fy_hint: -134,
    time_start: 1750,
    time_end: 2100,
  },
  {
    id: 'n_evidence_adam_smith',
    kind: 'evidence',
    cluster_id: 'cl_economics',
    label: 'Adam Smith',
    label_ar: 'آدم سميث',
    size: 14,
    zoom_level: 4,
    importance: 5,
    fx_hint: -676,
    fy_hint: -74,
    time_start: 1776,
    time_end: 2100,
    evidence_type: 'author',
  },
  {
    id: 'n_evidence_stock_exchange',
    kind: 'evidence',
    cluster_id: 'cl_economics',
    label: 'Stock exchange',
    label_ar: 'البورصة',
    size: 14,
    zoom_level: 4,
    importance: 4,
    fx_hint: -776,
    fy_hint: -38,
    time_start: 1800,
    time_end: 2100,
    evidence_type: 'institution',
  },
  {
    id: 'n_concept_thinkers',
    kind: 'concept',
    cluster_id: 'cl_knowledge',
    label: 'Thinkers',
    label_ar: 'المفكرون',
    size: 30,
    zoom_level: 2,
    importance: 8,
    fx_hint: -418,
    fy_hint: -516,
    time_start: -400,
    time_end: 2100,
  },
  {
    id: 'n_claim_thinkers_frame_worlds',
    kind: 'claim',
    cluster_id: 'cl_knowledge',
    label: 'Thinkers frame worlds through systems',
    label_ar: 'المفكرون يؤطرون العوالم عبر النظم',
    size: 20,
    zoom_level: 3,
    importance: 6,
    fx_hint: -500,
    fy_hint: -454,
    time_start: -300,
    time_end: 2100,
  },
  {
    id: 'n_evidence_aristotle',
    kind: 'evidence',
    cluster_id: 'cl_knowledge',
    label: 'Aristotle',
    label_ar: 'أرسطو',
    size: 14,
    zoom_level: 4,
    importance: 4,
    fx_hint: -566,
    fy_hint: -394,
    time_start: -340,
    time_end: 2100,
    evidence_type: 'thinker',
  },
  {
    id: 'n_evidence_ibn_khaldun',
    kind: 'evidence',
    cluster_id: 'cl_knowledge',
    label: 'Ibn Khaldun',
    label_ar: 'ابن خلدون',
    size: 14,
    zoom_level: 4,
    importance: 4,
    fx_hint: -474,
    fy_hint: -366,
    time_start: 1377,
    time_end: 2100,
    evidence_type: 'thinker',
  },
  {
    id: 'n_concept_authors',
    kind: 'concept',
    cluster_id: 'cl_civilization',
    label: 'Authors',
    label_ar: 'المؤلفون',
    size: 29,
    zoom_level: 2,
    importance: 7,
    fx_hint: 744,
    fy_hint: -472,
    time_start: -400,
    time_end: 2100,
  },
  {
    id: 'n_claim_authors_preserve_worlds',
    kind: 'claim',
    cluster_id: 'cl_civilization',
    label: 'Authors preserve worlds in durable language',
    label_ar: 'المؤلفون يحفظون العوالم في لغة دائمة',
    size: 20,
    zoom_level: 3,
    importance: 6,
    fx_hint: 816,
    fy_hint: -406,
    time_start: -200,
    time_end: 2100,
  },
  {
    id: 'n_evidence_ghazali',
    kind: 'evidence',
    cluster_id: 'cl_civilization',
    label: 'Al-Ghazali',
    label_ar: 'الغزالي',
    size: 14,
    zoom_level: 4,
    importance: 4,
    fx_hint: 874,
    fy_hint: -350,
    time_start: 1100,
    time_end: 2100,
    evidence_type: 'author',
  },
  {
    id: 'n_evidence_augustine',
    kind: 'evidence',
    cluster_id: 'cl_civilization',
    label: 'Augustine',
    label_ar: 'أوغسطين',
    size: 14,
    zoom_level: 4,
    importance: 4,
    fx_hint: 784,
    fy_hint: -332,
    time_start: 400,
    time_end: 2100,
    evidence_type: 'author',
  },
  {
    id: 'n_concept_prophets',
    kind: 'concept',
    cluster_id: 'cl_prophecy',
    label: 'Prophets',
    label_ar: 'الأنبياء',
    size: 32,
    zoom_level: 2,
    importance: 9,
    fx_hint: 826,
    fy_hint: -110,
    time_start: -1800,
    time_end: 2100,
  },
  {
    id: 'n_claim_prophets_judge_idols',
    kind: 'claim',
    cluster_id: 'cl_prophecy',
    label: 'Prophets judge idols, power, and forgetfulness',
    label_ar: 'الأنبياء يحاكمون الأصنام والسلطة والنسيان',
    size: 20,
    zoom_level: 3,
    importance: 7,
    fx_hint: 912,
    fy_hint: -42,
    time_start: -1400,
    time_end: 2100,
  },
  {
    id: 'n_evidence_moses',
    kind: 'evidence',
    cluster_id: 'cl_prophecy',
    label: 'Moses',
    label_ar: 'موسى',
    size: 14,
    zoom_level: 4,
    importance: 5,
    fx_hint: 972,
    fy_hint: 18,
    time_start: -1300,
    time_end: 2100,
    evidence_type: 'prophet',
  },
  {
    id: 'n_evidence_jesus',
    kind: 'evidence',
    cluster_id: 'cl_prophecy',
    label: 'Jesus',
    label_ar: 'عيسى',
    size: 14,
    zoom_level: 4,
    importance: 4,
    fx_hint: 882,
    fy_hint: 40,
    time_start: 30,
    time_end: 2100,
    evidence_type: 'prophet',
  },
  {
    id: 'n_evidence_muhammad',
    kind: 'evidence',
    cluster_id: 'cl_prophecy',
    label: 'Muhammad',
    label_ar: 'محمد',
    size: 14,
    zoom_level: 4,
    importance: 5,
    fx_hint: 932,
    fy_hint: 92,
    time_start: 610,
    time_end: 2100,
    evidence_type: 'prophet',
  },
  {
    id: 'n_concept_interest',
    kind: 'concept',
    cluster_id: 'cl_economics',
    label: 'Interest',
    label_ar: 'الربا',
    size: 31,
    zoom_level: 2,
    importance: 8,
    fx_hint: -1016,
    fy_hint: -220,
    time_start: 600,
    time_end: 2100,
  },
  {
    id: 'n_claim_interest_prices_dependence',
    kind: 'claim',
    cluster_id: 'cl_economics',
    label: 'Interest prices time, debt, and dependence',
    label_ar: 'الربا يسعّر الزمن والدين والتبعية',
    size: 20,
    zoom_level: 3,
    importance: 7,
    fx_hint: -1106,
    fy_hint: -156,
    time_start: 600,
    time_end: 2100,
  },
  {
    id: 'n_evidence_riba_verse',
    kind: 'evidence',
    cluster_id: 'cl_economics',
    label: 'Riba verse',
    label_ar: 'آية الربا',
    size: 14,
    zoom_level: 4,
    importance: 5,
    fx_hint: -1178,
    fy_hint: -90,
    time_start: 600,
    time_end: 2100,
    evidence_type: 'verse',
  },
  {
    id: 'n_evidence_debt_spiral',
    kind: 'evidence',
    cluster_id: 'cl_economics',
    label: 'Debt spiral',
    label_ar: 'دوامة الدين',
    size: 14,
    zoom_level: 4,
    importance: 4,
    fx_hint: -1072,
    fy_hint: -38,
    time_start: 1800,
    time_end: 2100,
    evidence_type: 'historical_case',
  },
  {
    id: 'n_concept_charity',
    kind: 'concept',
    cluster_id: 'cl_economics',
    label: 'Charity',
    label_ar: 'الصدقة',
    size: 30,
    zoom_level: 2,
    importance: 8,
    fx_hint: -1020,
    fy_hint: -84,
    time_start: 600,
    time_end: 2100,
  },
  {
    id: 'n_claim_charity_restores_circulation',
    kind: 'claim',
    cluster_id: 'cl_economics',
    label: 'Charity restores circulation through mercy',
    label_ar: 'الصدقة تعيد التداول عبر الرحمة',
    size: 20,
    zoom_level: 3,
    importance: 6,
    fx_hint: -1112,
    fy_hint: -20,
    time_start: 600,
    time_end: 2100,
  },
  {
    id: 'n_evidence_sadaqah',
    kind: 'evidence',
    cluster_id: 'cl_economics',
    label: 'Sadaqah practice',
    label_ar: 'ممارسة الصدقة',
    size: 14,
    zoom_level: 4,
    importance: 4,
    fx_hint: -1184,
    fy_hint: 42,
    time_start: 600,
    time_end: 2100,
    evidence_type: 'practice',
  },
  {
    id: 'n_evidence_waqf_kitchen',
    kind: 'evidence',
    cluster_id: 'cl_economics',
    label: 'Waqf kitchen',
    label_ar: 'مطبخ الوقف',
    size: 14,
    zoom_level: 4,
    importance: 4,
    fx_hint: -1084,
    fy_hint: 88,
    time_start: 1100,
    time_end: 2100,
    evidence_type: 'institution',
  },
  {
    id: 'n_concept_zakat',
    kind: 'concept',
    cluster_id: 'cl_economics',
    label: 'Zakat',
    label_ar: 'الزكاة',
    size: 32,
    zoom_level: 2,
    importance: 9,
    fx_hint: -932,
    fy_hint: -18,
    time_start: 600,
    time_end: 2100,
  },
  {
    id: 'n_claim_zakat_directs_surplus',
    kind: 'claim',
    cluster_id: 'cl_economics',
    label: 'Zakat directs surplus toward the needy',
    label_ar: 'الزكاة توجه الفائض نحو المحتاجين',
    size: 20,
    zoom_level: 3,
    importance: 7,
    fx_hint: -840,
    fy_hint: 44,
    time_start: 600,
    time_end: 2100,
  },
  {
    id: 'n_evidence_zakat_recipients',
    kind: 'evidence',
    cluster_id: 'cl_economics',
    label: 'Eight recipients',
    label_ar: 'مصارف الزكاة الثمانية',
    size: 14,
    zoom_level: 4,
    importance: 5,
    fx_hint: -742,
    fy_hint: 116,
    time_start: 600,
    time_end: 2100,
    evidence_type: 'verse',
  },
  {
    id: 'n_evidence_alms_distributor',
    kind: 'evidence',
    cluster_id: 'cl_economics',
    label: 'Alms distributor',
    label_ar: 'عامل الزكاة',
    size: 14,
    zoom_level: 4,
    importance: 4,
    fx_hint: -854,
    fy_hint: 154,
    time_start: 700,
    time_end: 2100,
    evidence_type: 'institution',
  },
  {
    id: 'n_concept_needy',
    kind: 'concept',
    cluster_id: 'cl_economics',
    label: 'Needy',
    label_ar: 'المحتاجون',
    size: 29,
    zoom_level: 2,
    importance: 7,
    fx_hint: -936,
    fy_hint: -268,
    time_start: 600,
    time_end: 2100,
  },
  {
    id: 'n_claim_needy_have_claim',
    kind: 'claim',
    cluster_id: 'cl_economics',
    label: 'The needy hold a claim on surplus wealth',
    label_ar: 'للمحتاجين حق في فائض المال',
    size: 20,
    zoom_level: 3,
    importance: 6,
    fx_hint: -1032,
    fy_hint: -324,
    time_start: 600,
    time_end: 2100,
  },
  {
    id: 'n_evidence_orphan_care',
    kind: 'evidence',
    cluster_id: 'cl_economics',
    label: 'Orphan care',
    label_ar: 'رعاية اليتيم',
    size: 14,
    zoom_level: 4,
    importance: 4,
    fx_hint: -1114,
    fy_hint: -378,
    time_start: 600,
    time_end: 2100,
    evidence_type: 'verse',
  },
  {
    id: 'n_evidence_traveler_aid',
    kind: 'evidence',
    cluster_id: 'cl_economics',
    label: 'Traveler aid',
    label_ar: 'إغاثة ابن السبيل',
    size: 14,
    zoom_level: 4,
    importance: 4,
    fx_hint: -998,
    fy_hint: -404,
    time_start: 600,
    time_end: 2100,
    evidence_type: 'practice',
  },
  {
    id: 'n_concept_spirituality',
    kind: 'concept',
    cluster_id: 'cl_revelation',
    label: 'Spirituality',
    label_ar: 'الروحانية',
    size: 31,
    zoom_level: 2,
    importance: 8,
    fx_hint: 96,
    fy_hint: -390,
    time_start: 600,
    time_end: 2100,
  },
  {
    id: 'n_claim_salah_orders_soul',
    kind: 'claim',
    cluster_id: 'cl_revelation',
    label: 'Salah orders the soul through sacred time',
    label_ar: 'الصلاة تنظم النفس عبر الزمن المقدس',
    size: 20,
    zoom_level: 3,
    importance: 7,
    fx_hint: 174,
    fy_hint: -326,
    time_start: 600,
    time_end: 2100,
  },
  {
    id: 'n_evidence_five_prayers',
    kind: 'evidence',
    cluster_id: 'cl_revelation',
    label: 'Five prayers',
    label_ar: 'الصلوات الخمس',
    size: 14,
    zoom_level: 4,
    importance: 5,
    fx_hint: 244,
    fy_hint: -260,
    time_start: 600,
    time_end: 2100,
    evidence_type: 'practice',
  },
  {
    id: 'n_evidence_dhikr',
    kind: 'evidence',
    cluster_id: 'cl_revelation',
    label: 'Dhikr discipline',
    label_ar: 'رياضة الذكر',
    size: 14,
    zoom_level: 4,
    importance: 4,
    fx_hint: 130,
    fy_hint: -230,
    time_start: 700,
    time_end: 2100,
    evidence_type: 'practice',
  },
  {
    id: 'n_concept_angels',
    kind: 'concept',
    cluster_id: 'cl_revelation',
    label: 'Angels',
    label_ar: 'الملائكة',
    size: 31,
    zoom_level: 2,
    importance: 8,
    fx_hint: 74,
    fy_hint: -166,
    time_start: 600,
    time_end: 2100,
  },
  {
    id: 'n_claim_angels_mediate_command',
    kind: 'claim',
    cluster_id: 'cl_revelation',
    label: 'Angels mediate command, descent, and witness',
    label_ar: 'الملائكة تتوسط الأمر والنزول والشهادة',
    size: 20,
    zoom_level: 3,
    importance: 7,
    fx_hint: 160,
    fy_hint: -102,
    time_start: 600,
    time_end: 2100,
  },
  {
    id: 'n_evidence_jibril',
    kind: 'evidence',
    cluster_id: 'cl_revelation',
    label: 'Jibril',
    label_ar: 'جبريل',
    size: 14,
    zoom_level: 4,
    importance: 5,
    fx_hint: 238,
    fy_hint: -34,
    time_start: 600,
    time_end: 2100,
    evidence_type: 'tradition',
  },
  {
    id: 'n_evidence_recording_angels',
    kind: 'evidence',
    cluster_id: 'cl_revelation',
    label: 'Recording angels',
    label_ar: 'الملائكة الكاتبة',
    size: 14,
    zoom_level: 4,
    importance: 4,
    fx_hint: 118,
    fy_hint: -10,
    time_start: 600,
    time_end: 2100,
    evidence_type: 'verse',
  },
  {
    id: 'n_concept_maturity',
    kind: 'concept',
    cluster_id: 'cl_human_nature',
    label: 'Maturity',
    label_ar: 'الرشد',
    size: 29,
    zoom_level: 2,
    importance: 7,
    fx_hint: -712,
    fy_hint: 330,
    time_start: 600,
    time_end: 2100,
  },
  {
    id: 'n_claim_maturity_needs_training',
    kind: 'claim',
    cluster_id: 'cl_human_nature',
    label: 'Maturity joins freedom to accountability',
    label_ar: 'الرشد يصل الحرية بالمسؤولية',
    size: 20,
    zoom_level: 3,
    importance: 6,
    fx_hint: -798,
    fy_hint: 394,
    time_start: 600,
    time_end: 2100,
  },
  {
    id: 'n_evidence_rushd',
    kind: 'evidence',
    cluster_id: 'cl_human_nature',
    label: 'Rushd test',
    label_ar: 'اختبار الرشد',
    size: 14,
    zoom_level: 4,
    importance: 4,
    fx_hint: -870,
    fy_hint: 452,
    time_start: 600,
    time_end: 2100,
    evidence_type: 'verse',
  },
  {
    id: 'n_evidence_adulthood_adab',
    kind: 'evidence',
    cluster_id: 'cl_human_nature',
    label: 'Adulthood adab',
    label_ar: 'أدب البلوغ',
    size: 14,
    zoom_level: 4,
    importance: 4,
    fx_hint: -748,
    fy_hint: 472,
    time_start: 700,
    time_end: 2100,
    evidence_type: 'practice',
  },
  {
    id: 'n_evidence_abraham',
    kind: 'evidence',
    cluster_id: 'cl_prophecy',
    label: 'Abraham',
    label_ar: 'إبراهيم',
    size: 14,
    zoom_level: 4,
    importance: 4,
    fx_hint: 786,
    fy_hint: -12,
    time_start: -1800,
    time_end: 2100,
    evidence_type: 'prophet',
  },
  {
    id: 'n_evidence_noah',
    kind: 'evidence',
    cluster_id: 'cl_prophecy',
    label: 'Noah',
    label_ar: 'نوح',
    size: 14,
    zoom_level: 4,
    importance: 4,
    fx_hint: 742,
    fy_hint: -72,
    time_start: -2200,
    time_end: 2100,
    evidence_type: 'prophet',
  },
  {
    id: 'n_evidence_joseph',
    kind: 'evidence',
    cluster_id: 'cl_prophecy',
    label: 'Joseph',
    label_ar: 'يوسف',
    size: 14,
    zoom_level: 4,
    importance: 4,
    fx_hint: 790,
    fy_hint: -170,
    time_start: -1700,
    time_end: 2100,
    evidence_type: 'prophet',
  },
  {
    id: 'n_evidence_david',
    kind: 'evidence',
    cluster_id: 'cl_prophecy',
    label: 'David',
    label_ar: 'داود',
    size: 14,
    zoom_level: 4,
    importance: 4,
    fx_hint: 864,
    fy_hint: -196,
    time_start: -1000,
    time_end: 2100,
    evidence_type: 'prophet',
  },
  {
    id: 'n_evidence_solomon',
    kind: 'evidence',
    cluster_id: 'cl_prophecy',
    label: 'Solomon',
    label_ar: 'سليمان',
    size: 14,
    zoom_level: 4,
    importance: 4,
    fx_hint: 954,
    fy_hint: -170,
    time_start: -960,
    time_end: 2100,
    evidence_type: 'prophet',
  },
  {
    id: 'n_evidence_aaron',
    kind: 'evidence',
    cluster_id: 'cl_prophecy',
    label: 'Aaron',
    label_ar: 'هارون',
    size: 14,
    zoom_level: 4,
    importance: 4,
    fx_hint: 1022,
    fy_hint: -110,
    time_start: -1300,
    time_end: 2100,
    evidence_type: 'prophet',
  },
  {
    id: 'n_evidence_isaac',
    kind: 'evidence',
    cluster_id: 'cl_prophecy',
    label: 'Isaac',
    label_ar: 'إسحاق',
    size: 14,
    zoom_level: 4,
    importance: 4,
    fx_hint: 1038,
    fy_hint: -8,
    time_start: -1700,
    time_end: 2100,
    evidence_type: 'prophet',
  },
  {
    id: 'n_evidence_jacob',
    kind: 'evidence',
    cluster_id: 'cl_prophecy',
    label: 'Jacob',
    label_ar: 'يعقوب',
    size: 14,
    zoom_level: 4,
    importance: 4,
    fx_hint: 1014,
    fy_hint: 72,
    time_start: -1650,
    time_end: 2100,
    evidence_type: 'prophet',
  },
  {
    id: 'n_evidence_ishmael',
    kind: 'evidence',
    cluster_id: 'cl_prophecy',
    label: 'Ishmael',
    label_ar: 'إسماعيل',
    size: 14,
    zoom_level: 4,
    importance: 4,
    fx_hint: 962,
    fy_hint: 146,
    time_start: -1750,
    time_end: 2100,
    evidence_type: 'prophet',
  },
  {
    id: 'n_evidence_jonah',
    kind: 'evidence',
    cluster_id: 'cl_prophecy',
    label: 'Jonah',
    label_ar: 'يونس',
    size: 14,
    zoom_level: 4,
    importance: 4,
    fx_hint: 864,
    fy_hint: 170,
    time_start: -750,
    time_end: 2100,
    evidence_type: 'prophet',
  },
  {
    id: 'n_evidence_job',
    kind: 'evidence',
    cluster_id: 'cl_prophecy',
    label: 'Job',
    label_ar: 'أيوب',
    size: 14,
    zoom_level: 4,
    importance: 4,
    fx_hint: 776,
    fy_hint: 126,
    time_start: -800,
    time_end: 2100,
    evidence_type: 'prophet',
  },
  {
    id: 'n_evidence_lot',
    kind: 'evidence',
    cluster_id: 'cl_prophecy',
    label: 'Lot',
    label_ar: 'لوط',
    size: 14,
    zoom_level: 4,
    importance: 4,
    fx_hint: 718,
    fy_hint: 38,
    time_start: -1800,
    time_end: 2100,
    evidence_type: 'prophet',
  },
  {
    id: 'n_evidence_zechariah',
    kind: 'evidence',
    cluster_id: 'cl_prophecy',
    label: 'Zechariah',
    label_ar: 'زكريا',
    size: 14,
    zoom_level: 4,
    importance: 4,
    fx_hint: 762,
    fy_hint: -216,
    time_start: -10,
    time_end: 2100,
    evidence_type: 'prophet',
  },
  {
    id: 'n_evidence_john',
    kind: 'evidence',
    cluster_id: 'cl_prophecy',
    label: 'John',
    label_ar: 'يحيى',
    size: 14,
    zoom_level: 4,
    importance: 4,
    fx_hint: 850,
    fy_hint: -250,
    time_start: 1,
    time_end: 2100,
    evidence_type: 'prophet',
  },
  {
    id: 'n_evidence_hud',
    kind: 'evidence',
    cluster_id: 'cl_prophecy',
    label: 'Hud',
    label_ar: 'هود',
    size: 14,
    zoom_level: 4,
    importance: 4,
    fx_hint: 948,
    fy_hint: -246,
    time_start: -2000,
    time_end: 2100,
    evidence_type: 'prophet',
  },
  {
    id: 'n_evidence_salih',
    kind: 'evidence',
    cluster_id: 'cl_prophecy',
    label: 'Salih',
    label_ar: 'صالح',
    size: 14,
    zoom_level: 4,
    importance: 4,
    fx_hint: 1038,
    fy_hint: -190,
    time_start: -1900,
    time_end: 2100,
    evidence_type: 'prophet',
  },
  {
    id: 'n_evidence_shuayb',
    kind: 'evidence',
    cluster_id: 'cl_prophecy',
    label: 'Shuayb',
    label_ar: 'شعيب',
    size: 14,
    zoom_level: 4,
    importance: 4,
    fx_hint: 1092,
    fy_hint: -82,
    time_start: -1700,
    time_end: 2100,
    evidence_type: 'prophet',
  },
];

export const SUPPLEMENTAL_EDGES: AtlasEdge[] = [
  { id: 'e65', source: 'n_concept_epistemology', target: 'n_claim_method_authority', type: 'explains', strength: 0.8 },
  { id: 'e66', source: 'n_claim_method_authority', target: 'n_evidence_laboratory', type: 'historical_example_of', strength: 0.7 },
  { id: 'e67', source: 'n_claim_method_authority', target: 'n_evidence_peer_review', type: 'supports', strength: 0.64 },
  { id: 'e68', source: 'n_concept_transmission', target: 'n_claim_chains_preserve_knowledge', type: 'explains', strength: 0.78 },
  { id: 'e69', source: 'n_claim_chains_preserve_knowledge', target: 'n_evidence_isnad', type: 'supports', strength: 0.76 },
  { id: 'e70', source: 'n_claim_chains_preserve_knowledge', target: 'n_evidence_commentary', type: 'supports', strength: 0.62 },
  { id: 'e71', source: 'n_concept_urban_form', target: 'n_claim_city_embeds_worldview', type: 'explains', strength: 0.8 },
  { id: 'e72', source: 'n_claim_city_embeds_worldview', target: 'n_evidence_market_mosque', type: 'historical_example_of', strength: 0.72 },
  { id: 'e73', source: 'n_claim_city_embeds_worldview', target: 'n_evidence_city_charter', type: 'supports', strength: 0.6 },
  { id: 'e74', source: 'n_concept_civilizational_memory', target: 'n_claim_memory_stabilizes_forms', type: 'explains', strength: 0.76 },
  { id: 'e75', source: 'n_claim_memory_stabilizes_forms', target: 'n_evidence_archive_city', type: 'supports', strength: 0.62 },
  { id: 'e76', source: 'n_claim_memory_stabilizes_forms', target: 'n_evidence_craft_guild', type: 'historical_example_of', strength: 0.62 },
  { id: 'e77', source: 'n_concept_virtue', target: 'n_claim_virtue_shapes_perception', type: 'expressed_as', strength: 0.82 },
  { id: 'e78', source: 'n_claim_virtue_shapes_perception', target: 'n_evidence_akhlaq', type: 'supports', strength: 0.72 },
  { id: 'e79', source: 'n_claim_virtue_shapes_perception', target: 'n_evidence_ascetic_practice', type: 'supports', strength: 0.66 },
  { id: 'e80', source: 'n_concept_relativism', target: 'n_claim_morality_detached', type: 'explains', strength: 0.74 },
  { id: 'e81', source: 'n_claim_morality_detached', target: 'n_evidence_values_language', type: 'supports', strength: 0.58 },
  { id: 'e82', source: 'n_claim_morality_detached', target: 'n_evidence_ethics_committee', type: 'historical_example_of', strength: 0.56 },
  { id: 'e83', source: 'n_concept_fitrah', target: 'n_claim_human_directed', type: 'expressed_as', strength: 0.82 },
  { id: 'e84', source: 'n_claim_human_directed', target: 'n_evidence_creation_verse', type: 'scriptural_anchor', strength: 0.86 },
  { id: 'e85', source: 'n_claim_human_directed', target: 'n_evidence_classical_anthropology', type: 'supports', strength: 0.58 },
  { id: 'e86', source: 'n_concept_desire', target: 'n_claim_desire_educated', type: 'explains', strength: 0.76 },
  { id: 'e87', source: 'n_claim_desire_educated', target: 'n_evidence_fasting', type: 'supports', strength: 0.66 },
  { id: 'e88', source: 'n_claim_desire_educated', target: 'n_evidence_adab', type: 'supports', strength: 0.6 },
  { id: 'e89', source: 'n_concept_pedagogy', target: 'n_claim_pedagogy_forms_perception', type: 'explains', strength: 0.8 },
  { id: 'e90', source: 'n_claim_pedagogy_forms_perception', target: 'n_evidence_madrasa', type: 'historical_example_of', strength: 0.66 },
  { id: 'e91', source: 'n_claim_pedagogy_forms_perception', target: 'n_evidence_recitation', type: 'supports', strength: 0.62 },
  { id: 'e92', source: 'n_concept_memory', target: 'n_claim_memory_is_civilizational', type: 'explains', strength: 0.74 },
  { id: 'e93', source: 'n_claim_memory_is_civilizational', target: 'n_evidence_hifz', type: 'supports', strength: 0.64 },
  { id: 'e94', source: 'n_claim_memory_is_civilizational', target: 'n_evidence_family_story', type: 'supports', strength: 0.58 },
  { id: 'e95', source: 'n_concept_transmission', target: 'n_concept_wahy', type: 'rooted_in', strength: 0.56 },
  { id: 'e96', source: 'n_concept_epistemology', target: 'n_concept_reason', type: 'related_to', strength: 0.52 },
  { id: 'e97', source: 'n_concept_urban_form', target: 'n_concept_empire', type: 'related_to', strength: 0.58 },
  { id: 'e98', source: 'n_concept_civilizational_memory', target: 'n_concept_memory', type: 'related_to', strength: 0.6 },
  { id: 'e99', source: 'n_concept_virtue', target: 'n_concept_family', type: 'related_to', strength: 0.56 },
  { id: 'e100', source: 'n_concept_relativism', target: 'n_concept_individualism', type: 'related_to', strength: 0.58 },
  { id: 'e101', source: 'n_concept_fitrah', target: 'n_concept_sharia', type: 'rooted_in', strength: 0.64 },
  { id: 'e102', source: 'n_concept_desire', target: 'n_concept_media', type: 'questions', strength: 0.46 },
  { id: 'e103', source: 'n_concept_pedagogy', target: 'n_concept_epistemology', type: 'related_to', strength: 0.56 },
  { id: 'e104', source: 'n_concept_memory', target: 'n_concept_covenant', type: 'related_to', strength: 0.44 },
  { id: 'e105', source: 'n_concept_justice', target: 'n_claim_justice_measures_power', type: 'expressed_as', strength: 0.84 },
  { id: 'e106', source: 'n_claim_justice_measures_power', target: 'n_evidence_qist', type: 'scriptural_anchor', strength: 0.88 },
  { id: 'e107', source: 'n_claim_justice_measures_power', target: 'n_evidence_sermon_farewell', type: 'supports', strength: 0.64 },
  { id: 'e108', source: 'n_concept_truth', target: 'n_claim_truth_is_received', type: 'expressed_as', strength: 0.82 },
  { id: 'e109', source: 'n_claim_truth_is_received', target: 'n_evidence_haqq', type: 'scriptural_anchor', strength: 0.9 },
  { id: 'e110', source: 'n_claim_truth_is_received', target: 'n_evidence_witness_testimony', type: 'supports', strength: 0.62 },
  { id: 'e111', source: 'n_concept_hereafter', target: 'n_claim_hereafter_scales_life', type: 'expressed_as', strength: 0.84 },
  { id: 'e112', source: 'n_claim_hereafter_scales_life', target: 'n_evidence_resurrection_verse', type: 'scriptural_anchor', strength: 0.9 },
  { id: 'e113', source: 'n_claim_hereafter_scales_life', target: 'n_evidence_mizan', type: 'supports', strength: 0.64 },
  { id: 'e114', source: 'n_concept_devil', target: 'n_claim_devil_whispers', type: 'explains', strength: 0.78 },
  { id: 'e115', source: 'n_claim_devil_whispers', target: 'n_evidence_iblis', type: 'scriptural_anchor', strength: 0.88 },
  { id: 'e116', source: 'n_claim_devil_whispers', target: 'n_evidence_temptation', type: 'supports', strength: 0.58 },
  { id: 'e117', source: 'n_concept_capitalism', target: 'n_claim_capitalism_reorders_value', type: 'explains', strength: 0.82 },
  { id: 'e118', source: 'n_claim_capitalism_reorders_value', target: 'n_evidence_adam_smith', type: 'historical_example_of', strength: 0.66 },
  { id: 'e119', source: 'n_claim_capitalism_reorders_value', target: 'n_evidence_stock_exchange', type: 'historical_example_of', strength: 0.62 },
  { id: 'e120', source: 'n_concept_thinkers', target: 'n_claim_thinkers_frame_worlds', type: 'explains', strength: 0.76 },
  { id: 'e121', source: 'n_claim_thinkers_frame_worlds', target: 'n_evidence_aristotle', type: 'historical_example_of', strength: 0.58 },
  { id: 'e122', source: 'n_claim_thinkers_frame_worlds', target: 'n_evidence_ibn_khaldun', type: 'historical_example_of', strength: 0.62 },
  { id: 'e123', source: 'n_concept_authors', target: 'n_claim_authors_preserve_worlds', type: 'explains', strength: 0.74 },
  { id: 'e124', source: 'n_claim_authors_preserve_worlds', target: 'n_evidence_ghazali', type: 'historical_example_of', strength: 0.58 },
  { id: 'e125', source: 'n_claim_authors_preserve_worlds', target: 'n_evidence_augustine', type: 'historical_example_of', strength: 0.52 },
  { id: 'e126', source: 'n_concept_prophets', target: 'n_claim_prophets_judge_idols', type: 'expressed_as', strength: 0.84 },
  { id: 'e127', source: 'n_claim_prophets_judge_idols', target: 'n_evidence_moses', type: 'historical_example_of', strength: 0.62 },
  { id: 'e128', source: 'n_claim_prophets_judge_idols', target: 'n_evidence_jesus', type: 'historical_example_of', strength: 0.58 },
  { id: 'e129', source: 'n_claim_prophets_judge_idols', target: 'n_evidence_muhammad', type: 'historical_example_of', strength: 0.68 },
  { id: 'e130', source: 'n_concept_justice', target: 'n_concept_sharia', type: 'rooted_in', strength: 0.68 },
  { id: 'e131', source: 'n_concept_justice', target: 'n_concept_sovereignty', type: 'questions', strength: 0.52 },
  { id: 'e132', source: 'n_concept_truth', target: 'n_concept_wahy', type: 'rooted_in', strength: 0.7 },
  { id: 'e133', source: 'n_concept_truth', target: 'n_concept_reason', type: 'contrasts', strength: 0.56 },
  { id: 'e134', source: 'n_concept_hereafter', target: 'n_concept_family', type: 'related_to', strength: 0.48 },
  { id: 'e135', source: 'n_concept_hereafter', target: 'n_concept_justice', type: 'related_to', strength: 0.52 },
  { id: 'e136', source: 'n_concept_devil', target: 'n_concept_desire', type: 'related_to', strength: 0.62 },
  { id: 'e137', source: 'n_concept_devil', target: 'n_concept_media', type: 'questions', strength: 0.48 },
  { id: 'e138', source: 'n_concept_capitalism', target: 'n_concept_individualism', type: 'related_to', strength: 0.68 },
  { id: 'e139', source: 'n_concept_capitalism', target: 'n_concept_family', type: 'contrasts', strength: 0.5 },
  { id: 'e140', source: 'n_concept_thinkers', target: 'n_concept_epistemology', type: 'related_to', strength: 0.66 },
  { id: 'e141', source: 'n_concept_authors', target: 'n_concept_civilizational_memory', type: 'related_to', strength: 0.62 },
  { id: 'e142', source: 'n_concept_prophets', target: 'n_concept_truth', type: 'related_to', strength: 0.7 },
  { id: 'e143', source: 'n_concept_prophets', target: 'n_claim_prophets_judge_power', type: 'related_to', strength: 0.74 },
  { id: 'e144', source: 'n_concept_interest', target: 'n_claim_interest_prices_dependence', type: 'explains', strength: 0.82 },
  { id: 'e145', source: 'n_claim_interest_prices_dependence', target: 'n_evidence_riba_verse', type: 'scriptural_anchor', strength: 0.9 },
  { id: 'e146', source: 'n_claim_interest_prices_dependence', target: 'n_evidence_debt_spiral', type: 'historical_example_of', strength: 0.64 },
  { id: 'e147', source: 'n_concept_charity', target: 'n_claim_charity_restores_circulation', type: 'expressed_as', strength: 0.8 },
  { id: 'e148', source: 'n_claim_charity_restores_circulation', target: 'n_evidence_sadaqah', type: 'supports', strength: 0.64 },
  { id: 'e149', source: 'n_claim_charity_restores_circulation', target: 'n_evidence_waqf_kitchen', type: 'historical_example_of', strength: 0.58 },
  { id: 'e150', source: 'n_concept_zakat', target: 'n_claim_zakat_directs_surplus', type: 'expressed_as', strength: 0.84 },
  { id: 'e151', source: 'n_claim_zakat_directs_surplus', target: 'n_evidence_zakat_recipients', type: 'scriptural_anchor', strength: 0.88 },
  { id: 'e152', source: 'n_claim_zakat_directs_surplus', target: 'n_evidence_alms_distributor', type: 'historical_example_of', strength: 0.58 },
  { id: 'e153', source: 'n_concept_needy', target: 'n_claim_needy_have_claim', type: 'expressed_as', strength: 0.78 },
  { id: 'e154', source: 'n_claim_needy_have_claim', target: 'n_evidence_orphan_care', type: 'scriptural_anchor', strength: 0.72 },
  { id: 'e155', source: 'n_claim_needy_have_claim', target: 'n_evidence_traveler_aid', type: 'supports', strength: 0.58 },
  { id: 'e156', source: 'n_concept_spirituality', target: 'n_claim_salah_orders_soul', type: 'expressed_as', strength: 0.82 },
  { id: 'e157', source: 'n_claim_salah_orders_soul', target: 'n_evidence_five_prayers', type: 'ritual_anchor', strength: 0.88 },
  { id: 'e158', source: 'n_claim_salah_orders_soul', target: 'n_evidence_dhikr', type: 'supports', strength: 0.62 },
  { id: 'e159', source: 'n_concept_angels', target: 'n_claim_angels_mediate_command', type: 'explains', strength: 0.8 },
  { id: 'e160', source: 'n_claim_angels_mediate_command', target: 'n_evidence_jibril', type: 'supports', strength: 0.74 },
  { id: 'e161', source: 'n_claim_angels_mediate_command', target: 'n_evidence_recording_angels', type: 'scriptural_anchor', strength: 0.7 },
  { id: 'e162', source: 'n_concept_maturity', target: 'n_claim_maturity_needs_training', type: 'explains', strength: 0.78 },
  { id: 'e163', source: 'n_claim_maturity_needs_training', target: 'n_evidence_rushd', type: 'scriptural_anchor', strength: 0.7 },
  { id: 'e164', source: 'n_claim_maturity_needs_training', target: 'n_evidence_adulthood_adab', type: 'supports', strength: 0.58 },
  { id: 'e165', source: 'n_claim_prophets_judge_idols', target: 'n_evidence_abraham', type: 'historical_example_of', strength: 0.66 },
  { id: 'e166', source: 'n_claim_prophets_judge_idols', target: 'n_evidence_noah', type: 'historical_example_of', strength: 0.62 },
  { id: 'e167', source: 'n_claim_prophets_judge_idols', target: 'n_evidence_joseph', type: 'historical_example_of', strength: 0.6 },
  { id: 'e168', source: 'n_claim_prophets_judge_power', target: 'n_evidence_david', type: 'historical_example_of', strength: 0.58 },
  { id: 'e169', source: 'n_claim_prophets_judge_power', target: 'n_evidence_solomon', type: 'historical_example_of', strength: 0.58 },
  { id: 'e170', source: 'n_claim_prophets_judge_idols', target: 'n_evidence_aaron', type: 'historical_example_of', strength: 0.56 },
  { id: 'e171', source: 'n_claim_prophets_judge_idols', target: 'n_evidence_isaac', type: 'historical_example_of', strength: 0.54 },
  { id: 'e172', source: 'n_claim_prophets_judge_idols', target: 'n_evidence_jacob', type: 'historical_example_of', strength: 0.54 },
  { id: 'e173', source: 'n_claim_prophets_judge_idols', target: 'n_evidence_ishmael', type: 'historical_example_of', strength: 0.58 },
  { id: 'e174', source: 'n_claim_prophets_judge_idols', target: 'n_evidence_jonah', type: 'historical_example_of', strength: 0.54 },
  { id: 'e175', source: 'n_claim_prophets_judge_idols', target: 'n_evidence_job', type: 'historical_example_of', strength: 0.52 },
  { id: 'e176', source: 'n_claim_prophets_judge_idols', target: 'n_evidence_lot', type: 'historical_example_of', strength: 0.54 },
  { id: 'e177', source: 'n_claim_prophets_judge_idols', target: 'n_evidence_zechariah', type: 'historical_example_of', strength: 0.52 },
  { id: 'e178', source: 'n_claim_prophets_judge_idols', target: 'n_evidence_john', type: 'historical_example_of', strength: 0.52 },
  { id: 'e179', source: 'n_claim_prophets_judge_idols', target: 'n_evidence_hud', type: 'historical_example_of', strength: 0.58 },
  { id: 'e180', source: 'n_claim_prophets_judge_idols', target: 'n_evidence_salih', type: 'historical_example_of', strength: 0.58 },
  { id: 'e181', source: 'n_claim_prophets_judge_idols', target: 'n_evidence_shuayb', type: 'historical_example_of', strength: 0.58 },
  { id: 'e182', source: 'n_concept_interest', target: 'n_concept_zakat', type: 'contrasts', strength: 0.7 },
  { id: 'e183', source: 'n_concept_charity', target: 'n_concept_needy', type: 'related_to', strength: 0.68 },
  { id: 'e184', source: 'n_concept_zakat', target: 'n_concept_needy', type: 'rooted_in', strength: 0.72 },
  { id: 'e185', source: 'n_concept_zakat', target: 'n_concept_charity', type: 'related_to', strength: 0.62 },
  { id: 'e186', source: 'n_concept_spirituality', target: 'n_concept_wahy', type: 'rooted_in', strength: 0.66 },
  { id: 'e187', source: 'n_concept_spirituality', target: 'n_concept_hereafter', type: 'related_to', strength: 0.58 },
  { id: 'e188', source: 'n_concept_angels', target: 'n_concept_hereafter', type: 'related_to', strength: 0.56 },
  { id: 'e189', source: 'n_concept_angels', target: 'n_concept_prophets', type: 'related_to', strength: 0.62 },
  { id: 'e190', source: 'n_concept_maturity', target: 'n_concept_fitrah', type: 'rooted_in', strength: 0.6 },
  { id: 'e191', source: 'n_concept_maturity', target: 'n_concept_family', type: 'related_to', strength: 0.56 }
];

export const SUPPLEMENTAL_VIEWS: AtlasZoomView[] = [
  {
    id: 'view_knowledge',
    label: 'Knowledge Cluster',
    cluster_id: 'cl_knowledge',
    x: -172,
    y: -462,
    k: 1.32,
    show_kinds: ['concept', 'claim'],
    label_min_importance: 6,
  },
  {
    id: 'view_civilization',
    label: 'Civilization Cluster',
    cluster_id: 'cl_civilization',
    x: 530,
    y: -398,
    k: 1.28,
    show_kinds: ['concept', 'claim'],
    label_min_importance: 6,
  },
  {
    id: 'view_human_nature',
    label: 'Human Nature Cluster',
    cluster_id: 'cl_human_nature',
    x: -676,
    y: 238,
    k: 1.32,
    show_kinds: ['concept', 'claim'],
    label_min_importance: 6,
  },
  {
    id: 'view_education',
    label: 'Education Cluster',
    cluster_id: 'cl_education',
    x: -18,
    y: 576,
    k: 1.24,
    show_kinds: ['concept', 'claim'],
    label_min_importance: 6,
  },
  {
    id: 'view_economics',
    label: 'Economics Cluster',
    cluster_id: 'cl_economics',
    x: -900,
    y: -150,
    k: 1.26,
    show_kinds: ['concept', 'claim'],
    label_min_importance: 6,
  },
  {
    id: 'view_prophecy',
    label: 'Prophecy Cluster',
    cluster_id: 'cl_prophecy',
    x: 885,
    y: -40,
    k: 1.24,
    show_kinds: ['concept', 'claim'],
    label_min_importance: 6,
  },
];

