#!/usr/bin/env python3
from __future__ import annotations

import json
import os
import sqlite3
from pathlib import Path

from _common import (
    D1Client,
    EVIDENCE_PATH,
    KELANI_EDITION_ID,
    KELANI_SOURCE_ID,
    MERGED_MEMBERS_PATH,
    MERGED_SETS_PATH,
    RAW_CHUNKS_PATH,
    REVIEW_QUEUE_PATH,
    SQL_OUTPUT_PATH,
    SOURCE_CONFIGS,
    chunked,
    confidence_to_score,
    insert_statement,
    load_local_env,
    read_json,
    root_text_from_value,
    sql_quote,
    sql_json,
    stable_hash,
    write_json,
    write_text,
)


class Resolver:
    def __init__(self, db_path: Path | None) -> None:
        self.conn = None
        self.d1 = None
        self.semantic_field_ids: dict[str, str] = {}
        self.root_ids: dict[str, str] = {}
        self.lemma_ids_by_bare: dict[str, str] = {}
        self.lemma_ids_by_display: dict[str, str] = {}
        if db_path and db_path.exists():
            self.conn = sqlite3.connect(db_path)
            self.conn.row_factory = sqlite3.Row
        else:
            candidate = D1Client("al")
            if candidate.is_available():
                self.d1 = candidate

    def close(self) -> None:
        if self.conn:
            self.conn.close()

    def query(self, sql: str) -> list[dict]:
        if self.conn:
            return [dict(row) for row in self.conn.execute(sql).fetchall()]
        if self.d1:
            return self.d1.query(sql)
        return []

    def prime(self, merged_sets: list[dict], merged_members: list[dict]) -> None:
        semantic_names = sorted(
            {
                (item.get("semantic_domain_key") or "MISC").replace("_", " ").title()
                for item in merged_sets
            }
        )
        for values in chunked(semantic_names):
            sql = (
                "SELECT id, field_name_en "
                "FROM ar_ling_semantic_fields "
                f"WHERE field_name_en IN ({', '.join(sql_quote(value) for value in values)})"
            )
            for row in self.query(sql):
                self.semantic_field_ids[row["field_name_en"]] = row["id"]

        root_values = sorted(
            {
                root_text
                for member in merged_members
                if (root_text := root_text_from_value(member.get("root_text")))
            }
        )
        for values in chunked(root_values):
            sql = (
                "SELECT id, root_text "
                "FROM ar_ling_roots "
                f"WHERE root_text IN ({', '.join(sql_quote(value) for value in values)})"
            )
            for row in self.query(sql):
                self.root_ids[row["root_text"]] = row["id"]

        lemma_bares = sorted({member["arabic_bare"] for member in merged_members if member.get("arabic_bare")})
        for values in chunked(lemma_bares):
            sql = (
                "SELECT id, lemma_text_bare "
                "FROM ar_ling_lemmas "
                f"WHERE lemma_text_bare IN ({', '.join(sql_quote(value) for value in values)})"
            )
            for row in self.query(sql):
                if row.get("lemma_text_bare"):
                    self.lemma_ids_by_bare[row["lemma_text_bare"]] = row["id"]

        lemma_displays = sorted({member["arabic_display"] for member in merged_members if member.get("arabic_display")})
        for values in chunked(lemma_displays):
            sql = (
                "SELECT id, lemma_text "
                "FROM ar_ling_lemmas "
                f"WHERE lemma_text IN ({', '.join(sql_quote(value) for value in values)})"
            )
            for row in self.query(sql):
                if row.get("lemma_text"):
                    self.lemma_ids_by_display[row["lemma_text"]] = row["id"]

    def semantic_field_id(self, field_name_en: str) -> str | None:
        return self.semantic_field_ids.get(field_name_en)

    def root_id(self, root_text: str) -> str | None:
        return self.root_ids.get(root_text)

    def lemma_id(self, bare: str, display: str) -> str | None:
        return self.lemma_ids_by_bare.get(bare) or self.lemma_ids_by_display.get(display)


def al_db_path() -> Path | None:
    for key in ("KM_ARABIC_LINGUISTIC_DB_PATH", "AL_DB_PATH", "D1_AL_DB_PATH"):
        value = os.getenv(key)
        if value:
            return Path(value)
    return None


def main() -> None:
    load_local_env()
    raw_chunks = read_json(RAW_CHUNKS_PATH, default=[])
    merged_sets = read_json(MERGED_SETS_PATH, default=[])
    merged_members = read_json(MERGED_MEMBERS_PATH, default=[])
    evidence_rows = read_json(EVIDENCE_PATH, default=[])
    review_rows = read_json(REVIEW_QUEUE_PATH, default=[])

    resolver = Resolver(al_db_path())
    resolver.prime(merged_sets, merged_members)
    sql_lines = [
        "-- Generated by 09_generate_d1_sql.py",
        "-- Near-synonym ingestion seed for km_arabic_linguistic",
        "",
        "-- Treat this import as authoritative for the near-synonym namespace.",
        "DELETE FROM ar_ling_quran_links WHERE id LIKE 'ALQL:NS:%' OR al_entity_ref LIKE 'NSM:%';",
        "DELETE FROM ar_ling_evidence_items WHERE id LIKE 'EI:NS:%';",
        "DELETE FROM ar_ling_near_synonym_review_queue;",
        "DELETE FROM ar_ling_near_synonym_member_sources;",
        "DELETE FROM ar_ling_near_synonym_set_sources;",
        "DELETE FROM ar_ling_near_synonym_evidence;",
        "DELETE FROM ar_ling_near_synonym_members;",
        "DELETE FROM ar_ling_near_synonym_sets;",
        (
            "DELETE FROM ar_ling_source_chunks "
            "WHERE source_id IN ("
            f"{sql_quote(SOURCE_CONFIGS['qdev'].source_id)}, "
            f"{sql_quote(SOURCE_CONFIGS['nqcm'].source_id)}, "
            f"{sql_quote(KELANI_SOURCE_ID)}"
            ");"
        ),
        "",
    ]

    source_rows = [
        {
            "id": SOURCE_CONFIGS["qdev"].source_id,
            "title_ar": "qurandev/synonyms",
            "title_en": "qurandev/synonyms",
            "source_type": "encyclopedia",
            "author_ref": None,
            "author_name": "Quran Dev",
            "period_label": "contemporary",
            "note_md": "GitHub source mined by the near-synonym ingestion pipeline.",
        },
        {
            "id": SOURCE_CONFIGS["nqcm"].source_id,
            "title_ar": "nqcm/synonyms-in-quran",
            "title_en": "nqcm/synonyms-in-quran",
            "source_type": "encyclopedia",
            "author_ref": None,
            "author_name": "NQCM",
            "period_label": "contemporary",
            "note_md": "GitHub source mined by the near-synonym ingestion pipeline.",
        },
        {
            "id": KELANI_SOURCE_ID,
            "title_ar": "مترادفات القرآن",
            "title_en": "Mutaradifat al-Quran",
            "source_type": "book",
            "author_ref": None,
            "author_name": "عبد الرحمٰن کیلانی",
            "period_label": "contemporary",
            "note_md": "Urdu Quranic near-synonym book OCR source mined by the near-synonym ingestion pipeline.",
        },
    ]
    edition_rows = [
        {
            "id": SOURCE_CONFIGS["qdev"].edition_id,
            "source_id": SOURCE_CONFIGS["qdev"].source_id,
            "edition_label": "gh-pages",
            "publisher": "GitHub",
            "year": None,
            "volume_count": None,
            "note_md": "Repository branch snapshot used by the ingestion pipeline.",
        },
        {
            "id": SOURCE_CONFIGS["nqcm"].edition_id,
            "source_id": SOURCE_CONFIGS["nqcm"].source_id,
            "edition_label": "master",
            "publisher": "GitHub",
            "year": None,
            "volume_count": None,
            "note_md": "Repository branch snapshot used by the ingestion pipeline.",
        },
        {
            "id": KELANI_EDITION_ID,
            "source_id": KELANI_SOURCE_ID,
            "edition_label": "PDF OCR",
            "publisher": "KitaboSunnat",
            "year": None,
            "volume_count": 1,
            "note_md": "Local scanned PDF OCR chunked by 06_extract_kelani_pdf_ocr.py.",
        },
    ]

    semantic_rows = {}
    for merged_set in merged_sets:
        field_name_en = (merged_set.get("semantic_domain_key") or "MISC").replace("_", " ").title()
        field_id = resolver.semantic_field_id(field_name_en) or merged_set["semantic_domain_id"]
        merged_set["semantic_domain_id"] = field_id
        semantic_rows[field_id] = {
            "id": field_id,
            "field_name_ar": merged_set.get("canonical_ar") or merged_set["canonical_en"],
            "field_name_en": field_name_en,
            "parent_field_id": None,
            "description_md": f"Near-synonym semantic domain for {merged_set['canonical_en']}.",
        }

    root_rows = {}
    lemma_rows = {}
    member_set_lookup = {row["id"]: row["set_id"] for row in merged_members}
    set_lookup = {row["id"]: row for row in merged_sets}
    for member in merged_members:
        root_text = root_text_from_value(member.get("root_text"))
        if member.get("root_text") and not root_text:
            review_rows.append(
                {
                    "id": f"NSRQ:UNSUPPORTED_ROOT:{stable_hash('review', member['id'], member.get('root_text'), length=16)}",
                    "set_id": member["set_id"],
                    "member_id": member["id"],
                    "evidence_id": None,
                    "issue_type": "unsupported_root",
                    "issue_detail": f"Unsupported root value: {member.get('root_text')}",
                    "source_id": None,
                    "chunk_id": None,
                    "status": "open",
                    "updated_at": None,
                }
            )
        if root_text:
            root_id = resolver.root_id(root_text) or f"ALR:NS:{stable_hash('root', root_text, length=16)}"
            member["root_id"] = root_id
            member["root_text"] = root_text
            letter_count = len(root_text.split("-"))
            root_rows[root_id] = {
                "id": root_id,
                "root_text": root_text,
                "root_letters": json.dumps(root_text.split("-"), ensure_ascii=False),
                "root_type": "trilateral" if letter_count == 3 else "quadrilateral" if letter_count == 4 else "quinqueliteral" if letter_count == 5 else "trilateral",
                "weak_pattern": None,
                "frequency_quran": 0,
                "frequency_hadith": 0,
                "meaning_core_en": member.get("basic_gloss"),
                "meaning_core_ar": None,
                "note_md": "Created by near-synonym ingestion.",
            }
        lemma_id = resolver.lemma_id(member["arabic_bare"], member["arabic_display"]) or f"ALL:NS:{stable_hash('lemma', member['arabic_bare'], member['set_id'], length=16)}"
        member["lemma_id"] = lemma_id
        part_of_speech = set_lookup[member["set_id"]].get("pos_hint") or "other"
        part_of_speech = part_of_speech if part_of_speech in {
            "noun",
            "verb",
            "adjective",
            "adverb",
            "particle",
            "preposition",
            "conjunction",
            "pronoun",
            "proper_noun",
            "other",
        } else "other"
        lemma_rows[lemma_id] = {
            "id": lemma_id,
            "root_id": member.get("root_id"),
            "lemma_text": member["arabic_display"],
            "lemma_text_bare": member["arabic_bare"],
            "part_of_speech": part_of_speech,
            "verb_form": None,
            "is_quran_word": 1,
            "frequency_quran": 0,
            "note_md": "Created by near-synonym ingestion.",
        }

    for row in source_rows:
        sql_lines.append(insert_statement("ar_ling_sources", row, update_columns=["title_ar", "title_en", "source_type", "author_name", "period_label", "note_md"]))
    sql_lines.append("")
    for row in edition_rows:
        sql_lines.append(insert_statement("ar_ling_source_editions", row, update_columns=["source_id", "edition_label", "publisher", "year", "volume_count", "note_md"]))
    sql_lines.append("")
    for chunk in raw_chunks:
        sql_lines.append(
            insert_statement(
                "ar_ling_source_chunks",
                {
                    "id": chunk["id"],
                    "source_id": chunk["source_id"],
                    "edition_id": chunk["edition_id"],
                    "chunk_kind": chunk.get("chunk_kind") or "semantic",
                    "chunk_seq": chunk.get("chunk_seq") or 1,
                    "heading_norm": chunk.get("title"),
                    "text_ar": chunk.get("raw_text") or "",
                    "text_en": None,
                    "page_no": None,
                    "volume_no": None,
                    "tokens_approx": len((chunk.get("raw_text") or "").split()),
                    "is_embedded": 0,
                    "qdrant_id": None,
                    "meta_json": json.dumps(
                        {
                            "source_path": chunk.get("source_path"),
                            "source_url": chunk.get("source_url"),
                            "published_url": chunk.get("published_url"),
                            "title": chunk.get("title"),
                            "checksum": chunk.get("checksum"),
                            "raw_format": chunk.get("raw_format"),
                            "metadata": chunk.get("metadata"),
                        },
                        ensure_ascii=False,
                    ),
                },
                update_columns=["source_id", "edition_id", "chunk_kind", "chunk_seq", "heading_norm", "text_ar", "text_en", "tokens_approx", "meta_json"],
            )
        )
    sql_lines.append("")

    for row in semantic_rows.values():
        sql_lines.append(
            insert_statement(
                "ar_ling_semantic_fields",
                row,
                update_columns=["field_name_ar", "field_name_en", "parent_field_id", "description_md"],
            )
        )
    sql_lines.append("")

    for row in root_rows.values():
        sql_lines.append(
            insert_statement(
                "ar_ling_roots",
                row,
                update_columns=["root_text", "root_letters", "root_type", "weak_pattern", "meaning_core_en", "meaning_core_ar", "note_md"],
            )
        )
    sql_lines.append("")

    for row in lemma_rows.values():
        sql_lines.append(
            insert_statement(
                "ar_ling_lemmas",
                row,
                update_columns=["root_id", "lemma_text", "lemma_text_bare", "part_of_speech", "verb_form", "is_quran_word", "frequency_quran", "note_md"],
            )
        )
    sql_lines.append("")

    for merged_set in merged_sets:
        sql_lines.append(
            insert_statement(
                "ar_ling_near_synonym_sets",
                {
                    "id": merged_set["id"],
                    "set_name": merged_set["set_name"],
                    "description_md": merged_set["description_md"],
                    "slug": merged_set["slug"],
                    "canonical_en": merged_set["canonical_en"],
                    "canonical_ar": merged_set.get("canonical_ar"),
                    "canonical_ur": merged_set.get("canonical_ur"),
                    "semantic_domain_id": merged_set["semantic_domain_id"],
                    "pos_hint": merged_set.get("pos_hint") or "mixed",
                    "short_summary": merged_set.get("short_summary"),
                    "source_status": merged_set.get("source_status") or "manual",
                    "confidence": merged_set.get("confidence") or "needs_review",
                    "review_status": merged_set.get("review_status") or "draft",
                    "updated_at": merged_set.get("updated_at"),
                },
                update_columns=[
                    "set_name",
                    "description_md",
                    "slug",
                    "canonical_en",
                    "canonical_ar",
                    "canonical_ur",
                    "semantic_domain_id",
                    "pos_hint",
                    "short_summary",
                    "source_status",
                    "confidence",
                    "review_status",
                    "updated_at",
                ],
            )
        )
    sql_lines.append("")

    for member in merged_members:
        sql_lines.append(
            insert_statement(
                "ar_ling_near_synonym_members",
                {
                    "id": member["id"],
                    "set_id": member["set_id"],
                    "lemma_id": member["lemma_id"],
                    "nuance_note": member.get("nuance_note") or member.get("basic_gloss") or member["arabic_display"],
                    "arabic_display": member["arabic_display"],
                    "arabic_bare": member["arabic_bare"],
                    "basic_gloss": member.get("basic_gloss"),
                    "basic_gloss_ur": member.get("basic_gloss_ur"),
                    "contrast_note": member.get("contrast_note"),
                    "contrast_note_ur": member.get("contrast_note_ur"),
                    "usage_rule": member.get("usage_rule"),
                    "usage_rule_ur": member.get("usage_rule_ur"),
                    "quran_usage_pattern": member.get("quran_usage_pattern"),
                    "quran_usage_pattern_ur": member.get("quran_usage_pattern_ur"),
                    "nuance_note_ur": member.get("nuance_note_ur"),
                    "source_status": member.get("source_status") or "manual",
                    "claim_basis": member.get("claim_basis") or "direct_source",
                    "confidence": member.get("confidence") or "needs_review",
                    "sort_order": member.get("sort_order") or 0,
                },
                update_columns=[
                    "set_id",
                    "lemma_id",
                    "nuance_note",
                    "arabic_display",
                    "arabic_bare",
                    "basic_gloss",
                    "basic_gloss_ur",
                    "contrast_note",
                    "contrast_note_ur",
                    "usage_rule",
                    "usage_rule_ur",
                    "quran_usage_pattern",
                    "quran_usage_pattern_ur",
                    "nuance_note_ur",
                    "source_status",
                    "claim_basis",
                    "confidence",
                    "sort_order",
                ],
            )
        )
    sql_lines.append("")

    evidence_item_rows = []
    quran_link_rows = []
    member_lookup = {row["id"]: row for row in merged_members}
    for evidence in evidence_rows:
        if not evidence.get("lemma_id") and evidence.get("member_id") in member_lookup:
            evidence["lemma_id"] = member_lookup[evidence["member_id"]].get("lemma_id")
    for evidence in evidence_rows:
        evidence_item_id = f"EI:NS:{stable_hash('evidence-item', evidence['id'], length=16)}"
        evidence_item_rows.append(
            {
                "id": evidence_item_id,
                "evidence_type": "quran_text",
                "text_ar": evidence.get("arabic_quote") or (next((m["arabic_display"] for m in merged_members if m["id"] == evidence.get("member_id")), "") or evidence["qr_ref"]),
                "text_en": evidence.get("translation_quote"),
                "qr_ref": evidence["qr_ref"],
                "source_ref": f"AL:{evidence['source_id']}" if evidence.get("source_id") else None,
                "locator_json": json.dumps(
                    {
                        "surah": evidence["surah"],
                        "ayah": evidence["ayah"],
                        "word_index": evidence.get("word_index"),
                        "word_occurrence_ref": evidence.get("word_occurrence_ref"),
                    },
                    ensure_ascii=False,
                ),
                "note_md": evidence.get("explanation_md"),
            }
        )
        if evidence.get("member_id") and evidence.get("qr_ref"):
            quran_link_rows.append(
                {
                    "id": f"ALQL:NS:{stable_hash('quran-link', evidence['member_id'], evidence['qr_ref'], length=16)}",
                    "al_entity_ref": evidence["member_id"],
                    "al_entity_type": "near_synonym_member",
                    "qr_scope_ref": evidence["qr_ref"],
                    "link_type": "attests",
                    "note_md": evidence.get("explanation_md"),
                    "confidence": confidence_to_score(evidence.get("confidence")),
                }
            )

    for row in evidence_item_rows:
        sql_lines.append(
            insert_statement(
                "ar_ling_evidence_items",
                row,
                update_columns=["evidence_type", "text_ar", "text_en", "qr_ref", "source_ref", "locator_json", "note_md"],
            )
        )
    sql_lines.append("")

    for evidence in evidence_rows:
        sql_lines.append(
            insert_statement(
                "ar_ling_near_synonym_evidence",
                evidence,
                update_columns=[
                    "set_id",
                    "member_id",
                    "lemma_id",
                    "qr_ref",
                    "surah",
                    "ayah",
                    "word_index",
                    "word_occurrence_ref",
                    "arabic_quote",
                    "translation_quote",
                    "explanation_md",
                    "evidence_type",
                    "source_id",
                    "chunk_id",
                    "confidence",
                    "validation_status",
                    "note_md",
                ],
            )
        )
    sql_lines.append("")

    for row in quran_link_rows:
        sql_lines.append(
            insert_statement(
                "ar_ling_quran_links",
                row,
                update_columns=["al_entity_ref", "al_entity_type", "qr_scope_ref", "link_type", "note_md", "confidence"],
            )
        )
    sql_lines.append("")

    set_source_rows = []
    member_source_rows = []
    for merged_set in merged_sets:
        set_source_rows.extend(merged_set.get("set_sources", []))
    for member in merged_members:
        member_source_rows.extend(member.get("source_claims", []))

    for row in set_source_rows:
        sql_lines.append(insert_statement("ar_ling_near_synonym_set_sources", row, update_columns=["set_id", "source_id", "chunk_id", "source_role", "source_path", "source_url", "note_md", "confidence"]))
    sql_lines.append("")
    for row in member_source_rows:
        sql_lines.append(insert_statement("ar_ling_near_synonym_member_sources", row, update_columns=["member_id", "source_id", "chunk_id", "claim_type", "claim_text", "claim_basis", "confidence", "note_md"]))
    sql_lines.append("")
    for row in review_rows:
        sql_lines.append(insert_statement("ar_ling_near_synonym_review_queue", row, update_columns=["set_id", "member_id", "evidence_id", "issue_type", "issue_detail", "source_id", "chunk_id", "status", "updated_at"]))

    write_json(MERGED_SETS_PATH, merged_sets)
    write_json(MERGED_MEMBERS_PATH, merged_members)
    write_json(EVIDENCE_PATH, evidence_rows)
    write_text(SQL_OUTPUT_PATH, "\n".join(sql_lines) + "\n")
    write_json(REVIEW_QUEUE_PATH, review_rows)
    resolver.close()
    print(f"Wrote D1 SQL to {SQL_OUTPUT_PATH}")


if __name__ == "__main__":
    main()
