-- Populate canonical_ur from qurandev topicUr
-- These are Urdu translations of the concept labels

UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'مرد' WHERE id = 'NS:HUMAN:MAN';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'آرام کرنا' WHERE id = 'NS:STATE:TRANQUIL_REST';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'آزمائش کرنا' WHERE id = 'NS:TO:TO_TEST_EXAM';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'آسان' WHERE id = 'NS:EASY:EASY';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'آسمان' WHERE id = 'NS:HEAVEN:HEAVEN';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'آسیب زدہ کرنا' WHERE id = 'NS:TO:TO_HAUNT';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'آگ' WHERE id = 'NS:FIRE:FIRE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'آگ جلنا جلانا' WHERE id = 'NS:THE:THE_BURNING_OF_FIRE_TO_LIT_FIRE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'آگ کا دوسری چیزوں  کو جلانا' WHERE id = 'NS:THE:THE_FIRE_S_BURNING_SOMETHING';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'بجھنا بجھانا' WHERE id = 'NS:TO:TO_BE_EXTINGUISHED_TO_EXTINGUISH';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'امید    لگانا     امید لگانا' WHERE id = 'NS:TO:TO_BE_AWARE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'آباد کرنا' WHERE id = 'NS:TO:TO_CULTIVATE_POPULATE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'آگے سامنے' WHERE id = 'NS:IN:IN_FRONT';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'آگے آنا بڑھنا' WHERE id = 'NS:TO:TO_COME_FORWARD_TO_GO_FORWARD';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'آگے بیھجنا' WHERE id = 'NS:TO:TO_SEND_FORWARD';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'آلات جنگ' WHERE id = 'NS:ARMS:ARMS_WEAPONS_ARMOUR';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'آنا' WHERE id = 'NS:TO:TO_COME';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'آنکھ' WHERE id = 'NS:EYES:EYES';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'آوارہ پھرنا' WHERE id = 'NS:TO:TO_WANDER_VAGRANCY';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'آواز اور اسکی اقسام' WHERE id = 'NS:NOISE:NOISE_AND_ITS_KIND';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'آرزو کرنا' WHERE id = 'NS:TO:TO_WISH';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'آڑ   Also refer toپردہ     and دیوار' WHERE id = 'NS:BARRIER:BARRIER';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'آزاد' WHERE id = 'NS:FREE:FREE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'آزادکرنا Also refer to رخصت کرنا' WHERE id = 'NS:TO:TO_FREE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'کھولنا' WHERE id = 'NS:TO:TO_BOIL_TO_RAGE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'اجڈ' WHERE id = 'NS:OBSTINATE:OBSTINATE_STUBBORN';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'اچانک' WHERE id = 'NS:SUDDENLY:SUDDENLY';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'اچھا خوب بہتر' WHERE id = 'NS:VERY:VERY_GOOD_BETTER';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'اختیار [رکھنا]' WHERE id = 'NS:TO:TO_HAVE_POWER';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'اختیار کرنا' WHERE id = 'NS:TO:TO_CHOOSE_SELECT';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'ادھار' WHERE id = 'NS:DEBT:DEBT_CREDIT';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'ارادہ کرنا[قصد کرنا]' WHERE id = 'NS:TO:TO_INTEND';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'پھیلانا' WHERE id = 'NS:TO:TO_PERSIST';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'ابھار' WHERE id = 'NS:PROTRUDE:PROTRUDE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'اڑنا اڑانا' WHERE id = 'NS:TO:TO_FLY_TO_MAKE_FLY';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'اشارہ کرنا' WHERE id = 'NS:TO:TO_INDICATE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'اطاعت وتابعداری پیروی- فرمانبرداری' WHERE id = 'NS:OBEDIENCE:OBEDIENCE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'اعتدال' WHERE id = 'NS:MIDDLE:MIDDLE_PATH_BALANCED_MODERATION';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'اعمال نامہ' WHERE id = 'NS:THE:THE_BOOK_OF_DEEDS';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'اقتدار بخشنا' WHERE id = 'NS:TO:TO_GIVE_AUTHORITY';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'ابھارنا' WHERE id = 'NS:TO:TO_ENCOURAGE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'اکیلا' WHERE id = 'NS:ONE:ONE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'اگر' WHERE id = 'NS:IF:IF';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'الٹ دینا-اوندھا کرنا-ہونا' WHERE id = 'NS:TO:TO_TURN_OVER';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'الگ[ جدا یا علحیدہ] کرنا' WHERE id = 'NS:TO:TO_SEPARATE_TO_DETATCH';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'الگ ہونا' WHERE id = 'NS:TO:TO_SEPARATE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'انٹریاں' WHERE id = 'NS:INTESTINES:INTESTINES';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'انجام [کار]' WHERE id = 'NS:END:END_RESULT_CONSEQUENCE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'andaza lagana' WHERE id = 'NS:TO:TO_ESTIMATE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'اتارنا- اترنا' WHERE id = 'NS:TO:TO_DESCEND_TO_REVEAL_COME_DOWN';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'andar' WHERE id = 'NS:INSIDE:INSIDE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'اندھا' WHERE id = 'NS:BLIND:BLIND';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'انصاف[کرنا]' WHERE id = 'NS:JUSTICE:JUSTICE_TO_DO_JUSTICE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'انکار کرنا' WHERE id = 'NS:TO:TO_REFUTE_TO_REFUSE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'انگلیاں' WHERE id = 'NS:FINGERS:FINGERS';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'ڈھانکنا' WHERE id = 'NS:TO:TO_COVER';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'اولاد' WHERE id = 'NS:CHILDREN:CHILDREN_OFFSPRING';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'اون' WHERE id = 'NS:WOOL:WOOL';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'اونٹ' WHERE id = 'NS:CAMEL:CAMEL';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'اونگھ' WHERE id = 'NS:DOZE:DOZE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'اترانا – تکبر کرنا' WHERE id = 'NS:TO:TO_BE_BOASTFUL_ARROGANT';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'ایندھن' WHERE id = 'NS:FUEL:FUEL';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'اٹکل پچو [من گھڑت]باتیں کرنا' WHERE id = 'NS:TO:TO_INVENT_STORIES_SLANDER';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'اٹھانا' WHERE id = 'NS:TO:TO_CARRY';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'اٹھنا' WHERE id = 'NS:TO:TO_GET_UP';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'اجازت لینا' WHERE id = 'NS:TO:TO_GET_PERMISSION';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'ضامن' WHERE id = 'NS:GUARANTOR:GUARANTOR';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'ہمت ہارنا' WHERE id = 'NS:TO:TO_BE_HELPLESS_FALL_SHORT';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'عقل - عقلمند' WHERE id = 'NS:BRAIN:BRAIN_INTELLIGENT';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'نیچے [پست ] کرنا' WHERE id = 'NS:TO:TO_LOSE_HIS_BRAINS';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'عورت' WHERE id = 'NS:WOMEN:WOMEN';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'عہد - وعدہ' WHERE id = 'NS:PROMISE:PROMISE_OATH';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'عالم' WHERE id = 'NS:SCHOLAR:SCHOLAR';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'عبادت گاہیں' WHERE id = 'NS:PLACES:PLACES_OF_WORSHIPS';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'عزاب – سزا' WHERE id = 'NS:PUNISHMENT:PUNISHMENT';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'نیکی کرنا' WHERE id = 'NS:TO:TO_GIVE_PUNISHMENT';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'عزاب کی اقسام' WHERE id = 'NS:DIFFERENT:DIFFERENT_TYPES_OF_PUNISHMENTS';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'عزت بخشنا' WHERE id = 'NS:CONFER:CONFER_HONOR_DIGNITY';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'عزت والا - معزز' WHERE id = 'NS:HONORABLE:HONORABLE_RESPECTABLE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'حاجت' WHERE id = 'NS:NEED:NEED';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'حقدار' WHERE id = 'NS:RIGHTFUL:RIGHTFUL';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'حق مہر' WHERE id = 'NS:RIGHT:RIGHT_OF_DOWRY';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'حملہ کرنا' WHERE id = 'NS:TO:TO_ATTACK';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'حیران ہونا' WHERE id = 'NS:TO:TO_BE_ASTONISHED';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'حیض' WHERE id = 'NS:MENSTRUATION:MENSTRUATION';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'حاضر' WHERE id = 'NS:PRESENT:PRESENT';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'حال - حالت' WHERE id = 'NS:CONDITION:CONDITION_STATE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'حاکم' WHERE id = 'NS:RULER:RULER_AUTHORITARIAN';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'حد سے بڑھنا – زیادتی کرنا' WHERE id = 'NS:TO:TO_EXCEED_BOUNDS_TRANSGRESS';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'حد سے کم کرنا' WHERE id = 'NS:TO:TO_FALL_SHORT';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'حرام' WHERE id = 'NS:FORBIDDEN:FORBIDDEN';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'حصہ' WHERE id = 'NS:PART:PART_PORTION';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'حفاظت کرنا' WHERE id = 'NS:TO:TO_PROTECT';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'صاف کرنا' WHERE id = 'NS:TO:TO_CLEANSE_WIPE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'صبح' WHERE id = 'NS:MORNING:MORNING';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'صبر کرنا' WHERE id = 'NS:TO:TO_BE_PATIENT';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'صلح' WHERE id = 'NS:PEACE:PEACE_TREATY';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'Taaqat' WHERE id = 'NS:STRENGTH:STRENGTH';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'Taaqat rakhna' WHERE id = 'NS:HAVING:HAVING_STRENGTH_STRONG';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'Tareeqah, Dastoor' WHERE id = 'NS:TRADITION:TRADITION';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'Tanah deyna' WHERE id = 'NS:TAUNT:TAUNT';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'Thawq dalna' WHERE id = 'NS:TO:TO_PUT_SHACKLES';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'Tama3 rakhna' WHERE id = 'NS:TO:TO_KEEP_HOPE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'Tay karna' WHERE id = 'NS:TO:TO_DECIDE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'باپ' WHERE id = 'NS:FATHER:FATHER';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'بازو' WHERE id = 'NS:ARM:ARM_WING_OF_BIRD';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'باغ' WHERE id = 'NS:GARDEN:GARDEN';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'قید کرنا   قیدی بنانا' WHERE id = 'NS:TO:TO_LEAVE_SOME_REMAINING';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'بال' WHERE id = 'NS:HAIR:HAIR';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'بانجھ' WHERE id = 'NS:BARREN:BARREN';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'قوت دینا' WHERE id = 'NS:TO:TO_BIND_FASTEN';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'بت' WHERE id = 'NS:STATUE:STATUE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'بجلی' WHERE id = 'NS:LIGHTNING:LIGHTNING';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'بچنا' WHERE id = 'NS:TO:TO_BE_SAVED';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'بچہ [لڑکا]' WHERE id = 'NS:CHILD:CHILD';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'بچھونا' WHERE id = 'NS:SPREAD:SPREAD_BEDDING_ETC';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'بدبختی' WHERE id = 'NS:WRETCHEDNESS:WRETCHEDNESS';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'بد دعا دینا' WHERE id = 'NS:TO:TO_CURSE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'بدصورت بنانا ہونا' WHERE id = 'NS:TO:TO_BECOME_MAKE_DISFIGURED';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'بدکاری بدکار' WHERE id = 'NS:IMMORAL:IMMORAL_SINFUL_SINNER';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'بدلہ' WHERE id = 'NS:RECOMPENSE:RECOMPENSE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'بات' WHERE id = 'NS:SPEECH:SPEECH';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'بدلہ لینا' WHERE id = 'NS:TO:TO_TAKE_REVENGE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'بدمست ہونا' WHERE id = 'NS:TO:TO_BE_DRUNK_INEBRIATED';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'برا- برائی' WHERE id = 'NS:BAD:BAD_EVIL';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'برابھلا کہنا' WHERE id = 'NS:TO:TO_ABUSE_REVILE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'برباد ہونا- کرنا ضائع ہونا- کرنا' WHERE id = 'NS:TO:TO_BE_RUINED_TO_DESTROY';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'برداشت کرنا' WHERE id = 'NS:TO:TO_TOLERATE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'بڑا- [بزرگ]' WHERE id = 'NS:GREAT:GREAT_NOBLE_SUPERIOR';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'بات کرنا' WHERE id = 'NS:TO:TO_TALK';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'برائی' WHERE id = 'NS:GREATNESS:GREATNESS';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'بڑھنا بڑھانا' WHERE id = 'NS:INCREASE:INCREASE_TO_INCREASE_EXPAND';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'بستی-بستی والے' WHERE id = 'NS:VILLAGE:VILLAGE_VILLAGERS';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'بکری' WHERE id = 'NS:GOAT:GOAT';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'بکھرنا [پراگندہ ہونا]' WHERE id = 'NS:TO:TO_BE_SCATTERED_DISHEVELLED';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'بلند ہونا' WHERE id = 'NS:TO:TO_BE_LOFTY_TO_BE_ABOVE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'بنانا' WHERE id = 'NS:TO:TO_MAKE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'بننا' WHERE id = 'NS:WEAVE:WEAVE_KNIT';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'بادشاہی' WHERE id = 'NS:SOVEREIGNTY:SOVEREIGNTY';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'بوجھ' WHERE id = 'NS:LOAD:LOAD_BURDEN';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'بوجھل ہونا [گراں ہونا]' WHERE id = 'NS:TO:TO_BE_BURDENED_LOADED';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'بوڑھا' WHERE id = 'NS:OLD:OLD';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'بوسیدہ ہونا' WHERE id = 'NS:TO:TO_DECAY_ROT';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'بولنا' WHERE id = 'NS:TO:TO_SPEAK';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'قتل کرنا' WHERE id = 'NS:TO:TO_POUR_TO_FLOW';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'بہانہ – بہانہ بنانا' WHERE id = 'NS:EXCUSE:EXCUSE_TO_MAKE_AN_EXCUSE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'بہتان' WHERE id = 'NS:SLANDER:SLANDER';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'بہکنا بہکانا' WHERE id = 'NS:ASTRAY:ASTRAY_TO_LEAD_ASTRAY';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'بھاگنا بھگانا' WHERE id = 'NS:FLEE:FLEE_CAUSE_TO_FLEE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'بادل' WHERE id = 'NS:CLOUDS:CLOUDS';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'بھائی' WHERE id = 'NS:BROTHER:BROTHER';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'بھر جانا' WHERE id = 'NS:TO:TO_FILL_UP';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'بھوک' WHERE id = 'NS:HUNGER:HUNGER';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'بھولنا بھلانا' WHERE id = 'NS:FORGET:FORGET_CAUSE_TO_FORGET';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'بھننا' WHERE id = 'NS:TO:TO_ROAST_LIKE_ON_A_SPIT_FIRE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'بیٹا بیٹی' WHERE id = 'NS:SON:SON_DAUGHTER';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'بیٹھنا' WHERE id = 'NS:TO:TO_SIT';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'بیمار' WHERE id = 'NS:ILL:ILL';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'بار[دفعہ مرتبہ]' WHERE id = 'NS:TIME:TIME_S';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'بیوی' WHERE id = 'NS:WIFE:WIFE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'بے رغبتی کرنا' WHERE id = 'NS:DISINCLINATION:DISINCLINATION';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'بیزار ہونا' WHERE id = 'NS:TO:TO_BE_ANNOYED_AND_DISSATISFIED';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'بیشک' WHERE id = 'NS:INDEED:INDEED';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'بیکار ہونا' WHERE id = 'NS:TO:TO_BE_JOBLESS_WORTHLESS';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'بےنصیب' WHERE id = 'NS:LACKING:LACKING_GOOD_FORTUNE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'بےنیاز' WHERE id = 'NS:WITHOUT:WITHOUT_WANT_COMPLETELY_INDEPENDENT';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'بےہودہ کلام' WHERE id = 'NS:NONSENSE:NONSENSE_AND_FRIVOLOUS_TALK';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'بارش' WHERE id = 'NS:RAIN:RAIN';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'بےہوش ہونا' WHERE id = 'NS:TO:TO_BE_UNCONSCIOUS';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'باز آنا' WHERE id = 'NS:TO:TO_BACK_OFF_ABSTAIN';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'چابی کنجی' WHERE id = 'NS:KEYS:KEYS';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'چشمہ' WHERE id = 'NS:FOUNTAIN:FOUNTAIN_SPRING';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'چلنا' WHERE id = 'NS:TO:TO_WALK_AND_TYPES_OF_WALKING';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'چلانا' WHERE id = 'NS:CAUSE:CAUSE_TO_WALK_OR_MOVE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'چلانا چیخنا' WHERE id = 'NS:TO:TO_SCREAM';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'چمٹنا' WHERE id = 'NS:TO:TO_STICK_CLING';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'چمک چمکنا' WHERE id = 'NS:SHINE:SHINE_FLASH_TO_SHINE_FLASH';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'چند' WHERE id = 'NS:SOME:SOME_FEW';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'چن لینا' WHERE id = 'NS:TO:TO_CHOOSE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'چوپائے' WHERE id = 'NS:CREATURES:CREATURES';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'چادر' WHERE id = 'NS:SHEET:SHEET';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'چوری کرنا' WHERE id = 'NS:TO:TO_STEAL';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'چوکیدار' WHERE id = 'NS:GUARD:GUARD';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'چھپانا' WHERE id = 'NS:TO:TO_CONCEAL';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'چھت' WHERE id = 'NS:ROOF:ROOF';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'چھوڑنا' WHERE id = 'NS:TO:TO_LEAVE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'چھڑانا' WHERE id = 'NS:CAUSE:CAUSE_TO_LIBERATE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'چھونا' WHERE id = 'NS:TOUCH:TOUCH';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'چاند' WHERE id = 'NS:MOON:MOON';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'چاہنا' WHERE id = 'NS:TO:TO_LIKE_INTEND_DESIRE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'چپ ہونا رہنا' WHERE id = 'NS:TO:TO_STAY_BE_QUIET';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'چراغ' WHERE id = 'NS:LAMP:LAMP';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'چرانا' WHERE id = 'NS:TO:TO_GRAZE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'چڑھنا' WHERE id = 'NS:TO:TO_CLIMB_ASCEND_RISE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'سپرد [حوالے] کرنا' WHERE id = 'NS:TO:TO_ENTER_TO_BE_ENTERED';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'درمیان' WHERE id = 'NS:IN:IN_BETWEEN';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'دشمن دشمنی' WHERE id = 'NS:ENEMY:ENEMY_ANIMOSITY';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'دل' WHERE id = 'NS:HEART:HEART';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'دل میں بات ڈالنا' WHERE id = 'NS:INSPIRATION:INSPIRATION_IN_THE_HEART';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'دلیل' WHERE id = 'NS:PROOF:PROOF';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'دن اور اسکے اوقات' WHERE id = 'NS:DAY:DAY_AND_ITS_TIMES';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'دنیا کے مختلف نام' WHERE id = 'NS:DIFFERENT:DIFFERENT_NAMES_FOR_THE_WORLD';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'دور' WHERE id = 'NS:FAR:FAR_AWAY';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'تنگ کرنا- ہونا' WHERE id = 'NS:TO:TO_DISTANCE_TO_BE_DISTANCED';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'داروغہ' WHERE id = 'NS:SUPERINTENDENT:SUPERINTENDENT';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'ڈورنا' WHERE id = 'NS:TO:TO_RUN';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'ڈورانا' WHERE id = 'NS:CAUSE:CAUSE_TO_RUN';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'دوزخ اور اسکے مختلف نام' WHERE id = 'NS:HELL:HELL_AND_ITS_VARIOUS_NAMES';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'دوزخ کے فرشتے' WHERE id = 'NS:ANGELS:ANGELS_OF_HELL_FIRE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'دوست' WHERE id = 'NS:FRIEND:FRIEND';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'دھتکارنا' WHERE id = 'NS:DRIVE:DRIVE_DOGS_OUT_REVILE_REPROVE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'دھندلانا' WHERE id = 'NS:CONCEALED:CONCEALED';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'دھواں' WHERE id = 'NS:SMOKE:SMOKE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'دھوپ' WHERE id = 'NS:SUNSHINE:SUNSHINE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'دھوکہ دینا' WHERE id = 'NS:TO:TO_DECEIVE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'داغ دینا' WHERE id = 'NS:TO:TO_MARK_SCAR';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'دیکھنا' WHERE id = 'NS:TO:TO_SEE_LOOK';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'دیکھنا [کیفیت نظر]' WHERE id = 'NS:VARIOUS:VARIOUS_WAYS_OF_LOOKING';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'دکھلانا' WHERE id = 'NS:TO:TO_SHOW_REVEAL';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'دین' WHERE id = 'NS:RELIGION:RELIGION';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'دینا' WHERE id = 'NS:TO:TO_GIVE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'دیوار' WHERE id = 'NS:WALL:WALL';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'دیوانہ- دیوانگی' WHERE id = 'NS:LUNATIC:LUNATIC_INSANITY';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'دبلا' WHERE id = 'NS:SLIM:SLIM_LEAN';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'دراز ہونا - کرنا' WHERE id = 'NS:PROLONG:PROLONG_LENGTHEN';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'در پے ہونا' WHERE id = 'NS:VERY:VERY_PERSISTENT';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'درخت اور پودے' WHERE id = 'NS:TREES:TREES_AND_SHRUBS';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'درست ٹھیک' WHERE id = 'NS:CORRECT:CORRECT_SOUND';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'درست کرنا' WHERE id = 'NS:TO:TO_CORRECT_RECTIFY';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'ڈالنا' WHERE id = 'NS:TO:TO_THROW_POUR_CAST_AWAY';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'ڈبونا' WHERE id = 'NS:TO:TO_DROWN_DIP';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'ڈرنا' WHERE id = 'NS:TO:TO_FEAR';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'ڈرانا' WHERE id = 'NS:TO:TO_FRIGHTEN';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'ڈول' WHERE id = 'NS:BUCKET:BUCKET';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'ڈھال' WHERE id = 'NS:SHIELD:SHIELD';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'ڈھلنا' WHERE id = 'NS:SETTING:SETTING_IE_SUN';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'ڈھونڈنا' WHERE id = 'NS:TO:TO_SEARCH';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'ذبح کرنا' WHERE id = 'NS:TO:TO_SLAUGHTER';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'ذریعہ' WHERE id = 'NS:MEANS:MEANS_MEDIUM';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'ذلت' WHERE id = 'NS:DISGRACE:DISGRACE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'ذلیل' WHERE id = 'NS:DISGRACED:DISGRACED';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'ذلیل کرنا' WHERE id = 'NS:TO:TO_DISGRACE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'ذمہ داری' WHERE id = 'NS:RESPONSIBILITY:RESPONSIBILITY';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'فائدہ – فائدہ دینا' WHERE id = 'NS:BENEFIT:BENEFIT_TO_GIVE_BENEFIT';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'فساد کرنا- ڈالنا' WHERE id = 'NS:TO:TO_CORRUPT_TO_CREATE_PROBLEMS';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'فضول باتیں کرنا' WHERE id = 'NS:USELESS:USELESS_TALK';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'فضیلت دینا' WHERE id = 'NS:TO:TO_GIVE_HONOUR';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'فراخی آسودگی' WHERE id = 'NS:SUFFICIENT:SUFFICIENT';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'فراخ ہونا – کرنا' WHERE id = 'NS:TO:TO_BE_BROADEN_TO_MAKE_SPACE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'فرشتہ' WHERE id = 'NS:ANGEL:ANGEL';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'فرق' WHERE id = 'NS:DIFFERENCE:DIFFERENCE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'فریاد رسی' WHERE id = 'NS:CRY:CRY_OUT_FOR_ASSISTANCE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'فریاد کرنا' WHERE id = 'NS:TO:TO_IMPLORE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'گاڑنا' WHERE id = 'NS:TO:TO_PITCH_PLANT';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'گزرنا' WHERE id = 'NS:TO:TO_PASS_BY';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'گلا' WHERE id = 'NS:NECK:NECK';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'گم ہونا' WHERE id = 'NS:TO:TO_BE_LOST';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'گمان کرنا' WHERE id = 'NS:TO:TO_THINK_HAVE_THOUGHTS';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'گناہ' WHERE id = 'NS:SIN:SIN';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'گنہگار' WHERE id = 'NS:SINFUL:SINFUL';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'گند گی نجاست' WHERE id = 'NS:FILTH:FILTH_IMPURITY';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'گننا' WHERE id = 'NS:TO:TO_COUNT';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'گود' WHERE id = 'NS:LAP:LAP';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'گہرا - گہرائی' WHERE id = 'NS:DEEP:DEEP_DEEPNESS';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'گردش ایام' WHERE id = 'NS:PASSAGE:PASSAGE_OF_TIME';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'گھاٹ' WHERE id = 'NS:WATERING:WATERING_PLACE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'گھاٹی' WHERE id = 'NS:VALLEY:VALLEY';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'گھر' WHERE id = 'NS:HOUSE:HOUSE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'وقت' WHERE id = 'NS:TIME:TIME';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'گھسنا' WHERE id = 'NS:ENTER:ENTER_BY_FORCE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'گھسیٹنا' WHERE id = 'NS:TO:TO_DRAG';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'گھوڑا' WHERE id = 'NS:HORSE:HORSE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'گھیرنا' WHERE id = 'NS:TO:TO_SURROUND';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'گرمی – گرم کرنا- ہونا' WHERE id = 'NS:HEAT:HEAT_TO_HEAT_TO_BE_HOT';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'گرمی حاصل کرنا' WHERE id = 'NS:TO:TO_OBTAIN_HEAT';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'گرنا - گرانا' WHERE id = 'NS:TO:TO_FALL_CAUSE_TO_FALL';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'گروی رکھنا' WHERE id = 'NS:TO:TO_PAWN';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'گڑھا' WHERE id = 'NS:DITCH:DITCH';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'غار' WHERE id = 'NS:CAVE:CAVE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'غبار' WHERE id = 'NS:DUST:DUST';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'غصہ' WHERE id = 'NS:ANGER:ANGER_TEMPER';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'غصۃ دلانا' WHERE id = 'NS:TO:TO_ENRAGE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'غم' WHERE id = 'NS:GRIEF:GRIEF_SADNESS';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'غمگین ہونا' WHERE id = 'NS:TO:TO_BE_SAD';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'غور کرنا' WHERE id = 'NS:TO:TO_REFLECT';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'ہاتھ' WHERE id = 'NS:HAND:HAND_EITHER_RIGHT_HAND_OR_LEFT_HAND_ARM';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'ہم آہنگی - ہونا' WHERE id = 'NS:CONGRUENCE:CONGRUENCE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'ہمیشہ' WHERE id = 'NS:ALWAYS:ALWAYS';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'ہمیشہ ہونا - رہنا' WHERE id = 'NS:TO:TO_REMAIN_ALWAYS';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'ہنسنا' WHERE id = 'NS:TO:TO_LAUGH';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'ہونا' WHERE id = 'NS:TO:TO_HAPPEN';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'ہاں' WHERE id = 'NS:YES:YES';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'ہانپنا' WHERE id = 'NS:TO:TO_PANT';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'ہدایت دینا پانا' WHERE id = 'NS:TO:TO_RECEIVE_GUIDANCE_TO_GIVE_GUIDANCE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'ہلاکت' WHERE id = 'NS:DESTRUCTION:DESTRUCTION';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'ہلنا - ہلانا' WHERE id = 'NS:TO:TO_MOVE_TO_SHAKE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'جاسوسی کرنا' WHERE id = 'NS:TO:TO_SPY';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'جلدی کرنا' WHERE id = 'NS:TO:TO_HASTEN_TO_HURRY';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'جماعت' WHERE id = 'NS:GROUP:GROUP';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'جماعت جانوروں کی' WHERE id = 'NS:GROUPS:GROUPS_OF_ANIMALS';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'جن' WHERE id = 'NS:JINN:JINN';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'جنت اور اسکے مختلف نام' WHERE id = 'NS:PARADISE:PARADISE_AND_ITS_DIFFERENT_NAMES';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'جنگ' WHERE id = 'NS:WAR:WAR_BATTLE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'جننا' WHERE id = 'NS:TO:TO_GIVE_BIRTH';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'جواب دینا' WHERE id = 'NS:TO:TO_ANSWER_REPLY';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'جوانی' WHERE id = 'NS:ADOLESCENCE:ADOLESCENCE_YOUTH';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'جوڑا' WHERE id = 'NS:COUPLE:COUPLE_PAIR';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'جاننا' WHERE id = 'NS:TO:TO_KNOW';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'جوڑنا' WHERE id = 'NS:TO:TO_JOIN';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'جہاں-  جہاں کہیں' WHERE id = 'NS:WHERE:WHERE_WHEREVER';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'جھڑکنا' WHERE id = 'NS:TO:TO_SCOLD';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'جھکنا مائل ہونا' WHERE id = 'NS:TO:TO_BEND_BOW_INCLINE_STOOP';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'جھکانا' WHERE id = 'NS:CAUSE:CAUSE_TO_BEND_STOOP';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'جھگڑنا' WHERE id = 'NS:TO:TO_QUARREL';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'جھوٹ' WHERE id = 'NS:LIE:LIE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'جھوٹ بولنا یا بنانا' WHERE id = 'NS:TO:TO_LIE_FABRICATE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'جھٹلانا' WHERE id = 'NS:TO:TO_FALSIFY_BELIE_REFUTE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'کب' WHERE id = 'NS:WHEN:WHEN';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'جڑھ' WHERE id = 'NS:ROOT:ROOT';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'جسم' WHERE id = 'NS:BODY:BODY';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'جکڑنا' WHERE id = 'NS:TO:TO_BIND_FASTEN_SHACKLE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'جگہ' WHERE id = 'NS:PLACE:PLACE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'جلا وطنی' WHERE id = 'NS:EXILE:EXILE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'کاٹنا' WHERE id = 'NS:TO:TO_CUT';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'کتاب' WHERE id = 'NS:BOOK:BOOK';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'کترا جانا – بچ کر نکل جانا' WHERE id = 'NS:TO:TO_DODGE_EVADE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'کریدنا' WHERE id = 'NS:TO:TO_SCRATCH';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'کڑوا' WHERE id = 'NS:BITTER:BITTER_UNPALATABLE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'کسان' WHERE id = 'NS:PEASANT:PEASANT_FARMER';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'کشتی جہاز' WHERE id = 'NS:SHIP:SHIP';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'کعبہ اور اسکے مختلف نام' WHERE id = 'NS:KAABA:KAABA_AND_ITS_DIFFERENT_NAMES';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'کل' WHERE id = 'NS:YESTERDAY:YESTERDAY_TOMORROW';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'کمانا – کمائی کرنا' WHERE id = 'NS:TO:TO_EARN';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'کمرہ' WHERE id = 'NS:ROOM:ROOM';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'کمزور' WHERE id = 'NS:WEAK:WEAK';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'کنارہ' WHERE id = 'NS:EDGE:EDGE_BRINK';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'کنواں' WHERE id = 'NS:WELL:WELL';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'کوڑا' WHERE id = 'NS:WHIP:WHIP';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'کاغز' WHERE id = 'NS:PAPER:PAPER';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'کہ گویا کہ' WHERE id = 'NS:WHO:WHO_WHICH_THAT_SUCH_AS';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'کہاں' WHERE id = 'NS:WHERE:WHERE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'کہانیاں  واقعات' WHERE id = 'NS:STORIES:STORIES_LEGENDS_INCIDENTS';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'کھال' WHERE id = 'NS:SKIN:SKIN';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'کھینچنا' WHERE id = 'NS:TO:TO_REMOVE_THE_SKIN';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'کھانا' WHERE id = 'NS:FOOD:FOOD';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'کھلانا' WHERE id = 'NS:TO:TO_FEED';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'کھجور' WHERE id = 'NS:DATES:DATES';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'کافی ہونا' WHERE id = 'NS:TO:TO_BE_ENOUGH';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'کھیلنا' WHERE id = 'NS:TO:TO_PLAY';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'کیا' WHERE id = 'NS:WHAT:WHAT';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'کیسے' WHERE id = 'NS:HOW:HOW';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'کیوں – کیوں نہ' WHERE id = 'NS:WHY:WHY_WHY_NOT';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'کام – کام کرنا' WHERE id = 'NS:WORK:WORK_TO_WORK';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'نجات پانا' WHERE id = 'NS:TO:TO_BE_SUCCESSFUL';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'کان' WHERE id = 'NS:EARS:EARS';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'کانپنا' WHERE id = 'NS:TO:TO_TREMBLE_SHIVER';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'خاوند' WHERE id = 'NS:HUSBAND:HUSBAND';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'خشک ہونا' WHERE id = 'NS:DRY:DRY_DEHYDRATED';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'خلاصی چھٹکارا پانا' WHERE id = 'NS:TO:TO_LIBERATE_TO_FREE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'خلقت مخلوق' WHERE id = 'NS:CREATION:CREATION';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'خواب' WHERE id = 'NS:DREAM:DREAM';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'خواہش' WHERE id = 'NS:WISH:WISH_DESIRE_HOPE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'خوبصورت' WHERE id = 'NS:BEAUTIFUL:BEAUTIFUL';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'خوراک لانا' WHERE id = 'NS:TO:TO_BRING_FOOD_NOURISHMENT';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'خوشحالی' WHERE id = 'NS:HAPPINESS:HAPPINESS_AND_PROSPERITY';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'خوشے' WHERE id = 'NS:BUNCH:BUNCH_OF_GRAPES_ETC_EAR_OF_CORN';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'خبر' WHERE id = 'NS:NEWS:NEWS';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'خیانت کرنا' WHERE id = 'NS:BREACH:BREACH_OF_TRUST';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'خیمہ - سائبان' WHERE id = 'NS:TENT:TENT_PAVILION';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'ختم ہونا' WHERE id = 'NS:FINISH:FINISH';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'خدمت گار' WHERE id = 'NS:SERVANT:SERVANT';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'خرابی' WHERE id = 'NS:SPOILED:SPOILED_RUINED';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'خرچ کرنا' WHERE id = 'NS:TO:TO_SPEND';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'خرید وفروخت کرنا' WHERE id = 'NS:TO:TO_UNDERTAKE_TRANSACTIONS';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'خزانہ' WHERE id = 'NS:TREASURE:TREASURE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'لکھوانا' WHERE id = 'NS:CAUSE:CAUSE_TO_WRITE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'لکھنے والے' WHERE id = 'NS:WRITERS:WRITERS';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'لگاتار پے در پے' WHERE id = 'NS:CONTINUOUS:CONTINUOUS';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'لوح محفوظ اور اسکے مختلف نام' WHERE id = 'NS:DIVINE:DIVINE_TABLET_RECORDING_AND_ITS_VARIOUS_NAMES';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'لونڈی  غلام' WHERE id = 'NS:MAID:MAID_SERVANT';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'لینا' WHERE id = 'NS:TO:TO_TAKE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'لین دین کرنا' WHERE id = 'NS:TO:TO_BE_INVOLVED_IN_TRANSACTIONS';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'لائق ہونا' WHERE id = 'NS:TO:TO_BE_CAPABLE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'لپیٹنا لپٹنا' WHERE id = 'NS:TO:TO_COIL_ENWRAP';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'لٹکنا لٹکانا' WHERE id = 'NS:TO:TO_HANG_DANGLE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'لحاظ رکھنا' WHERE id = 'NS:TO:TO_REGARD';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'لشکر' WHERE id = 'NS:ARMY:ARMY';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'لکڑی' WHERE id = 'NS:WOOD:WOOD';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'لکھنا' WHERE id = 'NS:TO:TO_WRITE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'مجلس' WHERE id = 'NS:ORGANIZATION:ORGANIZATION_MEETING';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'مچھلی' WHERE id = 'NS:FISH:FISH';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'محبت -  کرنا' WHERE id = 'NS:LOVE:LOVE_TO_LOVE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'محل' WHERE id = 'NS:PALACE:PALACE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'مختلف' WHERE id = 'NS:DIFFERENT:DIFFERENT_VARIOUS';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'مدت' WHERE id = 'NS:TIME:TIME_LENGTH_OF_TIME';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'مدد گار' WHERE id = 'NS:HELPER:HELPER';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'مزاق اڑانا' WHERE id = 'NS:TO:TO_RIDICULE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'مزا' WHERE id = 'NS:TASTE:TASTE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'مزین کرنا' WHERE id = 'NS:TO:TO_ADORN_DECORATE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'مسافر' WHERE id = 'NS:TRAVELLER:TRAVELLER';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'مسخر کرنا' WHERE id = 'NS:TO:TO_HARNESS';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'مسلط کرنا' WHERE id = 'NS:TO:TO_SUBDUED';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'مشقت میں ڈالنا' WHERE id = 'NS:TO:TO_PUT_IN_HARDSHIP';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'مشورہ کرنا' WHERE id = 'NS:TO:TO_CONSULT';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'مال و دولت' WHERE id = 'NS:GOODS:GOODS_WEALTH';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'مشہور کرنا' WHERE id = 'NS:TO:TO_MAKE_FAMOUS';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'مضبوط' WHERE id = 'NS:STRONG:STRONG_FIXED';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'معاف کرنا  بخشنا درگزر کرنا' WHERE id = 'NS:TO:TO_FORGIVE_PARDON';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'معبود' WHERE id = 'NS:DEITY:DEITY';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'مقدور - حیثیت' WHERE id = 'NS:STATUS:STATUS_AND_CAPACITY';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'مقرر کرنا' WHERE id = 'NS:TO:TO_APPOINT';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'مکھی' WHERE id = 'NS:FLY:FLY';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'ملنا' WHERE id = 'NS:TO:TO_MEET';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'ملانا' WHERE id = 'NS:TO:TO_JOIN_MIX_BLEND';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'مالک' WHERE id = 'NS:OWNER:OWNER';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'منہ پھیرنا' WHERE id = 'NS:TO:TO_TURN_YOUR_FACE_AWAY';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'موافقت کرنا' WHERE id = 'NS:TO:TO_AGREE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'موڑنا' WHERE id = 'NS:TO:TO_BEND_TURN';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'مہربان' WHERE id = 'NS:MERCIFUL:MERCIFUL';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'مہر لگانا' WHERE id = 'NS:TO:TO_STAMP_TO_PUT_A_SEAL';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'مہلت دینا' WHERE id = 'NS:TO:TO_GIVE_TIME_REPRIEVE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'مہمان' WHERE id = 'NS:VISITOR:VISITOR';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'مہینے' WHERE id = 'NS:MONTHS:MONTHS';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'میخ' WHERE id = 'NS:PEG:PEG_NAIL';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'ماں' WHERE id = 'NS:MOTHER:MOTHER';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'مانگنا' WHERE id = 'NS:TO:TO_ASK_BEG';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'مٹانا' WHERE id = 'NS:TO:TO_ERASE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'مٹی اور اسکی مختلف حالتیں' WHERE id = 'NS:SOIL:SOIL_AND_ITS_DIFFERENT_STAGES';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'مجامعت کرنا' WHERE id = 'NS:TO:TO_COPULATE_INTERCOURSE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'نا امید ہونا' WHERE id = 'NS:TO:TO_BE_HOPELESS';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'نامبارک' WHERE id = 'NS:INAUSPICIOUS:INAUSPICIOUS';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'نذر و نیاز' WHERE id = 'NS:GIFTS:GIFTS_AND_OBLATIONS';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'نرم ہونا - کرنا' WHERE id = 'NS:TO:TO_BE_SOFT_SOFTEN';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'نزدیک ہونا - کرنا' WHERE id = 'NS:TO:TO_BE_NEAR_TO_MAKE_IT_CLOSE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'نشانی' WHERE id = 'NS:SIGN:SIGN';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'نشان لگانا' WHERE id = 'NS:TO:TO_PLACE_AN_EMBLEM';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'نصیحت – کرنا – حاصل کرنا' WHERE id = 'NS:ADVICE:ADVICE_TO_GIVE_TO_ATTAIN';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'نعمت' WHERE id = 'NS:GRACE:GRACE_DIVINE_BLESSINGS';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'ناپاک' WHERE id = 'NS:IMPURE:IMPURE_POLLUTED';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'نکاح کرنا - کرانا' WHERE id = 'NS:TO:TO_MARRY_MARRY_OFF';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'نکلنا' WHERE id = 'NS:TO:TO_COME_OUT';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'نگاہ' WHERE id = 'NS:GLANCE:GLANCE_SIGHT';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'نگلنا' WHERE id = 'NS:TO:TO_SWALLOW';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'نہانا -دھونا' WHERE id = 'NS:TO:TO_WASH';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'نہیں' WHERE id = 'NS:NO:NO_NAY';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'نیا – نیا ہونا' WHERE id = 'NS:NEW:NEW_TO_BE_FRESH';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'ناپسندیدہ' WHERE id = 'NS:DISLIKED:DISLIKED_THING';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'نیچے' WHERE id = 'NS:UNDER:UNDER_LOWEST';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'نیک  نیکبخت' WHERE id = 'NS:PIOUS:PIOUS_VIRTUOUS';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'نیکی – نیک کام' WHERE id = 'NS:GOOD:GOOD_PIETY';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'نادان' WHERE id = 'NS:IGNORANT:IGNORANT_NAIVE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'ناراضگی' WHERE id = 'NS:UPSET:UPSET_AND_ANGRY';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'ناشکرا' WHERE id = 'NS:UNGRATEFUL:UNGRATEFUL';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'نافرمانی کرنا' WHERE id = 'NS:TO:TO_DISOBEY';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'ناک' WHERE id = 'NS:NOSE:NOSE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'نام - رکھنا' WHERE id = 'NS:NAME:NAME_TO_KEEP_A_NAME';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'پاس' WHERE id = 'NS:NEAR:NEAR_CLOSE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'پچھلا' WHERE id = 'NS:BEHIND:BEHIND_LATTER';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'پچھتانا' WHERE id = 'NS:TO:TO_REGRET';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'پرانا ہونا' WHERE id = 'NS:TO:TO_BE_OLD_ANCIENT';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'پردہ' WHERE id = 'NS:VEIL:VEIL';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'پردہ کرنا' WHERE id = 'NS:TO:TO_COVER_VEIL';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'پرورش کرنا' WHERE id = 'NS:TO:TO_BRING_UP_NURTURE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'پڑھانا پڑھنا' WHERE id = 'NS:TO:TO_TEACH_TO_READ';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'پسند کرنا' WHERE id = 'NS:TO:TO_LIKE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'پکارنا' WHERE id = 'NS:TO:TO_SHOUT_CALL_OUT';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'پکڑنا' WHERE id = 'NS:TO:TO_SEIZE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'پاک [ستھرا]' WHERE id = 'NS:PURE:PURE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'پناہ – پناہ گاہ' WHERE id = 'NS:PROTECTION:PROTECTION_SHELTER_REFUGE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'پوچھنا' WHERE id = 'NS:TO:TO_ASK';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'پورا  [سارا سب]' WHERE id = 'NS:WHOLE:WHOLE_ENTIRE_ALL';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'پورا کرنا -ہونا' WHERE id = 'NS:ACCOMPLISH:ACCOMPLISH_TO_COMPLETE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'پوشاک' WHERE id = 'NS:GARMENTS:GARMENTS_CLOTHES';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'پہار' WHERE id = 'NS:MOUNTAIN:MOUNTAIN';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'پہچاننا' WHERE id = 'NS:TO:TO_RECOGNIZE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'پہلا پہلی پہلے' WHERE id = 'NS:FIRST:FIRST_AT_FIRST';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'پہلو [کروٹ]' WHERE id = 'NS:SIDE:SIDE_IN_SLEEPING';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'پاک کرنا' WHERE id = 'NS:TO:TO_PURIFY_CLEANSE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'پہنچنا' WHERE id = 'NS:TO:TO_REACH';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'پھاڑنا' WHERE id = 'NS:TO:TO_TEAR_RIP';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'پھٹنا' WHERE id = 'NS:TO:TO_BURST_EXPLODE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'پھرنا' WHERE id = 'NS:TO:TO_STROLL_TO_WANDER';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'پھیرنا' WHERE id = 'NS:TO:TO_TURN_OVER_TO_REFUTE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'پھسلنا  پھسلانا' WHERE id = 'NS:TO:TO_SLIP_CAUSE_TO_SLIP_TO_SEDUCE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'پھل' WHERE id = 'NS:FRUIT:FRUIT';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'پھل پکنا' WHERE id = 'NS:RIPENING:RIPENING_OF_THE_FRUIT';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'پھونک مارنا' WHERE id = 'NS:TO:TO_BLOW';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'پانا' WHERE id = 'NS:TO:TO_OBTAIN';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'پھینکنا' WHERE id = 'NS:TO:TO_DISCARD';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'پیاسا' WHERE id = 'NS:THIRSTY:THIRSTY';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'پیالہ' WHERE id = 'NS:BOWL:BOWL';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'پیپ' WHERE id = 'NS:PUSS:PUSS';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'پیٹھ پشت' WHERE id = 'NS:BACKBONE:BACKBONE_LOIN';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'پیچھا کرنا' WHERE id = 'NS:TO:TO_FOLLOW';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'پیچھے' WHERE id = 'NS:BACK:BACK_BEHIND';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'پیچھے آنا' WHERE id = 'NS:ENSUE:ENSUE_TO_COME_AFTER';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'پانی اور اسکی اقسام' WHERE id = 'NS:WATER:WATER_AND_ITS_DIFFERENT_TYPES';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'پیچھے رہنا' WHERE id = 'NS:TO:TO_STAY_BEHIND';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'پیچھے کرنا یا ڈالنا' WHERE id = 'NS:TO:TO_PUT_BEHIND_CAUSE_TO_DELAY';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'پیچھے کے دوسرے مشتقات' WHERE id = 'NS:OTHER:OTHER_DERIVATIVES_OF_BEHIND';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'پیدا کرنا' WHERE id = 'NS:TO:TO_CREATE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'پیش کرنا' WHERE id = 'NS:TO:TO_PRESENT';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'پیشانی' WHERE id = 'NS:FOREHEAD:FOREHEAD';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'پیغمبر' WHERE id = 'NS:PROPHET:PROPHET';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'پیغمبروں کے حریف' WHERE id = 'NS:THE:THE_OPPONENT_RIVAL_OF_PROPHETS';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'پینا' WHERE id = 'NS:TO:TO_DRINK';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'پانی کے رستے اور اسکے ذخیرے' WHERE id = 'NS:DIFFERENT:DIFFERENT_TYPES_OF_NATURAL_FLOWING_WATER';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'پانی مانگنا' WHERE id = 'NS:TO:TO_ASK_FOR_WATER';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'پاوّں' WHERE id = 'NS:FEET:FEET';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'پتھر' WHERE id = 'NS:STONE:STONE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'قربانی کا جانور' WHERE id = 'NS:ANIMAL:ANIMAL_OF_SACRIFICE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'قسم اٹھانا' WHERE id = 'NS:TO:TO_TAKE_AN_OATH';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'قسم توڑنا' WHERE id = 'NS:TO:TO_BREAK_AN_OATH';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'قلعہ' WHERE id = 'NS:FORT:FORT';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'قمیص' WHERE id = 'NS:SHIRT:SHIRT_GARMENT';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'قیامت اور اسکے مختلف نام' WHERE id = 'NS:DOOMSDAY:DOOMSDAY_AND_ITS_DIFFERENT_NAMES';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'قید خانہ' WHERE id = 'NS:JAIL:JAIL';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'قافلہ' WHERE id = 'NS:CARAVAN:CARAVAN';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'قبر' WHERE id = 'NS:GRAVE:GRAVE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'قبول کرنا' WHERE id = 'NS:TO:TO_ACCEPT';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'قبیلہ خاندان' WHERE id = 'NS:FAMILY:FAMILY_TRIBE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'قدم' WHERE id = 'NS:STEP:STEP';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'قرار پکڑنا' WHERE id = 'NS:TO:TO_HAVE_STABILITY';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'قرآن کے مختلف نام' WHERE id = 'NS:DIFFERENT:DIFFERENT_NAMES_OF_THE_QURAN';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'رات' WHERE id = 'NS:NIGHT:NIGHT';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'رشتہ  دار' WHERE id = 'NS:RELATIVE:RELATIVE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'رضامندی [خوشنودی]' WHERE id = 'NS:APPROVAL:APPROVAL';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'رغبت کرنا' WHERE id = 'NS:TO:TO_INCLINE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'رکھنا' WHERE id = 'NS:TO:TO_PUT_PLACE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'رنگ' WHERE id = 'NS:COLOUR:COLOUR';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'روشنی  روشن کرنا - ہونا' WHERE id = 'NS:LIGHT:LIGHT_TO_ILLUMINATE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'روزہ دار' WHERE id = 'NS:FASTING:FASTING_PERSON';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'روکنا' WHERE id = 'NS:TO:TO_PROHIBIT_STOP';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'رکنا' WHERE id = 'NS:TO:TO_STOP';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'روندنا' WHERE id = 'NS:TO:TO_TRAMPLE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'رات کے کام' WHERE id = 'NS:ACTIONS:ACTIONS_IN_THE_NIGHT';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'رونق' WHERE id = 'NS:SPLENDOR:SPLENDOR_ILLUMINED_RESPLENDENT';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'ریت' WHERE id = 'NS:SAND:SAND';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'راہ - راستہ' WHERE id = 'NS:PATH:PATH_WAY';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'راہ ڈالنا –رائج کرنا' WHERE id = 'NS:TO:TO_ESTABLISH';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'رتبہ پانا' WHERE id = 'NS:TO:TO_ATTAIN_STATUS';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'رخ کرنا' WHERE id = 'NS:TO:TO_FACE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'ردی – نا کارہ' WHERE id = 'NS:WORTHLESS:WORTHLESS';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'رسسی' WHERE id = 'NS:ROPE:ROPE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'ساتھ' WHERE id = 'NS:ALONG:ALONG_WITH';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'سخت' WHERE id = 'NS:HARD:HARD';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'سختی' WHERE id = 'NS:HARDNESS:HARDNESS';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'سر اٹھانا' WHERE id = 'NS:TO:TO_RAISE_HEAD';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'سردار' WHERE id = 'NS:CHIEF:CHIEF_LEADER';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'سردی' WHERE id = 'NS:COLD:COLD_WINTER';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'سرکشی کرنا' WHERE id = 'NS:RECKLESS:RECKLESS_AND_ARROGANT';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'سرگوشی کرنا' WHERE id = 'NS:TO:TO_WHISPER';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'سرنگ' WHERE id = 'NS:TUNNEL:TUNNEL';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'سستی کرنا' WHERE id = 'NS:TO:TO_BE_LAZY_PROCASTINATE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'سفر کرنا' WHERE id = 'NS:TO:TO_TRAVEL';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'ساتھی' WHERE id = 'NS:COMPANION:COMPANION';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'سمجھنا - سمجھانا' WHERE id = 'NS:TO:TO_UNDERSTAND_TO_ADVISE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'سننا' WHERE id = 'NS:TO:TO_LISTEN';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'سنوارنا' WHERE id = 'NS:TO:TO_ADORN';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'سوائے' WHERE id = 'NS:EXCEPT:EXCEPT';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'سونا' WHERE id = 'NS:TO:TO_SLEEP';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'سیاہ سیاہی' WHERE id = 'NS:BLACK:BLACK';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'سیدھا سیدھی' WHERE id = 'NS:STRAIGHT:STRAIGHT';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'سیر کرانا' WHERE id = 'NS:CAUSE:CAUSE_TO_TRAVEL';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'سیڑھی' WHERE id = 'NS:LADDER:LADDER';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'سال' WHERE id = 'NS:YEAR:YEAR';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'سیکھنا سیکھانا' WHERE id = 'NS:TO:TO_LEARN_TEACH';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'سامان' WHERE id = 'NS:GOODS:GOODS_PROVISIONS';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'سامنے آنا' WHERE id = 'NS:TO:TO_FACE_APPEAR_IN_FRONT_OF';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'سانپ' WHERE id = 'NS:SNAKE:SNAKE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'سچ' WHERE id = 'NS:TRUTH:TRUTH';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'شاخ' WHERE id = 'NS:BRANCH:BRANCH';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'شک و شبہ' WHERE id = 'NS:DOUBT:DOUBT_SUSPICION';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'شکل و صورت' WHERE id = 'NS:SHAPE:SHAPE_FIGURE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'شکل و صورت بنانا' WHERE id = 'NS:GIVE:GIVE_SHAPE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'شگاف' WHERE id = 'NS:SPLIT:SPLIT';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'شہر' WHERE id = 'NS:TOWN:TOWN_CITY';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'شیشہ' WHERE id = 'NS:GLASS:GLASS';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'شام' WHERE id = 'NS:EVENING:EVENING';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'شائد' WHERE id = 'NS:MAYBE:MAYBE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'شراب' WHERE id = 'NS:BEER:BEER_WINE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'شرمانا' WHERE id = 'NS:TO:TO_BE_SHY';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'شروع کرنا' WHERE id = 'NS:TO:TO_START';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'شرمگاہ' WHERE id = 'NS:PRIVATE:PRIVATE_PART';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'شریک' WHERE id = 'NS:ACCOMPLICE:ACCOMPLICE_PARTNER';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'شعلہ' WHERE id = 'NS:FLAME:FLAME';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'تارا [اقسام]' WHERE id = 'NS:STAR:STAR_DIFFERENT_TYPES';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'تراشنا' WHERE id = 'NS:TO:TO_CARVE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'ترکاری' WHERE id = 'NS:VEGETABLES:VEGETABLES';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'تسبیح و تقدیس' WHERE id = 'NS:GLORIFICATION:GLORIFICATION_OF_ALLAH';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'تسکین تسلی' WHERE id = 'NS:PEACE:PEACE_AND_CONSOLATION';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'تعبیر بتلانا' WHERE id = 'NS:TO:TO_INTERPRET';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'تعریف کرنا' WHERE id = 'NS:TO:TO_PRAISE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'تعظیم کرنا' WHERE id = 'NS:TO:TO_HONOUR_RESPECT';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'تک' WHERE id = 'NS:TO:TO_UNTIL';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'تکلیف' WHERE id = 'NS:TROUBLE:TROUBLE_DIFFICULTY_HARDSHIP';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'تکلیف دینا - اٹھانا' WHERE id = 'NS:TO:TO_TROUBLE_TO_ENDURE_HARDSHIP';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'تاریکی چھانا' WHERE id = 'NS:SPREAD:SPREAD_OF_DARKNESS';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'تنگدستی' WHERE id = 'NS:POOR:POOR_DESTITUTE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'تنگی' WHERE id = 'NS:HARDSHIP:HARDSHIP';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'ٹوٹنا' WHERE id = 'NS:TO:TO_BREAK';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'توفیق دینا-' WHERE id = 'NS:TO:TO_GIVE_DIVINE_HELP';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'تہ بہ تہ' WHERE id = 'NS:LAYERED:LAYERED';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'تھکنا ]' WHERE id = 'NS:TO:TO_GET_TIRED';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'تھمنا [رکنا]' WHERE id = 'NS:STOP:STOP';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'تھوڑا' WHERE id = 'NS:LESS:LESS';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'تازہ' WHERE id = 'NS:FRESH:FRESH';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'تیار کرنا' WHERE id = 'NS:TO:TO_PREPARE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'تیر' WHERE id = 'NS:ARROW:ARROW';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'تیز' WHERE id = 'NS:SHARP:SHARP';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'تیل' WHERE id = 'NS:OIL:OIL';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'تیوری چڑھانا' WHERE id = 'NS:SCOWL:SCOWL_FROWN';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'تاکہ – تاکہ نہ' WHERE id = 'NS:SO:SO_THAT_SO_NOT';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'تانبا' WHERE id = 'NS:COPPER:COPPER';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'تختہ' WHERE id = 'NS:PLANK:PLANK_OF_WOOD_A_BOARD';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'تدبیر –تدبیر کرنا' WHERE id = 'NS:PLOT:PLOT_TO_PLOT';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'ترازو' WHERE id = 'NS:SCALES:SCALES';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'ثابت ہونا' WHERE id = 'NS:PROVEN:PROVEN';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'ثابت قدم رہنا  رکھنا' WHERE id = 'NS:TO:TO_BE_STEADFAST';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'ٹکڑا' WHERE id = 'NS:PIECE:PIECE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'ٹیلہ اور اسکی اقسام' WHERE id = 'NS:HILL:HILL_AND_TYPES';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'ٹیڑھ  ٹیڑھا ہونا' WHERE id = 'NS:CROOKED:CROOKED_TO_BE_BENT';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'ٹیک لگانا' WHERE id = 'NS:TO:TO_LEAN_AGAINST_SOMETHING';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'وافر- بہت' WHERE id = 'NS:PLENTIFUL:PLENTIFUL';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'وراثت' WHERE id = 'NS:INHERITANCE:INHERITANCE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'یا' WHERE id = 'NS:OR:OR';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'یاد کرنا – آنا - رکھنا' WHERE id = 'NS:TO:TO_REMEMBER';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'یقین کرنا' WHERE id = 'NS:TO:TO_BELIEF_TO_HAVE_FAITH';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'یکسو ہونا' WHERE id = 'NS:TO:TO_HAVE_COMPLETE_DEVOTION';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'زائد' WHERE id = 'NS:SURPLUS:SURPLUS';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'زینت' WHERE id = 'NS:ELEGANCE:ELEGANCE_BEAUTY_ORNAMENTS';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'زبردستی کرنا' WHERE id = 'NS:TO:TO_FORCE';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'زخم' WHERE id = 'NS:WOUND:WOUND_GASH';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'زمانہ' WHERE id = 'NS:PERIOD:PERIOD_OF_TIME';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'زمین اور اسکی اقسام' WHERE id = 'NS:EARTH:EARTH_AND_ITS_VARIETIES';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'زمین بوس ہونا – کرنا' WHERE id = 'NS:SINK:SINK_COLLAPSE_INTO_THE_EARTH';
UPDATE ar_ling_near_synonym_sets SET canonical_ur = 'زنجیریں' WHERE id = 'NS:CHAINS:CHAINS';
