-- ═══════════════════════════════════════════════════════════════════════════
-- K-MAPS  km_worldview — Arjana Ch.1 reading sessions (content + illustration links)
-- File : database/seeds/seed-wv-arjana-mwi-reading-sessions.sql
-- DB   : km_worldview   (binding: DB_WV)
-- Run  : wrangler d1 execute km_worldview --file=... --remote
--
-- Chapter 1 (sru-arjana-mwi-ch1) is split into two reading sessions. Each gets a
-- clean title and an executive summary that covers all of its concepts, plus a
-- major_points list (the concept titles). The chapter's 13 concept illustrations
-- are linked to their session: orders 1-7 → Session 1, orders 8-13 → Session 2.
-- ═══════════════════════════════════════════════════════════════════════════

-- Session 1 — Orientalism / the theoretical apparatus (concepts 1-7)
UPDATE wv_reading_sessions
   SET title = 'Session 1 · The Orientalist Apparatus',
       summary_md = 'How the Western imagination manufactures the Muslim monster. Orientalism is not one idea but five overlapping registers — a colonial language, a classification system, an artistic movement, an academic discipline, and an attitude — that together authenticate the fantasy rather than invent it. The discourse works in three layers and migrates from open polemic into the authority of scholarship: philology hardens cultural difference into a quasi-biological subspecies placed outside modernity. The imagined Muslim is then split into a gendered double image — the threatening male and the eroticised female — an ambivalence in which revulsion and desire for the monster coexist.',
       meta_json = '{"blocks":52,"nodes":44,"edges":81,"clusters":3,"timeline_events":10,"evidence":6,"questions":4,"claims":5,"highlights":3,"notes":1,"body_text":"pending_pdf_ingest","major_points":["Orientalism is five things at once","It authenticates — it does not invent","Three layers, not one","From polemic to “scholarship”","Philology → subspecies → outside modernity","The gendered double image","Desiring the monster"],"paraphrase_md":"Arjana opens by refusing a single, tidy definition of Orientalism. She treats it as five things working at once — a colonial language, a system for classifying peoples, an artistic movement, an academic discipline, and a general attitude toward the world. What matters is the combination: braided together, these registers do not so much invent the Muslim as authenticate a figure the West has already imagined. Orientalism supplies the citations, the vocabulary, and the air of objectivity that make the fantasy feel like knowledge.\n\nThis authority is layered rather than flat. Beneath the surface of polite scholarship sit older strata of theological polemic and popular fear; the discourse carries all three layers at once, which is why a single image of the Muslim can feel both ancient and modern, both learned and lurid.\n\nArjana tracks how openly hostile polemic is laundered over time into the language of “scholarship.” Claims that began as religious denunciation are restated as neutral description, so that contempt acquires the prestige of method and the monster gains a footnote.\n\nThe decisive move is philological. By treating language families as proxies for human types, nineteenth-century scholarship hardens cultural difference into something like biology: the Muslim becomes a fixed subspecies, placed permanently outside modernity and assumed incapable of change. Difference is no longer historical but essential.\n\nFinally, the imagined Muslim is gendered into a double image. The male is rendered as a threat — violent, fanatical, hypersexual — while the female is rendered as veiled mystery to be unveiled and possessed. The two images share one structure: both invite the Western gaze. Revulsion and desire are not opposites here but partners, and the monster becomes something the imagination both fears and wants to look at.\n\n(Paraphrase for reference — verbatim chapter text pending PDF ingest.)"}',
       updated_at = '2026-05-31T00:00:00Z'
 WHERE id = 'rs-arjana-mwi-ch1';

-- Session 2 — teratology / the logic of the monster (concepts 8-13)
UPDATE wv_reading_sessions
   SET title = 'Session 2 · The Logic of the Monster',
       summary_md = 'From Orientalism to teratology — the logic of monsters themselves. Monsters police the boundary of the human: naming what is not-human is how a culture defines what counts as human. Arjana ranges the threatening other along a spectrum from the almost-human, through the monster, to the alien, and reads monster-making as scapegoating that discharges collective anxiety onto a single figure. She traces the classical and medieval roots of the trope — including the recurring conflation of Jew and Muslim — and the shift from a pre-modern world of fixed monstrous races to the mobile, shape-shifting Gothic monster. It closes by defining the monster with and beyond David Gilmore: a culturally made embodiment of dread.',
       meta_json = '{"intent":"First read-through; capture highlights and notes on the Muslim-monster trope and Orientalism.","major_points":["Teratology: monsters draw the human boundary","The almost human, the monster, the alien","Monster-making as scapegoating","Classical roots & the Jewish-Muslim conflation","Pre-modern fixity → Gothic mobility","Defining the monster: Gilmore and beyond"],"paraphrase_md":"Arjana turns from Orientalism to teratology, the study of monsters. Monsters, she argues, are boundary-markers: by naming what is not human, a culture quietly defines what counts as human. The monster is therefore never only about the creature — it is about us, and about the line we are drawing.\n\nShe arranges the threatening other along a spectrum that runs from the almost-human, through the monster, to the wholly alien. Where a figure sits on that scale measures how much kinship a culture is willing to grant it — and the Muslim is repeatedly pushed toward the monstrous end.\n\nMaking monsters is a form of scapegoating. Collective anxieties — about violence, sexuality, contamination, and change — are gathered up and discharged onto a single figure who can then be feared, expelled, or destroyed. The monster absorbs what a society cannot face in itself.\n\nThese patterns are old. Arjana traces classical and medieval roots, including the persistent conflation of Jew and Muslim, in which two distinct peoples are folded into one composite enemy and made to share the same monstrous attributes.\n\nShe also marks a shift in form. The pre-modern world catalogued fixed monstrous races at the edges of the map; the modern Gothic, by contrast, gives us a mobile, shape-shifting monster that crosses borders and passes among us — a change that makes the imagined Muslim feel like an internal as well as an external danger.\n\nTo anchor the argument she works with and beyond David Gilmore’s account of monsters, defining the monster as a culturally manufactured embodiment of dread — not a natural fact but something a society builds, again and again, to hold its fears.\n\n(Paraphrase for reference — verbatim chapter text pending PDF ingest.)"}',
       updated_at = '2026-05-31T00:00:00Z'
 WHERE id = 'wvrs-arjana-mwi-001';

-- Link concept illustrations to their reading session.
UPDATE wv_source_unit_illustrations
   SET reading_session_id = 'rs-arjana-mwi-ch1', updated_at = '2026-05-31T00:00:00Z'
 WHERE source_unit_id = 'sru-arjana-mwi-ch1' AND order_index BETWEEN 1 AND 7;

UPDATE wv_source_unit_illustrations
   SET reading_session_id = 'wvrs-arjana-mwi-001', updated_at = '2026-05-31T00:00:00Z'
 WHERE source_unit_id = 'sru-arjana-mwi-ch1' AND order_index BETWEEN 8 AND 13;
