-- Auto-generated worldview flow seed
-- Seed type: wv_full_flow_seed
-- Version: 1
-- Source: database/data/worldview/wv_reading_seed.muslims_western_imagination.json

PRAGMA foreign_keys = ON;

INSERT INTO workspaces (id, canonical_input, slug, title, description, workspace_type, owner_user_id, status, settings_json, meta_json) VALUES ('ws_worldview', 'workspace:ws_worldview', 'worldview', 'Worldview Library', 'Personal worldview reading, highlighting, note-making, and distillation library.', 'personal', 1, 'active', '{}', '{"seed_type":"wv_full_flow_seed","seed_version":1,"origin":"seed-worldview-flow"}') ON CONFLICT(id) DO UPDATE SET canonical_input = excluded.canonical_input, slug = excluded.slug, title = excluded.title, description = excluded.description, workspace_type = excluded.workspace_type, owner_user_id = excluded.owner_user_id, status = excluded.status, settings_json = excluded.settings_json, meta_json = excluded.meta_json, updated_at = datetime('now');
INSERT INTO workspace_members (workspace_id, user_id, membership_role, status, settings_json, meta_json) VALUES ('ws_worldview', 1, 'owner', 'active', '{}', '{"seed_type":"wv_full_flow_seed","seed_version":1,"origin":"seed-worldview-flow"}') ON CONFLICT(workspace_id, user_id) DO UPDATE SET membership_role = excluded.membership_role, status = excluded.status, settings_json = excluded.settings_json, meta_json = excluded.meta_json, updated_at = datetime('now');
INSERT INTO workspace_groups (id, canonical_input, workspace_id, title, slug, group_type, description, status, order_index, settings_json, meta_json) VALUES ('grp_orientalism', 'workspace_group:ws_worldview:grp_orientalism', 'ws_worldview', 'Orientalism & the Western Imagination', 'orientalism', 'general', 'Sources on how Islam and Muslims are represented in Western thought and culture.', 'active', 1, '{}', '{"seed_type":"wv_full_flow_seed","seed_version":1,"origin":"seed-worldview-flow"}') ON CONFLICT(id) DO UPDATE SET canonical_input = excluded.canonical_input, workspace_id = excluded.workspace_id, title = excluded.title, slug = excluded.slug, group_type = excluded.group_type, description = excluded.description, status = excluded.status, order_index = excluded.order_index, settings_json = excluded.settings_json, meta_json = excluded.meta_json, updated_at = datetime('now');
INSERT INTO workspace_group_members (workspace_id, group_id, user_id, status) VALUES ('ws_worldview', 'grp_orientalism', 1, 'active') ON CONFLICT(workspace_id, group_id, user_id) DO UPDATE SET status = excluded.status, updated_at = datetime('now');

-- wv_sources
INSERT INTO wv_sources (id, canonical_input, workspace_id, group_id, user_id, source_type, title, subtitle, description, creator, publisher, publication_year, language, source_url, source_ref, status, source_json, meta_json) VALUES ('wv_src_mwi', 'wv_source:book:muslims-western-imagination', 'ws_worldview', 'grp_orientalism', 1, 'book', 'Muslims in the Western Imagination', NULL, 'Examines the long history of Western imaginings of Muslims as monsters and outsiders, tracing recurring figures from the medieval period through to the present. Read for the worldview library to extract highlights, notes, and distillations on Orientalism and Western representation of Islam.', 'Sophia Rose Arjana', 'Oxford University Press', 2015, 'en', 'https://global.oup.com/academic/product/muslims-in-the-western-imagination-9780199324927', 'ISBN 9780199324927', 'active', '{"source_kind":"book","isbn13":"9780199324927","place_of_publication":"New York","edition":"1st","themes":["orientalism","western-imagination","representation","islamophobia","monster-theory"]}', '{"reading_status":"in_progress","started_on":"2026-05-31","origin":"reading-session-seed"}') ON CONFLICT(id) DO UPDATE SET canonical_input = excluded.canonical_input, workspace_id = excluded.workspace_id, group_id = excluded.group_id, user_id = excluded.user_id, source_type = excluded.source_type, title = excluded.title, subtitle = excluded.subtitle, description = excluded.description, creator = excluded.creator, publisher = excluded.publisher, publication_year = excluded.publication_year, language = excluded.language, source_url = excluded.source_url, source_ref = excluded.source_ref, status = excluded.status, source_json = excluded.source_json, meta_json = excluded.meta_json, updated_at = datetime('now');

-- wv_people
INSERT INTO wv_people (id, canonical_input, workspace_id, group_id, user_id, display_name, sort_name, person_type, bio_short, website_url, meta_json) VALUES ('wv_person_arjana', 'wv_person:sophia-rose-arjana', 'ws_worldview', 'grp_orientalism', 1, 'Sophia Rose Arjana', 'Arjana, Sophia Rose', 'author', 'Scholar of Islamic studies whose work addresses Muslims in Western culture, monster theory, and pilgrimage.', NULL, '{}') ON CONFLICT(id) DO UPDATE SET canonical_input = excluded.canonical_input, workspace_id = excluded.workspace_id, group_id = excluded.group_id, user_id = excluded.user_id, display_name = excluded.display_name, sort_name = excluded.sort_name, person_type = excluded.person_type, bio_short = excluded.bio_short, website_url = excluded.website_url, meta_json = excluded.meta_json, updated_at = datetime('now');

-- wv_source_people
INSERT INTO wv_source_people (id, canonical_input, workspace_id, group_id, user_id, source_id, person_id, role, order_index, is_primary, note, meta_json) VALUES ('wv_sp_mwi_arjana', 'wv_source_person:mwi:arjana', 'ws_worldview', 'grp_orientalism', 1, 'wv_src_mwi', 'wv_person_arjana', 'author', 1, 1, NULL, '{}') ON CONFLICT(id) DO UPDATE SET canonical_input = excluded.canonical_input, workspace_id = excluded.workspace_id, group_id = excluded.group_id, user_id = excluded.user_id, source_id = excluded.source_id, person_id = excluded.person_id, role = excluded.role, order_index = excluded.order_index, is_primary = excluded.is_primary, note = excluded.note, meta_json = excluded.meta_json, updated_at = datetime('now');

-- wv_reading_sessions
INSERT INTO wv_reading_sessions (id, canonical_input, workspace_id, group_id, user_id, source_id, source_unit_id, session_type, started_at, ended_at, focus_mode, last_position, status, session_json, meta_json) VALUES ('wv_read_mwi_001', 'wv_reading_session:mwi:001', 'ws_worldview', 'grp_orientalism', 1, 'wv_src_mwi', NULL, 'reading', '2026-05-31 09:00:00', NULL, 'deep_read', NULL, 'active', '{"tabs_flow":["overview","read","highlights","notes","distill"],"distill_ready":false,"intent":"First read-through of Muslims in the Western Imagination; capture highlights and notes, then distill themes on Orientalism and Western representation of Islam."}', '{"reading_status":"in_progress"}') ON CONFLICT(id) DO UPDATE SET canonical_input = excluded.canonical_input, workspace_id = excluded.workspace_id, group_id = excluded.group_id, user_id = excluded.user_id, source_id = excluded.source_id, source_unit_id = excluded.source_unit_id, session_type = excluded.session_type, started_at = excluded.started_at, ended_at = excluded.ended_at, focus_mode = excluded.focus_mode, last_position = excluded.last_position, status = excluded.status, session_json = excluded.session_json, meta_json = excluded.meta_json, updated_at = datetime('now');
