-- Canonical timeline events for Arjana Introduction. Idempotent. Applied live 2026-05-31.
-- Canonical timeline events (eras as ranges + dated incidents)
INSERT OR REPLACE INTO wv_timeline_events (id,title,event_type,year_exact,year_start,year_end,century,significance,meta_json) VALUES
  ('wv-tl-arjana-era-medieval','Medieval (8th–15th c.)','era',NULL,700,1500,8,NULL,json('{"source_id":"src-arjana-muslims-western-imagination-2015","source_unit_id":"sru-arjana-mwi-intro","era":"medieval","order":1}')),
  ('wv-tl-arjana-era-renaissance','Renaissance / Elizabethan','era',NULL,1450,1650,15,NULL,json('{"source_id":"src-arjana-muslims-western-imagination-2015","source_unit_id":"sru-arjana-mwi-intro","era":"renaissance","order":2}')),
  ('wv-tl-arjana-era-americas','The Americas / colonial','era',NULL,1492,1800,15,NULL,json('{"source_id":"src-arjana-muslims-western-imagination-2015","source_unit_id":"sru-arjana-mwi-intro","era":"americas","order":3}')),
  ('wv-tl-arjana-era-orientalist','Orientalism & Gothic (18th–19th c.)','era',NULL,1700,1900,18,NULL,json('{"source_id":"src-arjana-muslims-western-imagination-2015","source_unit_id":"sru-arjana-mwi-intro","era":"orientalist","order":4}')),
  ('wv-tl-arjana-era-sept11','September 11 & after','era',NULL,2001,2010,21,NULL,json('{"source_id":"src-arjana-muslims-western-imagination-2015","source_unit_id":"sru-arjana-mwi-intro","era":"sept11","order":5}')),
  ('wv-tl-arjana-inc-622-0','Rise of Islam','incident',622,NULL,NULL,7,NULL,json('{"source_id":"src-arjana-muslims-western-imagination-2015","source_unit_id":"sru-arjana-mwi-intro","era":"medieval","kind":"spine"}')),
  ('wv-tl-arjana-inc-800-1','First Muslim monsters in Christian texts','incident',800,NULL,NULL,9,NULL,json('{"source_id":"src-arjana-muslims-western-imagination-2015","source_unit_id":"sru-arjana-mwi-intro","era":"medieval","kind":"spine"}')),
  ('wv-tl-arjana-inc-1453-2','Fall of Constantinople','incident',1453,NULL,NULL,15,NULL,json('{"source_id":"src-arjana-muslims-western-imagination-2015","source_unit_id":"sru-arjana-mwi-intro","era":"renaissance","kind":"spine"}')),
  ('wv-tl-arjana-inc-1492-3','Conquest of the Americas','incident',1492,NULL,NULL,15,NULL,json('{"source_id":"src-arjana-muslims-western-imagination-2015","source_unit_id":"sru-arjana-mwi-intro","era":"americas","kind":"spine"}')),
  ('wv-tl-arjana-inc-1785-4','Barbary corsair panic','incident',1785,NULL,NULL,18,NULL,json('{"source_id":"src-arjana-muslims-western-imagination-2015","source_unit_id":"sru-arjana-mwi-intro","era":"americas","kind":"spine"}')),
  ('wv-tl-arjana-inc-2001-5','September 11 attacks','incident',2001,NULL,NULL,21,NULL,json('{"source_id":"src-arjana-muslims-western-imagination-2015","source_unit_id":"sru-arjana-mwi-intro","era":"sept11","kind":"modern"}')),
  ('wv-tl-arjana-inc-2001-6','Invasion of Afghanistan','incident',2001,NULL,NULL,21,NULL,json('{"source_id":"src-arjana-muslims-western-imagination-2015","source_unit_id":"sru-arjana-mwi-intro","era":"sept11","kind":"modern"}')),
  ('wv-tl-arjana-inc-2002-7','Guantanamo Bay opens','incident',2002,NULL,NULL,21,NULL,json('{"source_id":"src-arjana-muslims-western-imagination-2015","source_unit_id":"sru-arjana-mwi-intro","era":"sept11","kind":"modern"}')),
  ('wv-tl-arjana-inc-2003-8','Invasion of Iraq','incident',2003,NULL,NULL,21,NULL,json('{"source_id":"src-arjana-muslims-western-imagination-2015","source_unit_id":"sru-arjana-mwi-intro","era":"sept11","kind":"modern"}')),
  ('wv-tl-arjana-inc-2004-9','Abu Ghraib photographs','incident',2004,NULL,NULL,21,NULL,json('{"source_id":"src-arjana-muslims-western-imagination-2015","source_unit_id":"sru-arjana-mwi-intro","era":"sept11","kind":"modern"}')),
  ('wv-tl-arjana-inc-2004-10','Madrid bombings','incident',2004,NULL,NULL,21,NULL,json('{"source_id":"src-arjana-muslims-western-imagination-2015","source_unit_id":"sru-arjana-mwi-intro","era":"sept11","kind":"modern"}')),
  ('wv-tl-arjana-inc-2005-11','London 7/7 bombings','incident',2005,NULL,NULL,21,NULL,json('{"source_id":"src-arjana-muslims-western-imagination-2015","source_unit_id":"sru-arjana-mwi-intro","era":"sept11","kind":"modern"}')),
  ('wv-tl-arjana-inc-2009-12','Swiss minaret ban','incident',2009,NULL,NULL,21,NULL,json('{"source_id":"src-arjana-muslims-western-imagination-2015","source_unit_id":"sru-arjana-mwi-intro","era":"sept11","kind":"modern"}'));
