import { HubCard } from '../models/hub.models';

export const ARABIC_CARDS: HubCard[] = [
  {
    id: 'containers',
    icon: '📚',
    glyph: 'ك',
    title: 'Content Library',
    description: 'Books, poems, podcast transcripts — all Arabic literature containers.',
    table: 'ar_containers',
    route: 'containers',
    panelMode: 'ar-container',
    countKey: 'containers',
    tag: 'LIBRARY',
    accentColor: '#8a3a1a',
  },
  {
    id: 'units',
    icon: '📑',
    glyph: 'ف',
    title: 'Units & Chapters',
    description: 'Chapters and sections within each Arabic content container.',
    table: 'ar_container_units',
    route: 'units',
    panelMode: 'ar-unit',
    countKey: 'container_units',
    tag: 'CONTENT',
    accentColor: '#8a3a1a',
  },
  {
    id: 'tasks',
    icon: '✅',
    glyph: '✓',
    title: 'Tasks',
    description: 'Reading, vocab, comprehension and grammar tasks across all units.',
    table: 'ar_container_unit_task',
    route: 'tasks',
    panelMode: 'ar-task',
    countKey: 'tasks',
    tag: 'LEARNING',
    accentColor: '#8a3a1a',
  },
  {
    id: 'grammar',
    icon: '⚙️',
    glyph: 'ن',
    title: 'Grammar',
    description: 'Arabic grammar concepts — nahw, sarf, irab with Quranic examples.',
    table: 'ar_grammar_concepts',
    route: 'grammar',
    panelMode: 'ar-grammar',
    countKey: 'grammar',
    tag: 'LINGUISTICS',
    accentColor: '#8a3a1a',
  },
  {
    id: 'balagha',
    icon: '✨',
    glyph: 'بـ',
    title: 'Balagha',
    description: 'Arabic rhetoric — Bayan, Maani, Badi with Quranic examples.',
    table: 'ar_balagha',
    route: 'balagha',
    panelMode: 'ar-balagha',
    countKey: 'balagha',
    tag: 'RHETORIC',
    accentColor: '#8a3a1a',
    badge: 'NEW',
  },
  {
    id: 'domains',
    icon: '🗺️',
    glyph: 'م',
    title: 'Domains',
    description: 'Context-specific vocabulary — home, market, mosque, travel and more.',
    table: 'ar_domain',
    route: 'domains',
    panelMode: 'ar-domain',
    countKey: 'domains',
    tag: 'VOCABULARY',
    accentColor: '#8a3a1a',
    badge: 'NEW',
  },
  {
    id: 'vocab',
    icon: '📝',
    glyph: 'ع',
    title: 'Vocabulary',
    description: 'Arabic root lexicon and vocabulary cards for spaced repetition.',
    table: 'ar_u_roots',
    route: 'vocab',
    panelMode: 'ar-vocab',
    tag: 'LEXICON',
    accentColor: '#8a3a1a',
  },
  {
    id: 'srs',
    icon: '🔁',
    glyph: '↻',
    title: 'Arabic SRS',
    description: 'Spaced repetition queue for Arabic vocabulary, grammar, and phrases.',
    table: 'km_srs',
    route: 'arabic-srs',
    panelMode: 'ar-srs',
    countKey: 'srs',
    tag: 'REVIEW',
    accentColor: '#8a3a1a',
  },
];
