import { HubCard } from '../models/hub.models';

export const WORKSPACE_CARDS: HubCard[] = [
  {
    id: 'workspaces',
    icon: '🏢',
    glyph: '⊞',
    title: 'Workspaces',
    description: 'Collaborative project containers shared with friends and colleagues.',
    table: 'workspaces',
    route: 'workspaces',
    panelMode: 'workspace',
    countKey: 'workspaces',
    tag: 'PROJECTS',
    accentColor: '#3a1a6e',
  },
  {
    id: 'members',
    icon: '👤',
    glyph: '⊕',
    title: 'Members',
    description: 'Workspace members — non-private contacts who collaborate on projects.',
    table: 'wv_workspace_person',
    route: 'members',
    panelMode: 'ws-member',
    tag: 'PEOPLE',
    accentColor: '#3a1a6e',
  },
  {
    id: 'docs',
    icon: '📄',
    glyph: '◻',
    title: 'Documents',
    description: 'Workspace documents — scripts, outlines, and research docs.',
    table: 'wv_documents',
    route: 'docs',
    panelMode: 'ws-doc',
    tag: 'CONTENT',
    accentColor: '#3a1a6e',
  },
  {
    id: 'activity',
    icon: '📊',
    glyph: '▸',
    title: 'Activity',
    description: 'Recent workspace activity log — actions, contributions, and changes.',
    table: 'wv_activity',
    route: 'activity',
    panelMode: 'ws-activity',
    tag: 'AUDIT',
    accentColor: '#3a1a6e',
  },
];
