import { HubCard } from '../models/hub.models';

export const QURAN_CARDS: HubCard[] = [
  {
    id: 'surahs',
    icon: '☽',
    glyph: '☽',
    title: 'Surahs',
    description: 'Browse and manage all 114 Surahs with metadata, ayah counts, and classification.',
    table: 'ar_quran_surah',
    route: 'surahs',
    panelMode: 'surah',
    countKey: 'surahs',
    tag: 'SCRIPTURE',
    accentColor: '#1a6e3a',
  },
  {
    id: 'passages',
    icon: '📖',
    glyph: '§',
    title: 'Passages',
    description: 'Translation passages — thematic groupings of ayahs with source references.',
    table: 'ar_quran_surah_passage',
    route: 'passages',
    panelMode: 'passage',
    countKey: 'passages',
    tag: 'TAFSIR',
    accentColor: '#1a6e3a',
  },
  {
    id: 'notes',
    icon: '✏️',
    glyph: '✎',
    title: 'Surah Notes',
    description: 'Scholarly annotations and thematic notes attached to specific Surahs.',
    table: 'wv_notes',
    route: 'notes',
    panelMode: 'surah-note',
    countKey: 'notes',
    tag: 'ANNOTATION',
    accentColor: '#1a6e3a',
  },
  {
    id: 'srs',
    icon: '🔁',
    glyph: '↻',
    title: 'SRS Queue',
    description: 'Spaced repetition review queue — ayahs due for memorisation review.',
    table: 'km_srs',
    route: 'srs',
    panelMode: 'ar-srs',
    countKey: 'srs',
    tag: 'MEMORISATION',
    accentColor: '#1a6e3a',
  },
  {
    id: 'highlights',
    icon: '🌟',
    glyph: '★',
    title: 'Highlights',
    description: 'Highlighted ayahs and passages with personal notes and colour coding.',
    table: 'wv_highlights',
    route: 'highlights',
    panelMode: 'wv-highlight',
    countKey: 'highlights',
    tag: 'STUDY',
    accentColor: '#1a6e3a',
  },
];
