export interface QrIrabBookEntry {
  id: string;
  source_id: string | null;
  source_slug: string;
  source_title: string | null;
  ayah_key: string;
  group_ayah_key: string | null;
  from_ayah: string | null;
  to_ayah: string | null;
  ayah_keys: string | null;
  surah: number | null;
  ayah_from: number | null;
  ayah_to: number | null;
  entry_html: string | null;
  irab_text: string | null;
  source_chunk_id: string | null;
  entry_order: number | null;
  source_quote_ar: string | null;
  source_quote_hash: string;
  irab_text_ar: string | null;
  target_text_ar: string | null;
  target_text_bare: string | null;
  target_text_match_key: string | null;
  grammar_role_ar: string | null;
  grammar_role_norm: string | null;
  grammar_case_ar: string | null;
  mahal_ar: string | null;
  grammar_concept_ref: string | null;
  syntax_relation_ref: string | null;
  case_concept_ref: string | null;
  mahal_concept_ref: string | null;
  alternative_json: string | null;
  inline_note_ar: string | null;
  raw_annotation_ar: string | null;
  word_occurrence_id: string | null;
  word_link_status: string | null;
  word_link_note: string | null;
  promotion_candidate_json: string | null;
  al_mapping_status: string | null;
  al_mapping_confidence: number | null;
  al_mapping_note: string | null;
  created_at: string;
  updated_at: string;
}

export interface QrIrabSourceChunk {
  id: string;
  extraction_run_id: string | null;
  source_id: string | null;
  source_slug: string;
  source_record_id: string | null;
  ayah_key: string | null;
  group_ayah_key: string | null;
  from_ayah: string | null;
  to_ayah: string | null;
  ayah_keys: string | null;
  surah: number | null;
  ayah_from: number | null;
  ayah_to: number | null;
  section_kind: string;
  section_order: number;
  content_format: 'html' | 'text' | 'openiti_markdown' | 'json';
  raw_html: string | null;
  raw_text: string | null;
  clean_text: string | null;
  source_record_json: string | null;
  created_at: string;
  updated_at: string;
}
