import { HubCard } from '../models/hub.models';

export const WORLDVIEW_CARDS: HubCard[] = [
  {
    id: 'worldviews',
    icon: '🌍',
    glyph: '◎',
    title: 'Worldviews',
    description: 'Worldview registry — Islam, Christianity, Judaism and their branches.',
    table: 'wv_worldview',
    route: 'worldviews',
    panelMode: 'wv-worldview',
    countKey: 'worldviews',
    tag: 'REGISTRY',
    accentColor: '#1a3a6e',
  },
  {
    id: 'topics',
    icon: '🏷️',
    glyph: '⊛',
    title: 'Topics',
    description: 'Research topics for comparison and brainstorm organisation.',
    table: 'wv_topic',
    route: 'topics',
    panelMode: 'wv-topic',
    countKey: 'topics',
    tag: 'RESEARCH',
    accentColor: '#1a3a6e',
  },
  {
    id: 'sources',
    icon: '📖',
    glyph: '§',
    title: 'Sources',
    description: 'Books, articles, and media ingested into the knowledge base.',
    table: 'wv_sources',
    route: 'sources',
    panelMode: 'wv-source',
    countKey: 'sources',
    tag: 'LIBRARY',
    accentColor: '#1a3a6e',
  },
  {
    id: 'source-units',
    icon: '📑',
    glyph: '¶',
    title: 'Source Units',
    description: 'Chapters and sections within each source — granular reading units.',
    table: 'wv_source_units',
    route: 'source-units',
    panelMode: 'wv-source-unit',
    countKey: 'source_units',
    tag: 'CONTENT',
    accentColor: '#1a3a6e',
  },
  {
    id: 'highlights',
    icon: '🌟',
    glyph: '★',
    title: 'Highlights',
    description: 'Key passages highlighted from reading — the raw material of insight.',
    table: 'wv_highlights',
    route: 'wv-highlights',
    panelMode: 'wv-highlight',
    countKey: 'highlights',
    tag: 'READING',
    accentColor: '#1a3a6e',
  },
  {
    id: 'notes',
    icon: '✏️',
    glyph: '✎',
    title: 'Notes',
    description: 'Personal notes, reflections, and distillations from all sources.',
    table: 'wv_notes',
    route: 'wv-notes',
    panelMode: 'wv-note',
    countKey: 'notes',
    tag: 'INSIGHTS',
    accentColor: '#1a3a6e',
  },
  {
    id: 'brainstorm',
    icon: '💡',
    glyph: '⚡',
    title: 'Brainstorm',
    description: 'Free-form research journal sessions — unstructured idea capture.',
    table: 'wv_brainstorm_session',
    route: 'brainstorm',
    panelMode: 'wv-brainstorm',
    countKey: 'brainstorm',
    tag: 'JOURNAL',
    accentColor: '#1a3a6e',
    badge: 'NEW',
  },
  {
    id: 'comparisons',
    icon: '⚖️',
    glyph: '↔',
    title: 'Comparisons',
    description: 'Side-by-side parallel scripture comparison across traditions.',
    table: 'wv_comparison',
    route: 'comparisons',
    panelMode: 'wv-comparison',
    countKey: 'comparisons',
    tag: 'ANALYSIS',
    accentColor: '#1a3a6e',
    badge: 'NEW',
  },
  {
    id: 'people',
    icon: '👥',
    glyph: '⊕',
    title: 'People',
    description: 'Personal contacts — family and friends with privacy model.',
    table: 'wv_person',
    route: 'people',
    panelMode: 'wv-person',
    countKey: 'people',
    tag: 'NETWORK',
    accentColor: '#1a3a6e',
  },
  {
    id: 'podcasts',
    icon: '🎙️',
    glyph: '◈',
    title: 'Podcasts',
    description: 'Podcast projects with participants, talking points, and structure.',
    table: 'wv_podcast',
    route: 'podcasts',
    panelMode: 'wv-podcast',
    countKey: 'podcasts',
    tag: 'MEDIA',
    accentColor: '#1a3a6e',
    badge: 'NEW',
  },
  {
    id: 'plans',
    icon: '📋',
    glyph: '▣',
    title: 'Reading Plans',
    description: 'Structured reading and research plans with target dates.',
    table: 'wv_plan',
    route: 'plans',
    panelMode: 'wv-plan',
    countKey: 'plans',
    tag: 'PLANNING',
    accentColor: '#1a3a6e',
  },
];
