-- Said, Orientalism — Chapter 1, Section I "Knowing the Oriental"
-- Character / concept map: worldview graph nodes + edges.
-- Target: km_worldview (binding DB_WV). Nodes scoped via data_json.source_unit_id;
-- the reader surfaces them in the Worldview tab and the unit graph page.
--   wrangler d1 execute km_worldview --remote --config workers/worldview/wrangler.toml \
--     --file database/seeds/orientalism/seed-wv-said-orientalism-ch1-s1-graph.sql

INSERT OR REPLACE INTO wv_nodes (id, node_type, title, summary, data_json) VALUES
('wvn-orient-s1-said','thinker','Edward Said','Author of Orientalism; reads Balfour and Cromer to show Orientalism as power-knowledge in operation.','{"source_unit_id":"sru-said-orient-ch1-s1","source_id":"src-said-orientalism-1978","slug":"said"}'),
('wvn-orient-s1-balfour','person','Arthur J. Balfour','Former PM whose 13 June 1910 Commons speech makes knowing Egypt the ground of ruling it; signs the Balfour Declaration in 1917.','{"source_unit_id":"sru-said-orient-ch1-s1","source_id":"src-said-orientalism-1978","slug":"balfour"}'),
('wvn-orient-s1-cromer','person','Lord Cromer','Evelyn Baring, Egypt’s ruler 1882–1907: the knowledge→power dialectic, rule by “contentment,” and the Modern Egypt stereotype catalogue.','{"source_unit_id":"sru-said-orient-ch1-s1","source_id":"src-said-orientalism-1978","slug":"cromer"}'),
('wvn-orient-s1-salisbury','person','Lord Salisbury','“Renounce, monopolize, or share” — Britain resolves to share the Orient with France (1881).','{"source_unit_id":"sru-said-orient-ch1-s1","source_id":"src-said-orientalism-1978","slug":"salisbury"}'),
('wvn-orient-s1-lyall','person','Sir Alfred Lyall','“Accuracy is abhorrent to the Oriental mind” — the maxim Cromer leans on.','{"source_unit_id":"sru-said-orient-ch1-s1","source_id":"src-said-orientalism-1978","slug":"lyall"}'),
('wvn-orient-s1-renan','person','Ernest Renan','Orthodox Orientalist authority; his 1848 Semitic linguistics lends racial-scientific prestige to the essence.','{"source_unit_id":"sru-said-orient-ch1-s1","source_id":"src-said-orientalism-1978","slug":"renan"}'),
('wvn-orient-s1-volney','person','Constantin de Volney','Cited with Renan to explain “why” Orientals are as the catalogue claims.','{"source_unit_id":"sru-said-orient-ch1-s1","source_id":"src-said-orientalism-1978","slug":"volney"}'),
('wvn-orient-s1-kipling','person','Rudyard Kipling','The mock “chain of being” from mule to Viceroy — an order of sovereignty set up East to West.','{"source_unit_id":"sru-said-orient-ch1-s1","source_id":"src-said-orientalism-1978","slug":"kipling"}'),
('wvn-orient-s1-pope','person','Alexander Pope','“The proper study of mankind is Man” — twisted by Cromer to single out Orientals.','{"source_unit_id":"sru-said-orient-ch1-s1","source_id":"src-said-orientalism-1978","slug":"pope"}'),
('wvn-orient-s1-napoleon','person','Napoleon Bonaparte','The 1798 invasion of Egypt and the Description de l’Égypte — scientific appropriation of one culture by another.','{"source_unit_id":"sru-said-orient-ch1-s1","source_id":"src-said-orientalism-1978","slug":"napoleon"}'),
('wvn-orient-s1-kissinger','person','Henry Kissinger','Pre-/post-Newtonian binary — living Orientalism in Cold-War strategy.','{"source_unit_id":"sru-said-orient-ch1-s1","source_id":"src-said-orientalism-1978","slug":"kissinger"}'),
('wvn-orient-s1-glidden','person','Harold W. Glidden','The 1972 psychiatric “Arab World” — Cromer’s catalogue in a 20th-century lab coat.','{"source_unit_id":"sru-said-orient-ch1-s1","source_id":"src-said-orientalism-1978","slug":"glidden"}'),
('wvn-orient-s1-foucault','thinker','Michel Foucault','Discourse and power/knowledge; the author as a function; power that produces its object.','{"source_unit_id":"sru-said-orient-ch1-s1","source_id":"src-said-orientalism-1978","slug":"foucault"}'),
('wvn-orient-s1-gramsci','thinker','Antonio Gramsci','Hegemony and “cultural strength” — leadership by consent.','{"source_unit_id":"sru-said-orient-ch1-s1","source_id":"src-said-orientalism-1978","slug":"gramsci"}'),
('wvn-orient-s1-vico','thinker','Giambattista Vico','Men make their own history; “facts” are made, not found.','{"source_unit_id":"sru-said-orient-ch1-s1","source_id":"src-said-orientalism-1978","slug":"vico"}'),
('wvn-orient-s1-bacon','thinker','Francis Bacon','“Knowledge is power” — the two Baconian themes Balfour fuses.','{"source_unit_id":"sru-said-orient-ch1-s1","source_id":"src-said-orientalism-1978","slug":"bacon"}'),
('wvn-orient-s1-lewis','thinker','Bernard Lewis','Objection: administrators are not scholars; the sample is stacked.','{"source_unit_id":"sru-said-orient-ch1-s1","source_id":"src-said-orientalism-1978","slug":"lewis"}'),
('wvn-orient-s1-irwin','thinker','Robert Irwin','Objection: real philology was often critical and not in colonial service.','{"source_unit_id":"sru-said-orient-ch1-s1","source_id":"src-said-orientalism-1978","slug":"irwin"}'),
('wvn-orient-s1-alazm','thinker','Sadik al-Azm','“Orientalism in Reverse” — Said essentialises “the West.”','{"source_unit_id":"sru-said-orient-ch1-s1","source_id":"src-said-orientalism-1978","slug":"alazm"}'),
('wvn-orient-s1-ahmad','thinker','Aijaz Ahmad','Objection: the colonised remain voiceless in Said’s account too.','{"source_unit_id":"sru-said-orient-ch1-s1","source_id":"src-said-orientalism-1978","slug":"ahmad"}'),
('wvn-orient-s1-power-knowledge','concept','Power / knowledge','To know the Orient is to dominate it — the two operations are one.','{"source_unit_id":"sru-said-orient-ch1-s1","source_id":"src-said-orientalism-1978","slug":"power-knowledge"}'),
('wvn-orient-s1-positional','concept','Positional superiority','The structural upper hand the Westerner keeps in every relation to the Orient.','{"source_unit_id":"sru-said-orient-ch1-s1","source_id":"src-said-orientalism-1978","slug":"positional-superiority"}'),
('wvn-orient-s1-hegemony','concept','Cultural strength / hegemony','Domination that prefers to look like leadership — rule by consent.','{"source_unit_id":"sru-said-orient-ch1-s1","source_id":"src-said-orientalism-1978","slug":"hegemony"}'),
('wvn-orient-s1-imaginative-geo','concept','Imaginative geography','The mind-made line dividing “our” space from “theirs.”','{"source_unit_id":"sru-said-orient-ch1-s1","source_id":"src-said-orientalism-1978","slug":"imaginative-geography"}'),
('wvn-orient-s1-ventriloquism','concept','Representation / ventriloquism','Speaking for the Oriental so he need never — and can never — speak for himself.','{"source_unit_id":"sru-said-orient-ch1-s1","source_id":"src-said-orientalism-1978","slug":"ventriloquism"}'),
('wvn-orient-s1-essentialism','concept','Platonic essence / essentialism','The Oriental as a single, timeless, unchanging type.','{"source_unit_id":"sru-said-orient-ch1-s1","source_id":"src-said-orientalism-1978","slug":"essentialism"}'),
('wvn-orient-s1-circular','claim','The circular syllogism','England knows Egypt → Egypt is what England knows → it cannot self-govern → occupation becomes its “very basis.”','{"source_unit_id":"sru-said-orient-ch1-s1","source_id":"src-said-orientalism-1978","slug":"circular-syllogism"}'),
('wvn-orient-s1-knowledge-creates','thesis','Knowledge creates the Orient','Generated out of strength, knowledge “in a sense creates the Orient.”','{"source_unit_id":"sru-said-orient-ch1-s1","source_id":"src-said-orientalism-1978","slug":"knowledge-creates-orient"}'),
('wvn-orient-s1-in-advance','thesis','Rule justified in advance','Colonial rule is licensed by Orientalism before the fact, not rationalised after it.','{"source_unit_id":"sru-said-orient-ch1-s1","source_id":"src-said-orientalism-1978","slug":"justified-in-advance"}'),
('wvn-orient-s1-four-frameworks','framework','The four dominating frameworks','Court, curriculum, prison, manual — the Oriental is judged, studied, disciplined, illustrated.','{"source_unit_id":"sru-said-orient-ch1-s1","source_id":"src-said-orientalism-1978","slug":"four-frameworks"}'),
('wvn-orient-s1-machine','framework','The embracing machine','A seat of power in the West that processes the East into more power.','{"source_unit_id":"sru-said-orient-ch1-s1","source_id":"src-said-orientalism-1978","slug":"embracing-machine"}'),
('wvn-orient-s1-archive','framework','The archive / library','The shared store of Orientalist “facts” authors draw on and replenish.','{"source_unit_id":"sru-said-orient-ch1-s1","source_id":"src-said-orientalism-1978","slug":"archive"}'),
('wvn-orient-s1-catalogue','evidence','The stereotype catalogue','Modern Egypt ch. 34: illogical, lethargic, liar, “unable to walk on roads or pavements.”','{"source_unit_id":"sru-said-orient-ch1-s1","source_id":"src-said-orientalism-1978","slug":"stereotype-catalogue"}');

INSERT OR REPLACE INTO wv_node_edges (id, from_node_id, to_node_id, relation_type, note, weight) VALUES
('wve-orient-s1-01','wvn-orient-s1-said','wvn-orient-s1-balfour','questions','Said reads Balfour as the discourse speaking',1.0),
('wve-orient-s1-02','wvn-orient-s1-said','wvn-orient-s1-cromer','questions','Said reads Cromer at the administrator’s desk',1.0),
('wve-orient-s1-03','wvn-orient-s1-balfour','wvn-orient-s1-power-knowledge','illustrates','“We know Egypt better”',1.0),
('wve-orient-s1-04','wvn-orient-s1-cromer','wvn-orient-s1-power-knowledge','illustrates','knowledge gives power, power requires knowledge',1.0),
('wve-orient-s1-05','wvn-orient-s1-balfour','wvn-orient-s1-circular','leads_to','the circular syllogism',1.0),
('wve-orient-s1-06','wvn-orient-s1-balfour','wvn-orient-s1-ventriloquism','leads_to','speaks for the Orientals',1.0),
('wve-orient-s1-07','wvn-orient-s1-cromer','wvn-orient-s1-catalogue','leads_to','Modern Egypt ch. 34',1.0),
('wve-orient-s1-08','wvn-orient-s1-cromer','wvn-orient-s1-machine','related_to','the great embracing machine',1.0),
('wve-orient-s1-09','wvn-orient-s1-cromer','wvn-orient-s1-hegemony','illustrates','rule by “contentment”',1.0),
('wve-orient-s1-10','wvn-orient-s1-lyall','wvn-orient-s1-catalogue','supports','“accuracy is abhorrent”',1.0),
('wve-orient-s1-11','wvn-orient-s1-renan','wvn-orient-s1-catalogue','supports','borrowed authority',1.0),
('wve-orient-s1-12','wvn-orient-s1-volney','wvn-orient-s1-catalogue','supports','borrowed authority',1.0),
('wve-orient-s1-13','wvn-orient-s1-catalogue','wvn-orient-s1-essentialism','supports','the fixed essence',1.0),
('wve-orient-s1-14','wvn-orient-s1-circular','wvn-orient-s1-in-advance','supports','manufactures its own justification',1.0),
('wve-orient-s1-15','wvn-orient-s1-power-knowledge','wvn-orient-s1-in-advance','leads_to','justified before the fact',1.0),
('wve-orient-s1-16','wvn-orient-s1-power-knowledge','wvn-orient-s1-knowledge-creates','related_to','knowledge creates the Orient',1.0),
('wve-orient-s1-17','wvn-orient-s1-four-frameworks','wvn-orient-s1-power-knowledge','part_of','court, curriculum, prison, manual',1.0),
('wve-orient-s1-18','wvn-orient-s1-machine','wvn-orient-s1-power-knowledge','illustrates','East processed into power',1.0),
('wve-orient-s1-19','wvn-orient-s1-positional','wvn-orient-s1-hegemony','related_to','the relative upper hand',1.0),
('wve-orient-s1-20','wvn-orient-s1-imaginative-geo','wvn-orient-s1-positional','related_to','the us/them line',1.0),
('wve-orient-s1-21','wvn-orient-s1-foucault','wvn-orient-s1-power-knowledge','supports','the theoretical engine',1.0),
('wve-orient-s1-22','wvn-orient-s1-gramsci','wvn-orient-s1-hegemony','supports','cultural strength',1.0),
('wve-orient-s1-23','wvn-orient-s1-vico','wvn-orient-s1-knowledge-creates','supports','facts are made, not found',1.0),
('wve-orient-s1-24','wvn-orient-s1-bacon','wvn-orient-s1-power-knowledge','supports','the two Baconian themes',1.0),
('wve-orient-s1-25','wvn-orient-s1-salisbury','wvn-orient-s1-archive','leads_to','resolve to share the Orient',1.0),
('wve-orient-s1-26','wvn-orient-s1-napoleon','wvn-orient-s1-archive','leads_to','Description de l’Égypte',1.0),
('wve-orient-s1-27','wvn-orient-s1-archive','wvn-orient-s1-essentialism','supports','regular characteristics',1.0),
('wve-orient-s1-28','wvn-orient-s1-kipling','wvn-orient-s1-machine','illustrates','the chain of being',1.0),
('wve-orient-s1-29','wvn-orient-s1-pope','wvn-orient-s1-power-knowledge','illustrates','the proper study twisted',1.0),
('wve-orient-s1-30','wvn-orient-s1-kissinger','wvn-orient-s1-power-knowledge','illustrates','living Orientalism',1.0),
('wve-orient-s1-31','wvn-orient-s1-glidden','wvn-orient-s1-catalogue','illustrates','the catalogue in a lab coat',1.0),
('wve-orient-s1-32','wvn-orient-s1-lewis','wvn-orient-s1-said','contradicts','administrators are not scholars',1.0),
('wve-orient-s1-33','wvn-orient-s1-irwin','wvn-orient-s1-said','contradicts','philology was self-correcting',1.0),
('wve-orient-s1-34','wvn-orient-s1-alazm','wvn-orient-s1-said','questions','Orientalism in Reverse',1.0),
('wve-orient-s1-35','wvn-orient-s1-ahmad','wvn-orient-s1-said','questions','the colonised still voiceless',1.0);
