-- Said, Orientalism — Chapter 1, Section I "Knowing the Oriental"
-- Timeline events for the worldview reader timeline.
-- Target: km_worldview (binding DB_WV). Scoped via meta_json.source_unit_id.
--   wrangler d1 execute km_worldview --remote --config workers/worldview/wrangler.toml \
--     --file database/seeds/orientalism/seed-wv-said-orientalism-ch1-s1-timeline.sql

INSERT OR REPLACE INTO wv_timeline_events (id, title, event_type, year_exact, year_start, year_end, century, description_md, significance, meta_json) VALUES
('tle-orient-s1-1798-napoleon','Napoleon invades Egypt','incident',1798,NULL,NULL,18,'The keynote of modern Orientalism — “the very model of a truly scientific appropriation of one culture by another.” Spawns the *Description de l’Égypte*.','Egypt becomes “the live province, the laboratory, the theater” of Western knowledge.','{"source_id":"src-said-orientalism-1978","source_unit_id":"sru-said-orient-ch1-s1"}'),
('tle-orient-s1-1809-fundgraben','*Fundgraben des Orients* founded','publication',1809,NULL,NULL,19,'An early Orientalist periodical; Fourier’s 1809 epigraph fuses “genius” with the “instruments of their power.”','Institutional scaffolding of the discourse.','{"source_id":"src-said-orientalism-1978","source_unit_id":"sru-said-orient-ch1-s1"}'),
('tle-orient-s1-era-3585','Colonial dominion: 35% → 85%','era',NULL,1815,1914,19,'European direct colonial dominion grows from about 35% to about 85% of the earth’s surface — the rise of Orientalism “coincides exactly” with this expansion.','Knowledge and empire expand together.','{"source_id":"src-said-orientalism-1978","source_unit_id":"sru-said-orient-ch1-s1"}'),
('tle-orient-s1-1848-renan','Renan’s Semitic linguistics','publication',1848,NULL,NULL,19,'Renan borrows authority from comparative grammar, comparative anatomy, and racial theory — modernised Orientalist science.','Scholarly prestige for the fixed essence.','{"source_id":"src-said-orientalism-1978","source_unit_id":"sru-said-orient-ch1-s1"}'),
('tle-orient-s1-1881-salisbury','Salisbury: “renounce, monopolize, or share”','historical',1881,NULL,NULL,19,'Faced with French rivalry over Egypt, Britain “resolved to share” — land, profit, and the intellectual power Said calls Orientalism.','Anglo-French co-ownership of the Orient.','{"source_id":"src-said-orientalism-1978","source_unit_id":"sru-said-orient-ch1-s1"}'),
('tle-orient-s1-1882-occupation','British occupation of Egypt','incident',1882,NULL,NULL,19,'Britain crushes Colonel Arabi’s nationalist revolt and bombards Alexandria; Cromer becomes Egypt’s “master.”','The occupation Balfour later defends.','{"source_id":"src-said-orientalism-1978","source_unit_id":"sru-said-orient-ch1-s1"}'),
('tle-orient-s1-1885-khartoum','Gordon at Khartoum','incident',1885,NULL,NULL,19,'One of the “overseas crises” that authorize Balfour’s voice.','Imperial backdrop.','{"source_id":"src-said-orientalism-1978","source_unit_id":"sru-said-orient-ch1-s1"}'),
('tle-orient-s1-1898-omdurman','Omdurman & Fashoda','incident',1898,NULL,NULL,19,'Reconquest of the Sudan and the Anglo-French near-collision at Fashoda.','The rivalry Salisbury managed by “sharing.”','{"source_id":"src-said-orientalism-1978","source_unit_id":"sru-said-orient-ch1-s1"}'),
('tle-orient-s1-1906-dinshaway','The Dinshaway incident','incident',1906,NULL,NULL,20,'Floggings and hangings of Egyptian villagers on Cromer’s watch — the real face of his “moral prosperity.”','Helped ignite the nationalism Cromer dismissed as “exotic.”','{"source_id":"src-said-orientalism-1978","source_unit_id":"sru-said-orient-ch1-s1"}'),
('tle-orient-s1-1908-subject-races','Cromer, “The Government of Subject Races”','publication',1908,NULL,NULL,20,'*Edinburgh Review* essay; *Modern Egypt* (ch. 34) supplies the stereotype catalogue, citing Renan and Volney.','Administrator leans on scholar; the loop closes.','{"source_id":"src-said-orientalism-1978","source_unit_id":"sru-said-orient-ch1-s1"}'),
('tle-orient-s1-1910-balfour','Balfour’s Commons speech','speech',1910,NULL,NULL,20,'13 June 1910: “We know Egypt better.” The circular syllogism and ventriloquism in action.','Knowing the Orient *is* ruling it.','{"source_id":"src-said-orientalism-1978","source_unit_id":"sru-said-orient-ch1-s1"}'),
('tle-orient-s1-1917-declaration','The Balfour Declaration','historical',1917,NULL,NULL,20,'Seven years on, Balfour speaks *for* the future of Palestine — the same gesture of authoritative speaking-for.','Why Said opens the book with Balfour.','{"source_id":"src-said-orientalism-1978","source_unit_id":"sru-said-orient-ch1-s1"}'),
('tle-orient-s1-1969-kissinger','Kissinger, “Domestic Structure and Foreign Policy”','publication',1969,NULL,NULL,20,'Pre-/post-Newtonian binary: “We had our Newtonian revolution; they didn’t.”','Living Orientalism in Cold-War strategy.','{"source_id":"src-said-orientalism-1978","source_unit_id":"sru-said-orient-ch1-s1"}'),
('tle-orient-s1-1972-glidden','Glidden, “The Arab World”','publication',1972,NULL,NULL,20,'A four-page, double-columned psychiatric “portrait” of over 100 million people, citing exactly four sources.','Cromer’s catalogue in a 20th-century lab coat.','{"source_id":"src-said-orientalism-1978","source_unit_id":"sru-said-orient-ch1-s1"}');
