#\!/usr/bin/env python3
"""
K-MAPS — Generate root search-key seed
======================================
Reads database/seeds/seed-al-roots.sql, computes:
  • buckwalter      — already in meaning_core_en (QUL english_trilateral)
  • simple_lat      — human-readable ASCII from Buckwalter (ktb, shrh, hmd)
  • root_normalized — Arabic with hamza/alef unified (for loose Arabic search)

Outputs: database/seeds/seed-al-roots-search.sql
  UPDATE ar_ling_roots SET buckwalter=…, simple_lat=…, root_normalized=… WHERE id=…;
  INSERT OR REPLACE INTO ar_ling_roots_fts …;

Run:
  python3 scripts/gen-root-search-keys.py
"""

import re
import sys
import pathlib
import unicodedata

REPO = pathlib.Path(__file__).resolve().parent.parent
SEED_IN  = REPO / "database/seeds/seed-al-roots.sql"
SEED_OUT = REPO / "database/seeds/seed-al-roots-search.sql"

# ── Buckwalter → simple ASCII Latin ─────────────────────────────────────────
# QUL Buckwalter alphabet:
#   consonants only; diacritics not present in root transliterations
_BW_TO_SIMPLE = {
    'A': 'a',   # ا (alef)
    "'": 'a',   # ء (hamza standalone)
    'b': 'b',   # ب
    't': 't',   # ت
    'v': 'th',  # ث
    'j': 'j',   # ج
    'H': 'h',   # ح  (use h; context distinguishes from ه)
    'x': 'kh',  # خ
    'd': 'd',   # د
    '*': 'dh',  # ذ
    'r': 'r',   # ر
    'z': 'z',   # ز
    's': 's',   # س
    '$': 'sh',  # ش
    'S': 's',   # ص  (emphatic → collapse)
    'D': 'd',   # ض  (emphatic → collapse)
    'T': 't',   # ط  (emphatic → collapse)
    'Z': 'z',   # ظ  (emphatic → collapse)
    'E': '',    # ع  (no ASCII; omit — the gap alone is distinctive)
    'g': 'gh',  # غ
    'f': 'f',   # ف
    'q': 'q',   # ق
    'k': 'k',   # ك
    'l': 'l',   # ل
    'm': 'm',   # م
    'n': 'n',   # ن
    'h': 'h',   # ه
    'w': 'w',   # و
    'y': 'y',   # ي
    # Extended / less common
    'p': 'h',   # ة (taa marbuta — not typical in roots but guard it)
    'Y': 'a',   # ى (alef maqsura)
    'W': 'w',   # ؤ
    'I': 'y',   # ئ
    '{': 'a',   # ٱ (wasla)
    'P': '',    # fatha (diacritic — skip)
    'F': '',    # tanwin fath
    'K': '',    # tanwin kasr
    'N': '',    # tanwin damm
    'a': '',    # fatha
    'i': '',    # kasra
    'u': '',    # damma
    'o': '',    # sukun
    '~': '',    # shadda
    '`': '',    # superscript alef
}

def bw_to_simple(bw: str) -> str:
    """Convert QUL Buckwalter root string to simple ASCII Latin."""
    return ''.join(_BW_TO_SIMPLE.get(c, c.lower()) for c in bw)

# ── Arabic → root_normalized (hamza/alef unification) ────────────────────────
# Map variant alef/hamza forms → ا, and ة→ه, ى→ي, ؤ→و, ئ→ي
_AR_NORM_MAP = str.maketrans({
    'أ': 'ا',  # alef with hamza above
    'إ': 'ا',  # alef with hamza below
    'آ': 'ا',  # alef with madda
    'ء': 'ا',  # hamza standalone
    'ٱ': 'ا',  # alef wasla
    'ؤ': 'و',  # waw with hamza
    'ئ': 'ي',  # ya with hamza
    'ة': 'ه',  # taa marbuta → ha
    'ى': 'ي',  # alef maqsura → ya
})

# Arabic diacritic codepoints to strip
_ARABIC_DIACRITICS = {
    '\u064B',  # FATHATAN
    '\u064C',  # DAMMATAN
    '\u064D',  # KASRATAN
    '\u064E',  # FATHA
    '\u064F',  # DAMMA
    '\u0650',  # KASRA
    '\u0651',  # SHADDA
    '\u0652',  # SUKUN
    '\u0653',  # MADDAH ABOVE
    '\u0654',  # HAMZA ABOVE
    '\u0655',  # HAMZA BELOW
    '\u0670',  # SUPERSCRIPT ALEF
}

def ar_normalize(text: str) -> str:
    """Normalize Arabic root for loose search: unify alef/hamza, strip diacritics."""
    text = text.translate(_AR_NORM_MAP)
    text = ''.join(c for c in text if c not in _ARABIC_DIACRITICS)
    return text

# ── Parse seed SQL ────────────────────────────────────────────────────────────
# Each row looks like:
#   ('ID26CHARS', 'root_text', '["ا","ب","ب"]', 'trilateral', 'sound', 28, 0, 'Bkw', NULL),

ROW_RE = re.compile(
    r"\(\s*'([^']{26})'\s*,\s*'([^']+)'\s*,\s*'[^']*'\s*,\s*'\w+'\s*,\s*'\w+'\s*,\s*\d+\s*,\s*\d+\s*,\s*(?:'([^']*)'|NULL)\s*,",
)

def parse_roots(path: pathlib.Path):
    roots = []
    for line in path.read_text(encoding='utf-8').splitlines():
        m = ROW_RE.search(line)
        if m:
            rid, root_text, bw = m.group(1), m.group(2), m.group(3) or ''
            roots.append((rid, root_text, bw))
    return roots

def sql_str(s):
    return "'" + s.replace("'", "''") + "'"

def main():
    print(f"Reading {SEED_IN} …")
    roots = parse_roots(SEED_IN)
    print(f"  → {len(roots)} roots parsed")

    lines = [
        "-- ═══════════════════════════════════════════════════════════════════════════",
        "-- K-MAPS GENERATED SEED — DO NOT EDIT BY HAND",
        "-- Generated by: scripts/gen-root-search-keys.py",
        "-- Populates buckwalter / simple_lat / root_normalized on ar_ling_roots",
        "-- Requires: migration 003_root_search_keys.sql applied first",
        "-- ═══════════════════════════════════════════════════════════════════════════",
        "",
        f"-- Rows: {len(roots)} roots",
        "",
        "-- ─── Step 1: Populate search key columns ────────────────────────────────",
    ]

    # Group into batches for readability — one UPDATE per row (D1 handles it fine)
    for rid, root_text, bw in roots:
        simple = bw_to_simple(bw)
        norm   = ar_normalize(root_text)
        lines.append(
            f"UPDATE ar_ling_roots SET"
            f" buckwalter={sql_str(bw)},"
            f" simple_lat={sql_str(simple)},"
            f" root_normalized={sql_str(norm)}"
            f" WHERE id={sql_str(rid)};"
        )

    lines += [
        "",
        "-- ─── Step 2: Populate FTS table ──────────────────────────────────────────",
        "-- Repopulate ar_ling_roots_fts (schema already rebuilt by migration 003)",
        "INSERT OR REPLACE INTO ar_ling_roots_fts",
        "  (id, root_text, root_normalized, buckwalter, simple_lat, meaning_core_en)",
        "SELECT id, root_text, root_normalized, buckwalter, simple_lat, meaning_core_en",
        "FROM ar_ling_roots;",
        "",
    ]

    out = '\n'.join(lines)
    SEED_OUT.write_text(out, encoding='utf-8')
    print(f"  → Written {SEED_OUT}")
    print(f"  → {len(roots)} UPDATE statements + 1 FTS INSERT")

    # Quick sanity check — show a few
    print("\nSample output:")
    for rid, root_text, bw in roots[:6]:
        simple = bw_to_simple(bw)
        norm   = ar_normalize(root_text)
        print(f"  {root_text:8s}  bw={bw:8s}  simple={simple:10s}  norm={norm}")

if __name__ == '__main__':
    main()
